// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: plainjson/plainjson.proto

package plainjson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How a message subtree is folded into its parent object.
type FlattenMode int32

const (
	FlattenMode_FLATTEN_MODE_UNSPECIFIED FlattenMode = 0
	// Recursively hoist every leaf of the subtree into the parent object.
	FlattenMode_FLATTEN_MODE_DEEP FlattenMode = 1
	// Hoist one level; message fields below stay nested objects.
	FlattenMode_FLATTEN_MODE_SHALLOW FlattenMode = 2
	// Keep the subtree as its own nested object.
	FlattenMode_FLATTEN_MODE_NONE FlattenMode = 3
)

// Enum value maps for FlattenMode.
var (
	FlattenMode_name = map[int32]string{
		0: "FLATTEN_MODE_UNSPECIFIED",
		1: "FLATTEN_MODE_DEEP",
		2: "FLATTEN_MODE_SHALLOW",
		3: "FLATTEN_MODE_NONE",
	}
	FlattenMode_value = map[string]int32{
		"FLATTEN_MODE_UNSPECIFIED": 0,
		"FLATTEN_MODE_DEEP":        1,
		"FLATTEN_MODE_SHALLOW":     2,
		"FLATTEN_MODE_NONE":        3,
	}
)

func (x FlattenMode) Enum() *FlattenMode {
	p := new(FlattenMode)
	*p = x
	return p
}

func (x FlattenMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlattenMode) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[0].Descriptor()
}

func (FlattenMode) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[0]
}

func (x FlattenMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlattenMode.Descriptor instead.
func (FlattenMode) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{0}
}

// How the JSON key of a flattened leaf is derived.
type KeyFrom int32

const (
	KeyFrom_KEY_FROM_UNSPECIFIED KeyFrom = 0
	// Name of the leaf field only. Different paths ending in the same field name
	// collapse onto one key; this is the point of flattening.
	KeyFrom_KEY_FROM_LEAF KeyFrom = 1
	// Every field name along the path from the generated message to the leaf,
	// joined. Collision-free by construction, at the cost of longer keys.
	KeyFrom_KEY_FROM_PATH KeyFrom = 2
)

// Enum value maps for KeyFrom.
var (
	KeyFrom_name = map[int32]string{
		0: "KEY_FROM_UNSPECIFIED",
		1: "KEY_FROM_LEAF",
		2: "KEY_FROM_PATH",
	}
	KeyFrom_value = map[string]int32{
		"KEY_FROM_UNSPECIFIED": 0,
		"KEY_FROM_LEAF":        1,
		"KEY_FROM_PATH":        2,
	}
)

func (x KeyFrom) Enum() *KeyFrom {
	p := new(KeyFrom)
	*p = x
	return p
}

func (x KeyFrom) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyFrom) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[1].Descriptor()
}

func (KeyFrom) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[1]
}

func (x KeyFrom) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyFrom.Descriptor instead.
func (KeyFrom) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{1}
}

// Casing applied to derived JSON keys.
type KeyCase int32

const (
	KeyCase_KEY_CASE_UNSPECIFIED KeyCase = 0
	// lowerCamelCase, matching protojson's json_name.
	KeyCase_KEY_CASE_CAMEL KeyCase = 1
	// snake_case.
	KeyCase_KEY_CASE_SNAKE KeyCase = 2
	// The proto field name, verbatim.
	KeyCase_KEY_CASE_ORIGINAL KeyCase = 3
)

// Enum value maps for KeyCase.
var (
	KeyCase_name = map[int32]string{
		0: "KEY_CASE_UNSPECIFIED",
		1: "KEY_CASE_CAMEL",
		2: "KEY_CASE_SNAKE",
		3: "KEY_CASE_ORIGINAL",
	}
	KeyCase_value = map[string]int32{
		"KEY_CASE_UNSPECIFIED": 0,
		"KEY_CASE_CAMEL":       1,
		"KEY_CASE_SNAKE":       2,
		"KEY_CASE_ORIGINAL":    3,
	}
)

func (x KeyCase) Enum() *KeyCase {
	p := new(KeyCase)
	*p = x
	return p
}

func (x KeyCase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyCase) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[2].Descriptor()
}

func (KeyCase) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[2]
}

func (x KeyCase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyCase.Descriptor instead.
func (KeyCase) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{2}
}

// What happens to a field that holds more than one value. This describes
// cardinality, not type, so it applies to `repeated` and `map` alike.
type Cardinality int32

const (
	Cardinality_CARDINALITY_UNSPECIFIED Cardinality = 0
	// repeated -> JSON array, map -> JSON object.
	Cardinality_CARDINALITY_KEEP Cardinality = 1
	// Only the first element. Maps iterate sorted by key, so this is the lowest key.
	Cardinality_CARDINALITY_FIRST Cardinality = 2
	// Only the last element; for maps, the highest key.
	Cardinality_CARDINALITY_LAST Cardinality = 3
	// Number of elements.
	Cardinality_CARDINALITY_COUNT Cardinality = 4
	// Scalar elements joined into one string with join_separator.
	Cardinality_CARDINALITY_JOIN Cardinality = 5
	// One key per element: <key><index_separator><i>, flattening below it.
	Cardinality_CARDINALITY_INDEXED Cardinality = 6
	// Every element's keys merged into the parent with no index. Elements that
	// produce the same key are resolved by the collision policy.
	Cardinality_CARDINALITY_EXPLODE Cardinality = 7
	// Map only: array of map keys.
	Cardinality_CARDINALITY_KEYS Cardinality = 8
	// Map only: array of map values.
	Cardinality_CARDINALITY_VALUES Cardinality = 9
	// Map only: map keys become JSON keys of the parent object. Collisions here
	// are only detectable at runtime.
	Cardinality_CARDINALITY_INLINE_KEYS Cardinality = 10
)

// Enum value maps for Cardinality.
var (
	Cardinality_name = map[int32]string{
		0:  "CARDINALITY_UNSPECIFIED",
		1:  "CARDINALITY_KEEP",
		2:  "CARDINALITY_FIRST",
		3:  "CARDINALITY_LAST",
		4:  "CARDINALITY_COUNT",
		5:  "CARDINALITY_JOIN",
		6:  "CARDINALITY_INDEXED",
		7:  "CARDINALITY_EXPLODE",
		8:  "CARDINALITY_KEYS",
		9:  "CARDINALITY_VALUES",
		10: "CARDINALITY_INLINE_KEYS",
	}
	Cardinality_value = map[string]int32{
		"CARDINALITY_UNSPECIFIED": 0,
		"CARDINALITY_KEEP":        1,
		"CARDINALITY_FIRST":       2,
		"CARDINALITY_LAST":        3,
		"CARDINALITY_COUNT":       4,
		"CARDINALITY_JOIN":        5,
		"CARDINALITY_INDEXED":     6,
		"CARDINALITY_EXPLODE":     7,
		"CARDINALITY_KEYS":        8,
		"CARDINALITY_VALUES":      9,
		"CARDINALITY_INLINE_KEYS": 10,
	}
)

func (x Cardinality) Enum() *Cardinality {
	p := new(Cardinality)
	*p = x
	return p
}

func (x Cardinality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cardinality) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[3].Descriptor()
}

func (Cardinality) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[3]
}

func (x Cardinality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cardinality.Descriptor instead.
func (Cardinality) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{3}
}

// How a oneof is rendered.
type OneofMode int32

const (
	OneofMode_ONEOF_MODE_UNSPECIFIED OneofMode = 0
	// Fields of the active branch are hoisted into the parent object. Default
	// when the enclosing flatten mode is DEEP or SHALLOW.
	OneofMode_ONEOF_MODE_INLINE OneofMode = 1
	// protojson shape: the branch field name is the key. Default under
	// FLATTEN_MODE_NONE.
	OneofMode_ONEOF_MODE_BRANCH_KEY OneofMode = 2
	// Branch fields are hoisted, plus a discriminator key naming the branch.
	OneofMode_ONEOF_MODE_TAGGED OneofMode = 3
	// One key (value_key) holding the branch value as an object.
	OneofMode_ONEOF_MODE_SINGLE_KEY OneofMode = 4
	// Only the discriminator key; the branch value is dropped.
	OneofMode_ONEOF_MODE_DISCRIMINATOR_ONLY OneofMode = 5
	// The oneof contributes nothing.
	OneofMode_ONEOF_MODE_OMIT OneofMode = 6
)

// Enum value maps for OneofMode.
var (
	OneofMode_name = map[int32]string{
		0: "ONEOF_MODE_UNSPECIFIED",
		1: "ONEOF_MODE_INLINE",
		2: "ONEOF_MODE_BRANCH_KEY",
		3: "ONEOF_MODE_TAGGED",
		4: "ONEOF_MODE_SINGLE_KEY",
		5: "ONEOF_MODE_DISCRIMINATOR_ONLY",
		6: "ONEOF_MODE_OMIT",
	}
	OneofMode_value = map[string]int32{
		"ONEOF_MODE_UNSPECIFIED":        0,
		"ONEOF_MODE_INLINE":             1,
		"ONEOF_MODE_BRANCH_KEY":         2,
		"ONEOF_MODE_TAGGED":             3,
		"ONEOF_MODE_SINGLE_KEY":         4,
		"ONEOF_MODE_DISCRIMINATOR_ONLY": 5,
		"ONEOF_MODE_OMIT":               6,
	}
)

func (x OneofMode) Enum() *OneofMode {
	p := new(OneofMode)
	*p = x
	return p
}

func (x OneofMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OneofMode) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[4].Descriptor()
}

func (OneofMode) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[4]
}

func (x OneofMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OneofMode.Descriptor instead.
func (OneofMode) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{4}
}

// What to do when two live sources produce the same JSON key. Sources that are
// mutually exclusive (oneof branches, declared exclusive groups, sources of one
// merge rule) never collide and are exempt from all policies.
type CollisionPolicy int32

const (
	CollisionPolicy_COLLISION_POLICY_UNSPECIFIED CollisionPolicy = 0
	// Keep one value per CollisionWins, silently. The default: under flattening,
	// colliding keys are the norm rather than an error.
	CollisionPolicy_COLLISION_POLICY_IGNORE CollisionPolicy = 1
	// Fail protoc for statically detectable collisions.
	CollisionPolicy_COLLISION_POLICY_ERROR_GENERATE CollisionPolicy = 2
	// Track written keys and fail at encode time on a real duplicate. The only
	// policy that catches dynamic collisions (INLINE_KEYS, EXPLODE, exclusive
	// groups that turn out not to be exclusive).
	CollisionPolicy_COLLISION_POLICY_ERROR_RUNTIME CollisionPolicy = 3
)

// Enum value maps for CollisionPolicy.
var (
	CollisionPolicy_name = map[int32]string{
		0: "COLLISION_POLICY_UNSPECIFIED",
		1: "COLLISION_POLICY_IGNORE",
		2: "COLLISION_POLICY_ERROR_GENERATE",
		3: "COLLISION_POLICY_ERROR_RUNTIME",
	}
	CollisionPolicy_value = map[string]int32{
		"COLLISION_POLICY_UNSPECIFIED":    0,
		"COLLISION_POLICY_IGNORE":         1,
		"COLLISION_POLICY_ERROR_GENERATE": 2,
		"COLLISION_POLICY_ERROR_RUNTIME":  3,
	}
)

func (x CollisionPolicy) Enum() *CollisionPolicy {
	p := new(CollisionPolicy)
	*p = x
	return p
}

func (x CollisionPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollisionPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[5].Descriptor()
}

func (CollisionPolicy) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[5]
}

func (x CollisionPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollisionPolicy.Descriptor instead.
func (CollisionPolicy) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{5}
}

// Which writer wins a collision under COLLISION_POLICY_IGNORE.
type CollisionWins int32

const (
	CollisionWins_COLLISION_WINS_UNSPECIFIED CollisionWins = 0
	// The first entry in traversal order that produces a non-empty value. Fully
	// streaming: the decision is made before the key is written.
	CollisionWins_COLLISION_WINS_FIRST CollisionWins = 1
	// The last writer. Requires buffering the object before flush.
	CollisionWins_COLLISION_WINS_LAST CollisionWins = 2
)

// Enum value maps for CollisionWins.
var (
	CollisionWins_name = map[int32]string{
		0: "COLLISION_WINS_UNSPECIFIED",
		1: "COLLISION_WINS_FIRST",
		2: "COLLISION_WINS_LAST",
	}
	CollisionWins_value = map[string]int32{
		"COLLISION_WINS_UNSPECIFIED": 0,
		"COLLISION_WINS_FIRST":       1,
		"COLLISION_WINS_LAST":        2,
	}
)

func (x CollisionWins) Enum() *CollisionWins {
	p := new(CollisionWins)
	*p = x
	return p
}

func (x CollisionWins) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollisionWins) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[6].Descriptor()
}

func (CollisionWins) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[6]
}

func (x CollisionWins) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollisionWins.Descriptor instead.
func (CollisionWins) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{6}
}

// How a merge rule resolves several non-empty sources.
type MergeConflict int32

const (
	MergeConflict_MERGE_CONFLICT_UNSPECIFIED MergeConflict = 0
	// First source in declaration order that has a value.
	MergeConflict_MERGE_CONFLICT_FIRST_NON_EMPTY MergeConflict = 1
	// Last source that has a value.
	MergeConflict_MERGE_CONFLICT_LAST_NON_EMPTY MergeConflict = 2
	// Fail at encode time if more than one source is non-empty.
	MergeConflict_MERGE_CONFLICT_ERROR MergeConflict = 3
)

// Enum value maps for MergeConflict.
var (
	MergeConflict_name = map[int32]string{
		0: "MERGE_CONFLICT_UNSPECIFIED",
		1: "MERGE_CONFLICT_FIRST_NON_EMPTY",
		2: "MERGE_CONFLICT_LAST_NON_EMPTY",
		3: "MERGE_CONFLICT_ERROR",
	}
	MergeConflict_value = map[string]int32{
		"MERGE_CONFLICT_UNSPECIFIED":     0,
		"MERGE_CONFLICT_FIRST_NON_EMPTY": 1,
		"MERGE_CONFLICT_LAST_NON_EMPTY":  2,
		"MERGE_CONFLICT_ERROR":           3,
	}
)

func (x MergeConflict) Enum() *MergeConflict {
	p := new(MergeConflict)
	*p = x
	return p
}

func (x MergeConflict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeConflict) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[7].Descriptor()
}

func (MergeConflict) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[7]
}

func (x MergeConflict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MergeConflict.Descriptor instead.
func (MergeConflict) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{7}
}

// Enum value representation.
type EnumFormat int32

const (
	EnumFormat_ENUM_FORMAT_UNSPECIFIED EnumFormat = 0
	// The value name, as protojson does.
	EnumFormat_ENUM_FORMAT_NAME EnumFormat = 1
	// The numeric value.
	EnumFormat_ENUM_FORMAT_NUMBER EnumFormat = 2
)

// Enum value maps for EnumFormat.
var (
	EnumFormat_name = map[int32]string{
		0: "ENUM_FORMAT_UNSPECIFIED",
		1: "ENUM_FORMAT_NAME",
		2: "ENUM_FORMAT_NUMBER",
	}
	EnumFormat_value = map[string]int32{
		"ENUM_FORMAT_UNSPECIFIED": 0,
		"ENUM_FORMAT_NAME":        1,
		"ENUM_FORMAT_NUMBER":      2,
	}
)

func (x EnumFormat) Enum() *EnumFormat {
	p := new(EnumFormat)
	*p = x
	return p
}

func (x EnumFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[8].Descriptor()
}

func (EnumFormat) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[8]
}

func (x EnumFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumFormat.Descriptor instead.
func (EnumFormat) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{8}
}

// 64-bit integer representation.
type Int64Format int32

const (
	Int64Format_INT64_FORMAT_UNSPECIFIED Int64Format = 0
	// JSON string, as protojson does.
	Int64Format_INT64_FORMAT_STRING Int64Format = 1
	// JSON number. Values beyond 2^53 lose precision in most JSON readers.
	Int64Format_INT64_FORMAT_NUMBER Int64Format = 2
)

// Enum value maps for Int64Format.
var (
	Int64Format_name = map[int32]string{
		0: "INT64_FORMAT_UNSPECIFIED",
		1: "INT64_FORMAT_STRING",
		2: "INT64_FORMAT_NUMBER",
	}
	Int64Format_value = map[string]int32{
		"INT64_FORMAT_UNSPECIFIED": 0,
		"INT64_FORMAT_STRING":      1,
		"INT64_FORMAT_NUMBER":      2,
	}
)

func (x Int64Format) Enum() *Int64Format {
	p := new(Int64Format)
	*p = x
	return p
}

func (x Int64Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Int64Format) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[9].Descriptor()
}

func (Int64Format) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[9]
}

func (x Int64Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Int64Format.Descriptor instead.
func (Int64Format) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{9}
}

// bytes representation.
type BytesFormat int32

const (
	BytesFormat_BYTES_FORMAT_UNSPECIFIED BytesFormat = 0
	// Standard padded base64, as protojson does.
	BytesFormat_BYTES_FORMAT_BASE64 BytesFormat = 1
	// URL-safe base64, unpadded.
	BytesFormat_BYTES_FORMAT_BASE64_URL BytesFormat = 2
	// Lowercase hex.
	BytesFormat_BYTES_FORMAT_HEX BytesFormat = 3
	// Array of byte values.
	BytesFormat_BYTES_FORMAT_ARRAY BytesFormat = 4
)

// Enum value maps for BytesFormat.
var (
	BytesFormat_name = map[int32]string{
		0: "BYTES_FORMAT_UNSPECIFIED",
		1: "BYTES_FORMAT_BASE64",
		2: "BYTES_FORMAT_BASE64_URL",
		3: "BYTES_FORMAT_HEX",
		4: "BYTES_FORMAT_ARRAY",
	}
	BytesFormat_value = map[string]int32{
		"BYTES_FORMAT_UNSPECIFIED": 0,
		"BYTES_FORMAT_BASE64":      1,
		"BYTES_FORMAT_BASE64_URL":  2,
		"BYTES_FORMAT_HEX":         3,
		"BYTES_FORMAT_ARRAY":       4,
	}
)

func (x BytesFormat) Enum() *BytesFormat {
	p := new(BytesFormat)
	*p = x
	return p
}

func (x BytesFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BytesFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[10].Descriptor()
}

func (BytesFormat) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[10]
}

func (x BytesFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BytesFormat.Descriptor instead.
func (BytesFormat) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{10}
}

// google.protobuf.Timestamp representation.
type TimeFormat int32

const (
	TimeFormat_TIME_FORMAT_UNSPECIFIED TimeFormat = 0
	// RFC 3339 string, as protojson does.
	TimeFormat_TIME_FORMAT_RFC3339      TimeFormat = 1
	TimeFormat_TIME_FORMAT_UNIX_SECONDS TimeFormat = 2
	TimeFormat_TIME_FORMAT_UNIX_MILLI   TimeFormat = 3
	TimeFormat_TIME_FORMAT_UNIX_MICRO   TimeFormat = 4
	TimeFormat_TIME_FORMAT_UNIX_NANO    TimeFormat = 5
)

// Enum value maps for TimeFormat.
var (
	TimeFormat_name = map[int32]string{
		0: "TIME_FORMAT_UNSPECIFIED",
		1: "TIME_FORMAT_RFC3339",
		2: "TIME_FORMAT_UNIX_SECONDS",
		3: "TIME_FORMAT_UNIX_MILLI",
		4: "TIME_FORMAT_UNIX_MICRO",
		5: "TIME_FORMAT_UNIX_NANO",
	}
	TimeFormat_value = map[string]int32{
		"TIME_FORMAT_UNSPECIFIED":  0,
		"TIME_FORMAT_RFC3339":      1,
		"TIME_FORMAT_UNIX_SECONDS": 2,
		"TIME_FORMAT_UNIX_MILLI":   3,
		"TIME_FORMAT_UNIX_MICRO":   4,
		"TIME_FORMAT_UNIX_NANO":    5,
	}
)

func (x TimeFormat) Enum() *TimeFormat {
	p := new(TimeFormat)
	*p = x
	return p
}

func (x TimeFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[11].Descriptor()
}

func (TimeFormat) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[11]
}

func (x TimeFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeFormat.Descriptor instead.
func (TimeFormat) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{11}
}

// google.protobuf.Duration representation.
type DurationFormat int32

const (
	DurationFormat_DURATION_FORMAT_UNSPECIFIED DurationFormat = 0
	// Seconds with a fractional part and an "s" suffix, as protojson does.
	DurationFormat_DURATION_FORMAT_PROTOJSON DurationFormat = 1
	// Number of seconds.
	DurationFormat_DURATION_FORMAT_SECONDS DurationFormat = 2
	// Number of milliseconds.
	DurationFormat_DURATION_FORMAT_MILLIS DurationFormat = 3
	// Number of nanoseconds.
	DurationFormat_DURATION_FORMAT_NANOS DurationFormat = 4
)

// Enum value maps for DurationFormat.
var (
	DurationFormat_name = map[int32]string{
		0: "DURATION_FORMAT_UNSPECIFIED",
		1: "DURATION_FORMAT_PROTOJSON",
		2: "DURATION_FORMAT_SECONDS",
		3: "DURATION_FORMAT_MILLIS",
		4: "DURATION_FORMAT_NANOS",
	}
	DurationFormat_value = map[string]int32{
		"DURATION_FORMAT_UNSPECIFIED": 0,
		"DURATION_FORMAT_PROTOJSON":   1,
		"DURATION_FORMAT_SECONDS":     2,
		"DURATION_FORMAT_MILLIS":      3,
		"DURATION_FORMAT_NANOS":       4,
	}
)

func (x DurationFormat) Enum() *DurationFormat {
	p := new(DurationFormat)
	*p = x
	return p
}

func (x DurationFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DurationFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_plainjson_plainjson_proto_enumTypes[12].Descriptor()
}

func (DurationFormat) Type() protoreflect.EnumType {
	return &file_plainjson_plainjson_proto_enumTypes[12]
}

func (x DurationFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DurationFormat.Descriptor instead.
func (DurationFormat) EnumDescriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{12}
}

// One hoisted path inside a field's subtree.
type Lift struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dot-separated field path relative to the annotated field. Must resolve to
	// a leaf.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// JSON key for the lifted value. Empty means the leaf's own name.
	As            string `protobuf:"bytes,2,opt,name=as,proto3" json:"as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lift) Reset() {
	*x = Lift{}
	mi := &file_plainjson_plainjson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lift) ProtoMessage() {}

func (x *Lift) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lift.ProtoReflect.Descriptor instead.
func (*Lift) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{0}
}

func (x *Lift) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Lift) GetAs() string {
	if x != nil {
		return x.As
	}
	return ""
}

// Collects several source paths into one key, in priority order.
type MergeRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON key produced.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Dot-separated paths relative to the annotated message, in priority order.
	// These paths are removed from the normal flatten plan.
	From []string `protobuf:"bytes,2,rep,name=from,proto3" json:"from,omitempty"`
	// How several non-empty sources are resolved.
	OnConflict MergeConflict `protobuf:"varint,3,opt,name=on_conflict,json=onConflict,proto3,enum=plainjson.MergeConflict" json:"on_conflict,omitempty"`
	// Emit the key even when every source is empty.
	EmitEmpty *bool `protobuf:"varint,4,opt,name=emit_empty,json=emitEmpty,proto3,oneof" json:"emit_empty,omitempty"`
	// Use `key` verbatim, ignoring key_case.
	RawKey bool `protobuf:"varint,5,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	// Value formatting for the merged value; unset means inherit.
	Cardinality    Cardinality    `protobuf:"varint,10,opt,name=cardinality,proto3,enum=plainjson.Cardinality" json:"cardinality,omitempty"`
	JoinSeparator  string         `protobuf:"bytes,11,opt,name=join_separator,json=joinSeparator,proto3" json:"join_separator,omitempty"`
	EnumFormat     EnumFormat     `protobuf:"varint,20,opt,name=enum_format,json=enumFormat,proto3,enum=plainjson.EnumFormat" json:"enum_format,omitempty"`
	Int64Format    Int64Format    `protobuf:"varint,21,opt,name=int64_format,json=int64Format,proto3,enum=plainjson.Int64Format" json:"int64_format,omitempty"`
	BytesFormat    BytesFormat    `protobuf:"varint,22,opt,name=bytes_format,json=bytesFormat,proto3,enum=plainjson.BytesFormat" json:"bytes_format,omitempty"`
	TimeFormat     TimeFormat     `protobuf:"varint,23,opt,name=time_format,json=timeFormat,proto3,enum=plainjson.TimeFormat" json:"time_format,omitempty"`
	DurationFormat DurationFormat `protobuf:"varint,24,opt,name=duration_format,json=durationFormat,proto3,enum=plainjson.DurationFormat" json:"duration_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MergeRule) Reset() {
	*x = MergeRule{}
	mi := &file_plainjson_plainjson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRule) ProtoMessage() {}

func (x *MergeRule) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRule.ProtoReflect.Descriptor instead.
func (*MergeRule) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{1}
}

func (x *MergeRule) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MergeRule) GetFrom() []string {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MergeRule) GetOnConflict() MergeConflict {
	if x != nil {
		return x.OnConflict
	}
	return MergeConflict_MERGE_CONFLICT_UNSPECIFIED
}

func (x *MergeRule) GetEmitEmpty() bool {
	if x != nil && x.EmitEmpty != nil {
		return *x.EmitEmpty
	}
	return false
}

func (x *MergeRule) GetRawKey() bool {
	if x != nil {
		return x.RawKey
	}
	return false
}

func (x *MergeRule) GetCardinality() Cardinality {
	if x != nil {
		return x.Cardinality
	}
	return Cardinality_CARDINALITY_UNSPECIFIED
}

func (x *MergeRule) GetJoinSeparator() string {
	if x != nil {
		return x.JoinSeparator
	}
	return ""
}

func (x *MergeRule) GetEnumFormat() EnumFormat {
	if x != nil {
		return x.EnumFormat
	}
	return EnumFormat_ENUM_FORMAT_UNSPECIFIED
}

func (x *MergeRule) GetInt64Format() Int64Format {
	if x != nil {
		return x.Int64Format
	}
	return Int64Format_INT64_FORMAT_UNSPECIFIED
}

func (x *MergeRule) GetBytesFormat() BytesFormat {
	if x != nil {
		return x.BytesFormat
	}
	return BytesFormat_BYTES_FORMAT_UNSPECIFIED
}

func (x *MergeRule) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *MergeRule) GetDurationFormat() DurationFormat {
	if x != nil {
		return x.DurationFormat
	}
	return DurationFormat_DURATION_FORMAT_UNSPECIFIED
}

// A fixed key/value pair with no protobuf source.
type Constant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Raw JSON value, for example "\"v1\"" or "[1,2]". Must parse as JSON.
	ValueJson string `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	// Use `key` verbatim, ignoring key_case.
	RawKey        bool `protobuf:"varint,3,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constant) Reset() {
	*x = Constant{}
	mi := &file_plainjson_plainjson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constant) ProtoMessage() {}

func (x *Constant) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constant.ProtoReflect.Descriptor instead.
func (*Constant) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{2}
}

func (x *Constant) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Constant) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *Constant) GetRawKey() bool {
	if x != nil {
		return x.RawKey
	}
	return false
}

// A set of fields that never carry a value at the same time. Members may share
// JSON keys without being reported as a collision.
type ExclusiveGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field names, or dot paths for deeper fields, relative to the message.
	Fields        []string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExclusiveGroup) Reset() {
	*x = ExclusiveGroup{}
	mi := &file_plainjson_plainjson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExclusiveGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusiveGroup) ProtoMessage() {}

func (x *ExclusiveGroup) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusiveGroup.ProtoReflect.Descriptor instead.
func (*ExclusiveGroup) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{3}
}

func (x *ExclusiveGroup) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// File-level defaults for every message in the file.
type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate marshalers for every message in the file. Per-message
	// `generate: false` still opts out.
	GenerateAll bool `protobuf:"varint,1,opt,name=generate_all,json=generateAll,proto3" json:"generate_all,omitempty"`
	// Default for MessageOptions.override_marshal_json.
	OverrideMarshalJson bool        `protobuf:"varint,2,opt,name=override_marshal_json,json=overrideMarshalJson,proto3" json:"override_marshal_json,omitempty"`
	Flatten             FlattenMode `protobuf:"varint,10,opt,name=flatten,proto3,enum=plainjson.FlattenMode" json:"flatten,omitempty"`
	KeyFrom             KeyFrom     `protobuf:"varint,11,opt,name=key_from,json=keyFrom,proto3,enum=plainjson.KeyFrom" json:"key_from,omitempty"`
	KeyCase             KeyCase     `protobuf:"varint,12,opt,name=key_case,json=keyCase,proto3,enum=plainjson.KeyCase" json:"key_case,omitempty"`
	// Message levels to descend before leaving the rest nested. 0 = unlimited;
	// optional so a message can lift a file-level bound.
	MaxDepth *uint32 `protobuf:"varint,13,opt,name=max_depth,json=maxDepth,proto3,oneof" json:"max_depth,omitempty"`
	// Emit keys whose value is empty or zero.
	EmitEmpty       *bool           `protobuf:"varint,14,opt,name=emit_empty,json=emitEmpty,proto3,oneof" json:"emit_empty,omitempty"`
	CollisionPolicy CollisionPolicy `protobuf:"varint,20,opt,name=collision_policy,json=collisionPolicy,proto3,enum=plainjson.CollisionPolicy" json:"collision_policy,omitempty"`
	CollisionWins   CollisionWins   `protobuf:"varint,21,opt,name=collision_wins,json=collisionWins,proto3,enum=plainjson.CollisionWins" json:"collision_wins,omitempty"`
	Cardinality     Cardinality     `protobuf:"varint,30,opt,name=cardinality,proto3,enum=plainjson.Cardinality" json:"cardinality,omitempty"`
	// Separator for CARDINALITY_JOIN. Empty means ",".
	JoinSeparator string `protobuf:"bytes,31,opt,name=join_separator,json=joinSeparator,proto3" json:"join_separator,omitempty"`
	// Separator for CARDINALITY_INDEXED. Empty means "_".
	IndexSeparator string         `protobuf:"bytes,32,opt,name=index_separator,json=indexSeparator,proto3" json:"index_separator,omitempty"`
	EnumFormat     EnumFormat     `protobuf:"varint,40,opt,name=enum_format,json=enumFormat,proto3,enum=plainjson.EnumFormat" json:"enum_format,omitempty"`
	Int64Format    Int64Format    `protobuf:"varint,41,opt,name=int64_format,json=int64Format,proto3,enum=plainjson.Int64Format" json:"int64_format,omitempty"`
	BytesFormat    BytesFormat    `protobuf:"varint,42,opt,name=bytes_format,json=bytesFormat,proto3,enum=plainjson.BytesFormat" json:"bytes_format,omitempty"`
	TimeFormat     TimeFormat     `protobuf:"varint,43,opt,name=time_format,json=timeFormat,proto3,enum=plainjson.TimeFormat" json:"time_format,omitempty"`
	DurationFormat DurationFormat `protobuf:"varint,44,opt,name=duration_format,json=durationFormat,proto3,enum=plainjson.DurationFormat" json:"duration_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_plainjson_plainjson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{4}
}

func (x *FileOptions) GetGenerateAll() bool {
	if x != nil {
		return x.GenerateAll
	}
	return false
}

func (x *FileOptions) GetOverrideMarshalJson() bool {
	if x != nil {
		return x.OverrideMarshalJson
	}
	return false
}

func (x *FileOptions) GetFlatten() FlattenMode {
	if x != nil {
		return x.Flatten
	}
	return FlattenMode_FLATTEN_MODE_UNSPECIFIED
}

func (x *FileOptions) GetKeyFrom() KeyFrom {
	if x != nil {
		return x.KeyFrom
	}
	return KeyFrom_KEY_FROM_UNSPECIFIED
}

func (x *FileOptions) GetKeyCase() KeyCase {
	if x != nil {
		return x.KeyCase
	}
	return KeyCase_KEY_CASE_UNSPECIFIED
}

func (x *FileOptions) GetMaxDepth() uint32 {
	if x != nil && x.MaxDepth != nil {
		return *x.MaxDepth
	}
	return 0
}

func (x *FileOptions) GetEmitEmpty() bool {
	if x != nil && x.EmitEmpty != nil {
		return *x.EmitEmpty
	}
	return false
}

func (x *FileOptions) GetCollisionPolicy() CollisionPolicy {
	if x != nil {
		return x.CollisionPolicy
	}
	return CollisionPolicy_COLLISION_POLICY_UNSPECIFIED
}

func (x *FileOptions) GetCollisionWins() CollisionWins {
	if x != nil {
		return x.CollisionWins
	}
	return CollisionWins_COLLISION_WINS_UNSPECIFIED
}

func (x *FileOptions) GetCardinality() Cardinality {
	if x != nil {
		return x.Cardinality
	}
	return Cardinality_CARDINALITY_UNSPECIFIED
}

func (x *FileOptions) GetJoinSeparator() string {
	if x != nil {
		return x.JoinSeparator
	}
	return ""
}

func (x *FileOptions) GetIndexSeparator() string {
	if x != nil {
		return x.IndexSeparator
	}
	return ""
}

func (x *FileOptions) GetEnumFormat() EnumFormat {
	if x != nil {
		return x.EnumFormat
	}
	return EnumFormat_ENUM_FORMAT_UNSPECIFIED
}

func (x *FileOptions) GetInt64Format() Int64Format {
	if x != nil {
		return x.Int64Format
	}
	return Int64Format_INT64_FORMAT_UNSPECIFIED
}

func (x *FileOptions) GetBytesFormat() BytesFormat {
	if x != nil {
		return x.BytesFormat
	}
	return BytesFormat_BYTES_FORMAT_UNSPECIFIED
}

func (x *FileOptions) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *FileOptions) GetDurationFormat() DurationFormat {
	if x != nil {
		return x.DurationFormat
	}
	return DurationFormat_DURATION_FORMAT_UNSPECIFIED
}

// Message-level options. Every formatting option overrides the file value.
type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Emit MarshalPlainJSON/EncodePlainJSON for this message. Optional so that
	// `generate: false` can opt out of a file-level generate_all; unset means
	// inherit.
	Generate *bool `protobuf:"varint,1,opt,name=generate,proto3,oneof" json:"generate,omitempty"`
	// Also emit MarshalJSON, so encoding/json produces the flat form.
	OverrideMarshalJson *bool           `protobuf:"varint,2,opt,name=override_marshal_json,json=overrideMarshalJson,proto3,oneof" json:"override_marshal_json,omitempty"`
	Flatten             FlattenMode     `protobuf:"varint,10,opt,name=flatten,proto3,enum=plainjson.FlattenMode" json:"flatten,omitempty"`
	KeyFrom             KeyFrom         `protobuf:"varint,11,opt,name=key_from,json=keyFrom,proto3,enum=plainjson.KeyFrom" json:"key_from,omitempty"`
	KeyCase             KeyCase         `protobuf:"varint,12,opt,name=key_case,json=keyCase,proto3,enum=plainjson.KeyCase" json:"key_case,omitempty"`
	MaxDepth            *uint32         `protobuf:"varint,13,opt,name=max_depth,json=maxDepth,proto3,oneof" json:"max_depth,omitempty"`
	EmitEmpty           *bool           `protobuf:"varint,14,opt,name=emit_empty,json=emitEmpty,proto3,oneof" json:"emit_empty,omitempty"`
	CollisionPolicy     CollisionPolicy `protobuf:"varint,20,opt,name=collision_policy,json=collisionPolicy,proto3,enum=plainjson.CollisionPolicy" json:"collision_policy,omitempty"`
	CollisionWins       CollisionWins   `protobuf:"varint,21,opt,name=collision_wins,json=collisionWins,proto3,enum=plainjson.CollisionWins" json:"collision_wins,omitempty"`
	Cardinality         Cardinality     `protobuf:"varint,30,opt,name=cardinality,proto3,enum=plainjson.Cardinality" json:"cardinality,omitempty"`
	JoinSeparator       string          `protobuf:"bytes,31,opt,name=join_separator,json=joinSeparator,proto3" json:"join_separator,omitempty"`
	IndexSeparator      string          `protobuf:"bytes,32,opt,name=index_separator,json=indexSeparator,proto3" json:"index_separator,omitempty"`
	EnumFormat          EnumFormat      `protobuf:"varint,40,opt,name=enum_format,json=enumFormat,proto3,enum=plainjson.EnumFormat" json:"enum_format,omitempty"`
	Int64Format         Int64Format     `protobuf:"varint,41,opt,name=int64_format,json=int64Format,proto3,enum=plainjson.Int64Format" json:"int64_format,omitempty"`
	BytesFormat         BytesFormat     `protobuf:"varint,42,opt,name=bytes_format,json=bytesFormat,proto3,enum=plainjson.BytesFormat" json:"bytes_format,omitempty"`
	TimeFormat          TimeFormat      `protobuf:"varint,43,opt,name=time_format,json=timeFormat,proto3,enum=plainjson.TimeFormat" json:"time_format,omitempty"`
	DurationFormat      DurationFormat  `protobuf:"varint,44,opt,name=duration_format,json=durationFormat,proto3,enum=plainjson.DurationFormat" json:"duration_format,omitempty"`
	// Coalesce several source paths into one key.
	Merge []*MergeRule `protobuf:"bytes,50,rep,name=merge,proto3" json:"merge,omitempty"`
	// Fixed key/value pairs, emitted first in declaration order.
	Constants []*Constant `protobuf:"bytes,51,rep,name=constants,proto3" json:"constants,omitempty"`
	// Field sets that are mutually exclusive in practice.
	ExclusiveGroups []*ExclusiveGroup `protobuf:"bytes,52,rep,name=exclusive_groups,json=exclusiveGroups,proto3" json:"exclusive_groups,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_plainjson_plainjson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{5}
}

func (x *MessageOptions) GetGenerate() bool {
	if x != nil && x.Generate != nil {
		return *x.Generate
	}
	return false
}

func (x *MessageOptions) GetOverrideMarshalJson() bool {
	if x != nil && x.OverrideMarshalJson != nil {
		return *x.OverrideMarshalJson
	}
	return false
}

func (x *MessageOptions) GetFlatten() FlattenMode {
	if x != nil {
		return x.Flatten
	}
	return FlattenMode_FLATTEN_MODE_UNSPECIFIED
}

func (x *MessageOptions) GetKeyFrom() KeyFrom {
	if x != nil {
		return x.KeyFrom
	}
	return KeyFrom_KEY_FROM_UNSPECIFIED
}

func (x *MessageOptions) GetKeyCase() KeyCase {
	if x != nil {
		return x.KeyCase
	}
	return KeyCase_KEY_CASE_UNSPECIFIED
}

func (x *MessageOptions) GetMaxDepth() uint32 {
	if x != nil && x.MaxDepth != nil {
		return *x.MaxDepth
	}
	return 0
}

func (x *MessageOptions) GetEmitEmpty() bool {
	if x != nil && x.EmitEmpty != nil {
		return *x.EmitEmpty
	}
	return false
}

func (x *MessageOptions) GetCollisionPolicy() CollisionPolicy {
	if x != nil {
		return x.CollisionPolicy
	}
	return CollisionPolicy_COLLISION_POLICY_UNSPECIFIED
}

func (x *MessageOptions) GetCollisionWins() CollisionWins {
	if x != nil {
		return x.CollisionWins
	}
	return CollisionWins_COLLISION_WINS_UNSPECIFIED
}

func (x *MessageOptions) GetCardinality() Cardinality {
	if x != nil {
		return x.Cardinality
	}
	return Cardinality_CARDINALITY_UNSPECIFIED
}

func (x *MessageOptions) GetJoinSeparator() string {
	if x != nil {
		return x.JoinSeparator
	}
	return ""
}

func (x *MessageOptions) GetIndexSeparator() string {
	if x != nil {
		return x.IndexSeparator
	}
	return ""
}

func (x *MessageOptions) GetEnumFormat() EnumFormat {
	if x != nil {
		return x.EnumFormat
	}
	return EnumFormat_ENUM_FORMAT_UNSPECIFIED
}

func (x *MessageOptions) GetInt64Format() Int64Format {
	if x != nil {
		return x.Int64Format
	}
	return Int64Format_INT64_FORMAT_UNSPECIFIED
}

func (x *MessageOptions) GetBytesFormat() BytesFormat {
	if x != nil {
		return x.BytesFormat
	}
	return BytesFormat_BYTES_FORMAT_UNSPECIFIED
}

func (x *MessageOptions) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *MessageOptions) GetDurationFormat() DurationFormat {
	if x != nil {
		return x.DurationFormat
	}
	return DurationFormat_DURATION_FORMAT_UNSPECIFIED
}

func (x *MessageOptions) GetMerge() []*MergeRule {
	if x != nil {
		return x.Merge
	}
	return nil
}

func (x *MessageOptions) GetConstants() []*Constant {
	if x != nil {
		return x.Constants
	}
	return nil
}

func (x *MessageOptions) GetExclusiveGroups() []*ExclusiveGroup {
	if x != nil {
		return x.ExclusiveGroups
	}
	return nil
}

// Oneof-level options, declared inside the oneof block.
type OneofOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How this oneof is rendered.
	Mode OneofMode `protobuf:"varint,1,opt,name=mode,proto3,enum=plainjson.OneofMode" json:"mode,omitempty"`
	// Key holding the branch tag under TAGGED / DISCRIMINATOR_ONLY.
	// Empty means "type".
	Discriminator string `protobuf:"bytes,2,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	// Key holding the value under SINGLE_KEY. Empty means the oneof name.
	ValueKey string `protobuf:"bytes,3,opt,name=value_key,json=valueKey,proto3" json:"value_key,omitempty"`
	// When no branch is set, write nothing. False writes null under the
	// discriminator or value key. Unset means true.
	OmitIfUnset    *bool          `protobuf:"varint,4,opt,name=omit_if_unset,json=omitIfUnset,proto3,oneof" json:"omit_if_unset,omitempty"`
	KeyFrom        KeyFrom        `protobuf:"varint,11,opt,name=key_from,json=keyFrom,proto3,enum=plainjson.KeyFrom" json:"key_from,omitempty"`
	KeyCase        KeyCase        `protobuf:"varint,12,opt,name=key_case,json=keyCase,proto3,enum=plainjson.KeyCase" json:"key_case,omitempty"`
	EmitEmpty      *bool          `protobuf:"varint,14,opt,name=emit_empty,json=emitEmpty,proto3,oneof" json:"emit_empty,omitempty"`
	Cardinality    Cardinality    `protobuf:"varint,30,opt,name=cardinality,proto3,enum=plainjson.Cardinality" json:"cardinality,omitempty"`
	JoinSeparator  string         `protobuf:"bytes,31,opt,name=join_separator,json=joinSeparator,proto3" json:"join_separator,omitempty"`
	IndexSeparator string         `protobuf:"bytes,32,opt,name=index_separator,json=indexSeparator,proto3" json:"index_separator,omitempty"`
	EnumFormat     EnumFormat     `protobuf:"varint,40,opt,name=enum_format,json=enumFormat,proto3,enum=plainjson.EnumFormat" json:"enum_format,omitempty"`
	Int64Format    Int64Format    `protobuf:"varint,41,opt,name=int64_format,json=int64Format,proto3,enum=plainjson.Int64Format" json:"int64_format,omitempty"`
	BytesFormat    BytesFormat    `protobuf:"varint,42,opt,name=bytes_format,json=bytesFormat,proto3,enum=plainjson.BytesFormat" json:"bytes_format,omitempty"`
	TimeFormat     TimeFormat     `protobuf:"varint,43,opt,name=time_format,json=timeFormat,proto3,enum=plainjson.TimeFormat" json:"time_format,omitempty"`
	DurationFormat DurationFormat `protobuf:"varint,44,opt,name=duration_format,json=durationFormat,proto3,enum=plainjson.DurationFormat" json:"duration_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_plainjson_plainjson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{6}
}

func (x *OneofOptions) GetMode() OneofMode {
	if x != nil {
		return x.Mode
	}
	return OneofMode_ONEOF_MODE_UNSPECIFIED
}

func (x *OneofOptions) GetDiscriminator() string {
	if x != nil {
		return x.Discriminator
	}
	return ""
}

func (x *OneofOptions) GetValueKey() string {
	if x != nil {
		return x.ValueKey
	}
	return ""
}

func (x *OneofOptions) GetOmitIfUnset() bool {
	if x != nil && x.OmitIfUnset != nil {
		return *x.OmitIfUnset
	}
	return false
}

func (x *OneofOptions) GetKeyFrom() KeyFrom {
	if x != nil {
		return x.KeyFrom
	}
	return KeyFrom_KEY_FROM_UNSPECIFIED
}

func (x *OneofOptions) GetKeyCase() KeyCase {
	if x != nil {
		return x.KeyCase
	}
	return KeyCase_KEY_CASE_UNSPECIFIED
}

func (x *OneofOptions) GetEmitEmpty() bool {
	if x != nil && x.EmitEmpty != nil {
		return *x.EmitEmpty
	}
	return false
}

func (x *OneofOptions) GetCardinality() Cardinality {
	if x != nil {
		return x.Cardinality
	}
	return Cardinality_CARDINALITY_UNSPECIFIED
}

func (x *OneofOptions) GetJoinSeparator() string {
	if x != nil {
		return x.JoinSeparator
	}
	return ""
}

func (x *OneofOptions) GetIndexSeparator() string {
	if x != nil {
		return x.IndexSeparator
	}
	return ""
}

func (x *OneofOptions) GetEnumFormat() EnumFormat {
	if x != nil {
		return x.EnumFormat
	}
	return EnumFormat_ENUM_FORMAT_UNSPECIFIED
}

func (x *OneofOptions) GetInt64Format() Int64Format {
	if x != nil {
		return x.Int64Format
	}
	return Int64Format_INT64_FORMAT_UNSPECIFIED
}

func (x *OneofOptions) GetBytesFormat() BytesFormat {
	if x != nil {
		return x.BytesFormat
	}
	return BytesFormat_BYTES_FORMAT_UNSPECIFIED
}

func (x *OneofOptions) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *OneofOptions) GetDurationFormat() DurationFormat {
	if x != nil {
		return x.DurationFormat
	}
	return DurationFormat_DURATION_FORMAT_UNSPECIFIED
}

// Field-level options.
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Drop the field and its whole subtree.
	Omit bool `protobuf:"varint,1,opt,name=omit,proto3" json:"omit,omitempty"`
	// Replace this path segment's name. Accumulated prefixes still apply.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Prepended to every key produced by this subtree. Accumulates across levels.
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Appended to every key produced by this subtree. Accumulates across levels.
	Suffix string `protobuf:"bytes,4,opt,name=suffix,proto3" json:"suffix,omitempty"`
	// Boundary decision only: is this message field inlined into its parent
	// (DEEP/SHALLOW) or does it keep its own key (NONE). What happens below the
	// boundary is decided by the field type's own flatten mode. Use max_depth to
	// bound a subtree from the outside.
	Flatten FlattenMode `protobuf:"varint,5,opt,name=flatten,proto3,enum=plainjson.FlattenMode" json:"flatten,omitempty"`
	// Dot path inside this field; the field is replaced by that single value.
	// Mutually exclusive with lift.
	Pick string `protobuf:"bytes,6,opt,name=pick,proto3" json:"pick,omitempty"`
	// Hoist selected paths out of the subtree; the rest of it is dropped.
	// Mutually exclusive with pick.
	Lift []*Lift `protobuf:"bytes,7,rep,name=lift,proto3" json:"lift,omitempty"`
	// Discriminator value when this field is a oneof branch. Empty means the
	// branch field name.
	Tag string `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	// Depth limit for this subtree. 0 = unlimited.
	MaxDepth       *uint32        `protobuf:"varint,9,opt,name=max_depth,json=maxDepth,proto3,oneof" json:"max_depth,omitempty"`
	Cardinality    Cardinality    `protobuf:"varint,20,opt,name=cardinality,proto3,enum=plainjson.Cardinality" json:"cardinality,omitempty"`
	JoinSeparator  string         `protobuf:"bytes,21,opt,name=join_separator,json=joinSeparator,proto3" json:"join_separator,omitempty"`
	IndexSeparator string         `protobuf:"bytes,22,opt,name=index_separator,json=indexSeparator,proto3" json:"index_separator,omitempty"`
	KeyFrom        KeyFrom        `protobuf:"varint,30,opt,name=key_from,json=keyFrom,proto3,enum=plainjson.KeyFrom" json:"key_from,omitempty"`
	KeyCase        KeyCase        `protobuf:"varint,31,opt,name=key_case,json=keyCase,proto3,enum=plainjson.KeyCase" json:"key_case,omitempty"`
	EmitEmpty      *bool          `protobuf:"varint,32,opt,name=emit_empty,json=emitEmpty,proto3,oneof" json:"emit_empty,omitempty"`
	EnumFormat     EnumFormat     `protobuf:"varint,40,opt,name=enum_format,json=enumFormat,proto3,enum=plainjson.EnumFormat" json:"enum_format,omitempty"`
	Int64Format    Int64Format    `protobuf:"varint,41,opt,name=int64_format,json=int64Format,proto3,enum=plainjson.Int64Format" json:"int64_format,omitempty"`
	BytesFormat    BytesFormat    `protobuf:"varint,42,opt,name=bytes_format,json=bytesFormat,proto3,enum=plainjson.BytesFormat" json:"bytes_format,omitempty"`
	TimeFormat     TimeFormat     `protobuf:"varint,43,opt,name=time_format,json=timeFormat,proto3,enum=plainjson.TimeFormat" json:"time_format,omitempty"`
	DurationFormat DurationFormat `protobuf:"varint,44,opt,name=duration_format,json=durationFormat,proto3,enum=plainjson.DurationFormat" json:"duration_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_plainjson_plainjson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{7}
}

func (x *FieldOptions) GetOmit() bool {
	if x != nil {
		return x.Omit
	}
	return false
}

func (x *FieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldOptions) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *FieldOptions) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *FieldOptions) GetFlatten() FlattenMode {
	if x != nil {
		return x.Flatten
	}
	return FlattenMode_FLATTEN_MODE_UNSPECIFIED
}

func (x *FieldOptions) GetPick() string {
	if x != nil {
		return x.Pick
	}
	return ""
}

func (x *FieldOptions) GetLift() []*Lift {
	if x != nil {
		return x.Lift
	}
	return nil
}

func (x *FieldOptions) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *FieldOptions) GetMaxDepth() uint32 {
	if x != nil && x.MaxDepth != nil {
		return *x.MaxDepth
	}
	return 0
}

func (x *FieldOptions) GetCardinality() Cardinality {
	if x != nil {
		return x.Cardinality
	}
	return Cardinality_CARDINALITY_UNSPECIFIED
}

func (x *FieldOptions) GetJoinSeparator() string {
	if x != nil {
		return x.JoinSeparator
	}
	return ""
}

func (x *FieldOptions) GetIndexSeparator() string {
	if x != nil {
		return x.IndexSeparator
	}
	return ""
}

func (x *FieldOptions) GetKeyFrom() KeyFrom {
	if x != nil {
		return x.KeyFrom
	}
	return KeyFrom_KEY_FROM_UNSPECIFIED
}

func (x *FieldOptions) GetKeyCase() KeyCase {
	if x != nil {
		return x.KeyCase
	}
	return KeyCase_KEY_CASE_UNSPECIFIED
}

func (x *FieldOptions) GetEmitEmpty() bool {
	if x != nil && x.EmitEmpty != nil {
		return *x.EmitEmpty
	}
	return false
}

func (x *FieldOptions) GetEnumFormat() EnumFormat {
	if x != nil {
		return x.EnumFormat
	}
	return EnumFormat_ENUM_FORMAT_UNSPECIFIED
}

func (x *FieldOptions) GetInt64Format() Int64Format {
	if x != nil {
		return x.Int64Format
	}
	return Int64Format_INT64_FORMAT_UNSPECIFIED
}

func (x *FieldOptions) GetBytesFormat() BytesFormat {
	if x != nil {
		return x.BytesFormat
	}
	return BytesFormat_BYTES_FORMAT_UNSPECIFIED
}

func (x *FieldOptions) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

func (x *FieldOptions) GetDurationFormat() DurationFormat {
	if x != nil {
		return x.DurationFormat
	}
	return DurationFormat_DURATION_FORMAT_UNSPECIFIED
}

// Enum-type-level options.
type EnumOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default representation for every field of this enum type. A field-level
	// enum_format still overrides it.
	Format EnumFormat `protobuf:"varint,1,opt,name=format,proto3,enum=plainjson.EnumFormat" json:"format,omitempty"`
	// Strip the SCREAMING_SNAKE type prefix from emitted value names.
	StripPrefix   bool `protobuf:"varint,2,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_plainjson_plainjson_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{8}
}

func (x *EnumOptions) GetFormat() EnumFormat {
	if x != nil {
		return x.Format
	}
	return EnumFormat_ENUM_FORMAT_UNSPECIFIED
}

func (x *EnumOptions) GetStripPrefix() bool {
	if x != nil {
		return x.StripPrefix
	}
	return false
}

// Enum-value-level options.
type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Emitted name for this value.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Emit nothing when a field holds this value.
	Omit          bool `protobuf:"varint,2,opt,name=omit,proto3" json:"omit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_plainjson_plainjson_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_plainjson_plainjson_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_plainjson_plainjson_proto_rawDescGZIP(), []int{9}
}

func (x *EnumValueOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumValueOptions) GetOmit() bool {
	if x != nil {
		return x.Omit
	}
	return false
}

var file_plainjson_plainjson_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         60040,
		Name:          "plainjson.file",
		Tag:           "bytes,60040,opt,name=file",
		Filename:      "plainjson/plainjson.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         60040,
		Name:          "plainjson.message",
		Tag:           "bytes,60040,opt,name=message",
		Filename:      "plainjson/plainjson.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         60040,
		Name:          "plainjson.field",
		Tag:           "bytes,60040,opt,name=field",
		Filename:      "plainjson/plainjson.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         60040,
		Name:          "plainjson.oneof",
		Tag:           "bytes,60040,opt,name=oneof",
		Filename:      "plainjson/plainjson.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         60040,
		Name:          "plainjson.enum",
		Tag:           "bytes,60040,opt,name=enum",
		Filename:      "plainjson/plainjson.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         60040,
		Name:          "plainjson.enum_value",
		Tag:           "bytes,60040,opt,name=enum_value",
		Filename:      "plainjson/plainjson.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional plainjson.FileOptions file = 60040;
	E_File = &file_plainjson_plainjson_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional plainjson.MessageOptions message = 60040;
	E_Message = &file_plainjson_plainjson_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional plainjson.FieldOptions field = 60040;
	E_Field = &file_plainjson_plainjson_proto_extTypes[2]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional plainjson.OneofOptions oneof = 60040;
	E_Oneof = &file_plainjson_plainjson_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional plainjson.EnumOptions enum = 60040;
	E_Enum = &file_plainjson_plainjson_proto_extTypes[4]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional plainjson.EnumValueOptions enum_value = 60040;
	E_EnumValue = &file_plainjson_plainjson_proto_extTypes[5]
)

var File_plainjson_plainjson_proto protoreflect.FileDescriptor

const file_plainjson_plainjson_proto_rawDesc = "" +
	"\n" +
	"\x19plainjson/plainjson.proto\x12\tplainjson\x1a google/protobuf/descriptor.proto\"*\n" +
	"\x04Lift\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02as\x18\x02 \x01(\tR\x02as\"\xc3\x04\n" +
	"\tMergeRule\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04from\x18\x02 \x03(\tR\x04from\x129\n" +
	"\von_conflict\x18\x03 \x01(\x0e2\x18.plainjson.MergeConflictR\n" +
	"onConflict\x12\"\n" +
	"\n" +
	"emit_empty\x18\x04 \x01(\bH\x00R\temitEmpty\x88\x01\x01\x12\x17\n" +
	"\araw_key\x18\x05 \x01(\bR\x06rawKey\x128\n" +
	"\vcardinality\x18\n" +
	" \x01(\x0e2\x16.plainjson.CardinalityR\vcardinality\x12%\n" +
	"\x0ejoin_separator\x18\v \x01(\tR\rjoinSeparator\x126\n" +
	"\venum_format\x18\x14 \x01(\x0e2\x15.plainjson.EnumFormatR\n" +
	"enumFormat\x129\n" +
	"\fint64_format\x18\x15 \x01(\x0e2\x16.plainjson.Int64FormatR\vint64Format\x129\n" +
	"\fbytes_format\x18\x16 \x01(\x0e2\x16.plainjson.BytesFormatR\vbytesFormat\x126\n" +
	"\vtime_format\x18\x17 \x01(\x0e2\x15.plainjson.TimeFormatR\n" +
	"timeFormat\x12B\n" +
	"\x0fduration_format\x18\x18 \x01(\x0e2\x19.plainjson.DurationFormatR\x0edurationFormatB\r\n" +
	"\v_emit_empty\"T\n" +
	"\bConstant\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\x12\x17\n" +
	"\araw_key\x18\x03 \x01(\bR\x06rawKey\"(\n" +
	"\x0eExclusiveGroup\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\"\x93\a\n" +
	"\vFileOptions\x12!\n" +
	"\fgenerate_all\x18\x01 \x01(\bR\vgenerateAll\x122\n" +
	"\x15override_marshal_json\x18\x02 \x01(\bR\x13overrideMarshalJson\x120\n" +
	"\aflatten\x18\n" +
	" \x01(\x0e2\x16.plainjson.FlattenModeR\aflatten\x12-\n" +
	"\bkey_from\x18\v \x01(\x0e2\x12.plainjson.KeyFromR\akeyFrom\x12-\n" +
	"\bkey_case\x18\f \x01(\x0e2\x12.plainjson.KeyCaseR\akeyCase\x12 \n" +
	"\tmax_depth\x18\r \x01(\rH\x00R\bmaxDepth\x88\x01\x01\x12\"\n" +
	"\n" +
	"emit_empty\x18\x0e \x01(\bH\x01R\temitEmpty\x88\x01\x01\x12E\n" +
	"\x10collision_policy\x18\x14 \x01(\x0e2\x1a.plainjson.CollisionPolicyR\x0fcollisionPolicy\x12?\n" +
	"\x0ecollision_wins\x18\x15 \x01(\x0e2\x18.plainjson.CollisionWinsR\rcollisionWins\x128\n" +
	"\vcardinality\x18\x1e \x01(\x0e2\x16.plainjson.CardinalityR\vcardinality\x12%\n" +
	"\x0ejoin_separator\x18\x1f \x01(\tR\rjoinSeparator\x12'\n" +
	"\x0findex_separator\x18  \x01(\tR\x0eindexSeparator\x126\n" +
	"\venum_format\x18( \x01(\x0e2\x15.plainjson.EnumFormatR\n" +
	"enumFormat\x129\n" +
	"\fint64_format\x18) \x01(\x0e2\x16.plainjson.Int64FormatR\vint64Format\x129\n" +
	"\fbytes_format\x18* \x01(\x0e2\x16.plainjson.BytesFormatR\vbytesFormat\x126\n" +
	"\vtime_format\x18+ \x01(\x0e2\x15.plainjson.TimeFormatR\n" +
	"timeFormat\x12B\n" +
	"\x0fduration_format\x18, \x01(\x0e2\x19.plainjson.DurationFormatR\x0edurationFormatB\f\n" +
	"\n" +
	"_max_depthB\r\n" +
	"\v_emit_empty\"\xe5\b\n" +
	"\x0eMessageOptions\x12\x1f\n" +
	"\bgenerate\x18\x01 \x01(\bH\x00R\bgenerate\x88\x01\x01\x127\n" +
	"\x15override_marshal_json\x18\x02 \x01(\bH\x01R\x13overrideMarshalJson\x88\x01\x01\x120\n" +
	"\aflatten\x18\n" +
	" \x01(\x0e2\x16.plainjson.FlattenModeR\aflatten\x12-\n" +
	"\bkey_from\x18\v \x01(\x0e2\x12.plainjson.KeyFromR\akeyFrom\x12-\n" +
	"\bkey_case\x18\f \x01(\x0e2\x12.plainjson.KeyCaseR\akeyCase\x12 \n" +
	"\tmax_depth\x18\r \x01(\rH\x02R\bmaxDepth\x88\x01\x01\x12\"\n" +
	"\n" +
	"emit_empty\x18\x0e \x01(\bH\x03R\temitEmpty\x88\x01\x01\x12E\n" +
	"\x10collision_policy\x18\x14 \x01(\x0e2\x1a.plainjson.CollisionPolicyR\x0fcollisionPolicy\x12?\n" +
	"\x0ecollision_wins\x18\x15 \x01(\x0e2\x18.plainjson.CollisionWinsR\rcollisionWins\x128\n" +
	"\vcardinality\x18\x1e \x01(\x0e2\x16.plainjson.CardinalityR\vcardinality\x12%\n" +
	"\x0ejoin_separator\x18\x1f \x01(\tR\rjoinSeparator\x12'\n" +
	"\x0findex_separator\x18  \x01(\tR\x0eindexSeparator\x126\n" +
	"\venum_format\x18( \x01(\x0e2\x15.plainjson.EnumFormatR\n" +
	"enumFormat\x129\n" +
	"\fint64_format\x18) \x01(\x0e2\x16.plainjson.Int64FormatR\vint64Format\x129\n" +
	"\fbytes_format\x18* \x01(\x0e2\x16.plainjson.BytesFormatR\vbytesFormat\x126\n" +
	"\vtime_format\x18+ \x01(\x0e2\x15.plainjson.TimeFormatR\n" +
	"timeFormat\x12B\n" +
	"\x0fduration_format\x18, \x01(\x0e2\x19.plainjson.DurationFormatR\x0edurationFormat\x12*\n" +
	"\x05merge\x182 \x03(\v2\x14.plainjson.MergeRuleR\x05merge\x121\n" +
	"\tconstants\x183 \x03(\v2\x13.plainjson.ConstantR\tconstants\x12D\n" +
	"\x10exclusive_groups\x184 \x03(\v2\x19.plainjson.ExclusiveGroupR\x0fexclusiveGroupsB\v\n" +
	"\t_generateB\x18\n" +
	"\x16_override_marshal_jsonB\f\n" +
	"\n" +
	"_max_depthB\r\n" +
	"\v_emit_empty\"\xfb\x05\n" +
	"\fOneofOptions\x12(\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x14.plainjson.OneofModeR\x04mode\x12$\n" +
	"\rdiscriminator\x18\x02 \x01(\tR\rdiscriminator\x12\x1b\n" +
	"\tvalue_key\x18\x03 \x01(\tR\bvalueKey\x12'\n" +
	"\romit_if_unset\x18\x04 \x01(\bH\x00R\vomitIfUnset\x88\x01\x01\x12-\n" +
	"\bkey_from\x18\v \x01(\x0e2\x12.plainjson.KeyFromR\akeyFrom\x12-\n" +
	"\bkey_case\x18\f \x01(\x0e2\x12.plainjson.KeyCaseR\akeyCase\x12\"\n" +
	"\n" +
	"emit_empty\x18\x0e \x01(\bH\x01R\temitEmpty\x88\x01\x01\x128\n" +
	"\vcardinality\x18\x1e \x01(\x0e2\x16.plainjson.CardinalityR\vcardinality\x12%\n" +
	"\x0ejoin_separator\x18\x1f \x01(\tR\rjoinSeparator\x12'\n" +
	"\x0findex_separator\x18  \x01(\tR\x0eindexSeparator\x126\n" +
	"\venum_format\x18( \x01(\x0e2\x15.plainjson.EnumFormatR\n" +
	"enumFormat\x129\n" +
	"\fint64_format\x18) \x01(\x0e2\x16.plainjson.Int64FormatR\vint64Format\x129\n" +
	"\fbytes_format\x18* \x01(\x0e2\x16.plainjson.BytesFormatR\vbytesFormat\x126\n" +
	"\vtime_format\x18+ \x01(\x0e2\x15.plainjson.TimeFormatR\n" +
	"timeFormat\x12B\n" +
	"\x0fduration_format\x18, \x01(\x0e2\x19.plainjson.DurationFormatR\x0edurationFormatB\x10\n" +
	"\x0e_omit_if_unsetB\r\n" +
	"\v_emit_empty\"\xd8\x06\n" +
	"\fFieldOptions\x12\x12\n" +
	"\x04omit\x18\x01 \x01(\bR\x04omit\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06suffix\x18\x04 \x01(\tR\x06suffix\x120\n" +
	"\aflatten\x18\x05 \x01(\x0e2\x16.plainjson.FlattenModeR\aflatten\x12\x12\n" +
	"\x04pick\x18\x06 \x01(\tR\x04pick\x12#\n" +
	"\x04lift\x18\a \x03(\v2\x0f.plainjson.LiftR\x04lift\x12\x10\n" +
	"\x03tag\x18\b \x01(\tR\x03tag\x12 \n" +
	"\tmax_depth\x18\t \x01(\rH\x00R\bmaxDepth\x88\x01\x01\x128\n" +
	"\vcardinality\x18\x14 \x01(\x0e2\x16.plainjson.CardinalityR\vcardinality\x12%\n" +
	"\x0ejoin_separator\x18\x15 \x01(\tR\rjoinSeparator\x12'\n" +
	"\x0findex_separator\x18\x16 \x01(\tR\x0eindexSeparator\x12-\n" +
	"\bkey_from\x18\x1e \x01(\x0e2\x12.plainjson.KeyFromR\akeyFrom\x12-\n" +
	"\bkey_case\x18\x1f \x01(\x0e2\x12.plainjson.KeyCaseR\akeyCase\x12\"\n" +
	"\n" +
	"emit_empty\x18  \x01(\bH\x01R\temitEmpty\x88\x01\x01\x126\n" +
	"\venum_format\x18( \x01(\x0e2\x15.plainjson.EnumFormatR\n" +
	"enumFormat\x129\n" +
	"\fint64_format\x18) \x01(\x0e2\x16.plainjson.Int64FormatR\vint64Format\x129\n" +
	"\fbytes_format\x18* \x01(\x0e2\x16.plainjson.BytesFormatR\vbytesFormat\x126\n" +
	"\vtime_format\x18+ \x01(\x0e2\x15.plainjson.TimeFormatR\n" +
	"timeFormat\x12B\n" +
	"\x0fduration_format\x18, \x01(\x0e2\x19.plainjson.DurationFormatR\x0edurationFormatB\f\n" +
	"\n" +
	"_max_depthB\r\n" +
	"\v_emit_empty\"_\n" +
	"\vEnumOptions\x12-\n" +
	"\x06format\x18\x01 \x01(\x0e2\x15.plainjson.EnumFormatR\x06format\x12!\n" +
	"\fstrip_prefix\x18\x02 \x01(\bR\vstripPrefix\":\n" +
	"\x10EnumValueOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04omit\x18\x02 \x01(\bR\x04omit*s\n" +
	"\vFlattenMode\x12\x1c\n" +
	"\x18FLATTEN_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FLATTEN_MODE_DEEP\x10\x01\x12\x18\n" +
	"\x14FLATTEN_MODE_SHALLOW\x10\x02\x12\x15\n" +
	"\x11FLATTEN_MODE_NONE\x10\x03*I\n" +
	"\aKeyFrom\x12\x18\n" +
	"\x14KEY_FROM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rKEY_FROM_LEAF\x10\x01\x12\x11\n" +
	"\rKEY_FROM_PATH\x10\x02*b\n" +
	"\aKeyCase\x12\x18\n" +
	"\x14KEY_CASE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eKEY_CASE_CAMEL\x10\x01\x12\x12\n" +
	"\x0eKEY_CASE_SNAKE\x10\x02\x12\x15\n" +
	"\x11KEY_CASE_ORIGINAL\x10\x03*\x97\x02\n" +
	"\vCardinality\x12\x1b\n" +
	"\x17CARDINALITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CARDINALITY_KEEP\x10\x01\x12\x15\n" +
	"\x11CARDINALITY_FIRST\x10\x02\x12\x14\n" +
	"\x10CARDINALITY_LAST\x10\x03\x12\x15\n" +
	"\x11CARDINALITY_COUNT\x10\x04\x12\x14\n" +
	"\x10CARDINALITY_JOIN\x10\x05\x12\x17\n" +
	"\x13CARDINALITY_INDEXED\x10\x06\x12\x17\n" +
	"\x13CARDINALITY_EXPLODE\x10\a\x12\x14\n" +
	"\x10CARDINALITY_KEYS\x10\b\x12\x16\n" +
	"\x12CARDINALITY_VALUES\x10\t\x12\x1b\n" +
	"\x17CARDINALITY_INLINE_KEYS\x10\n" +
	"*\xc3\x01\n" +
	"\tOneofMode\x12\x1a\n" +
	"\x16ONEOF_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ONEOF_MODE_INLINE\x10\x01\x12\x19\n" +
	"\x15ONEOF_MODE_BRANCH_KEY\x10\x02\x12\x15\n" +
	"\x11ONEOF_MODE_TAGGED\x10\x03\x12\x19\n" +
	"\x15ONEOF_MODE_SINGLE_KEY\x10\x04\x12!\n" +
	"\x1dONEOF_MODE_DISCRIMINATOR_ONLY\x10\x05\x12\x13\n" +
	"\x0fONEOF_MODE_OMIT\x10\x06*\x99\x01\n" +
	"\x0fCollisionPolicy\x12 \n" +
	"\x1cCOLLISION_POLICY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17COLLISION_POLICY_IGNORE\x10\x01\x12#\n" +
	"\x1fCOLLISION_POLICY_ERROR_GENERATE\x10\x02\x12\"\n" +
	"\x1eCOLLISION_POLICY_ERROR_RUNTIME\x10\x03*b\n" +
	"\rCollisionWins\x12\x1e\n" +
	"\x1aCOLLISION_WINS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COLLISION_WINS_FIRST\x10\x01\x12\x17\n" +
	"\x13COLLISION_WINS_LAST\x10\x02*\x90\x01\n" +
	"\rMergeConflict\x12\x1e\n" +
	"\x1aMERGE_CONFLICT_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eMERGE_CONFLICT_FIRST_NON_EMPTY\x10\x01\x12!\n" +
	"\x1dMERGE_CONFLICT_LAST_NON_EMPTY\x10\x02\x12\x18\n" +
	"\x14MERGE_CONFLICT_ERROR\x10\x03*W\n" +
	"\n" +
	"EnumFormat\x12\x1b\n" +
	"\x17ENUM_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENUM_FORMAT_NAME\x10\x01\x12\x16\n" +
	"\x12ENUM_FORMAT_NUMBER\x10\x02*]\n" +
	"\vInt64Format\x12\x1c\n" +
	"\x18INT64_FORMAT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INT64_FORMAT_STRING\x10\x01\x12\x17\n" +
	"\x13INT64_FORMAT_NUMBER\x10\x02*\x8f\x01\n" +
	"\vBytesFormat\x12\x1c\n" +
	"\x18BYTES_FORMAT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13BYTES_FORMAT_BASE64\x10\x01\x12\x1b\n" +
	"\x17BYTES_FORMAT_BASE64_URL\x10\x02\x12\x14\n" +
	"\x10BYTES_FORMAT_HEX\x10\x03\x12\x16\n" +
	"\x12BYTES_FORMAT_ARRAY\x10\x04*\xb3\x01\n" +
	"\n" +
	"TimeFormat\x12\x1b\n" +
	"\x17TIME_FORMAT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TIME_FORMAT_RFC3339\x10\x01\x12\x1c\n" +
	"\x18TIME_FORMAT_UNIX_SECONDS\x10\x02\x12\x1a\n" +
	"\x16TIME_FORMAT_UNIX_MILLI\x10\x03\x12\x1a\n" +
	"\x16TIME_FORMAT_UNIX_MICRO\x10\x04\x12\x19\n" +
	"\x15TIME_FORMAT_UNIX_NANO\x10\x05*\xa4\x01\n" +
	"\x0eDurationFormat\x12\x1f\n" +
	"\x1bDURATION_FORMAT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DURATION_FORMAT_PROTOJSON\x10\x01\x12\x1b\n" +
	"\x17DURATION_FORMAT_SECONDS\x10\x02\x12\x1a\n" +
	"\x16DURATION_FORMAT_MILLIS\x10\x03\x12\x19\n" +
	"\x15DURATION_FORMAT_NANOS\x10\x04:J\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\x88\xd5\x03 \x01(\v2\x16.plainjson.FileOptionsR\x04file:V\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\x88\xd5\x03 \x01(\v2\x19.plainjson.MessageOptionsR\amessage:N\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\x88\xd5\x03 \x01(\v2\x17.plainjson.FieldOptionsR\x05field:N\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\x88\xd5\x03 \x01(\v2\x17.plainjson.OneofOptionsR\x05oneof:J\n" +
	"\x04enum\x12\x1c.google.protobuf.EnumOptions\x18\x88\xd5\x03 \x01(\v2\x16.plainjson.EnumOptionsR\x04enum:_\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18\x88\xd5\x03 \x01(\v2\x1b.plainjson.EnumValueOptionsR\tenumValueB7Z5github.com/gopherex/protoc-gen-go-plainjson/plainjsonb\x06proto3"

var (
	file_plainjson_plainjson_proto_rawDescOnce sync.Once
	file_plainjson_plainjson_proto_rawDescData []byte
)

func file_plainjson_plainjson_proto_rawDescGZIP() []byte {
	file_plainjson_plainjson_proto_rawDescOnce.Do(func() {
		file_plainjson_plainjson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plainjson_plainjson_proto_rawDesc), len(file_plainjson_plainjson_proto_rawDesc)))
	})
	return file_plainjson_plainjson_proto_rawDescData
}

var file_plainjson_plainjson_proto_enumTypes = make([]protoimpl.EnumInfo, 13)
var file_plainjson_plainjson_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plainjson_plainjson_proto_goTypes = []any{
	(FlattenMode)(0),                      // 0: plainjson.FlattenMode
	(KeyFrom)(0),                          // 1: plainjson.KeyFrom
	(KeyCase)(0),                          // 2: plainjson.KeyCase
	(Cardinality)(0),                      // 3: plainjson.Cardinality
	(OneofMode)(0),                        // 4: plainjson.OneofMode
	(CollisionPolicy)(0),                  // 5: plainjson.CollisionPolicy
	(CollisionWins)(0),                    // 6: plainjson.CollisionWins
	(MergeConflict)(0),                    // 7: plainjson.MergeConflict
	(EnumFormat)(0),                       // 8: plainjson.EnumFormat
	(Int64Format)(0),                      // 9: plainjson.Int64Format
	(BytesFormat)(0),                      // 10: plainjson.BytesFormat
	(TimeFormat)(0),                       // 11: plainjson.TimeFormat
	(DurationFormat)(0),                   // 12: plainjson.DurationFormat
	(*Lift)(nil),                          // 13: plainjson.Lift
	(*MergeRule)(nil),                     // 14: plainjson.MergeRule
	(*Constant)(nil),                      // 15: plainjson.Constant
	(*ExclusiveGroup)(nil),                // 16: plainjson.ExclusiveGroup
	(*FileOptions)(nil),                   // 17: plainjson.FileOptions
	(*MessageOptions)(nil),                // 18: plainjson.MessageOptions
	(*OneofOptions)(nil),                  // 19: plainjson.OneofOptions
	(*FieldOptions)(nil),                  // 20: plainjson.FieldOptions
	(*EnumOptions)(nil),                   // 21: plainjson.EnumOptions
	(*EnumValueOptions)(nil),              // 22: plainjson.EnumValueOptions
	(*descriptorpb.FileOptions)(nil),      // 23: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 24: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 25: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),     // 26: google.protobuf.OneofOptions
	(*descriptorpb.EnumOptions)(nil),      // 27: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 28: google.protobuf.EnumValueOptions
}
var file_plainjson_plainjson_proto_depIdxs = []int32{
	7,  // 0: plainjson.MergeRule.on_conflict:type_name -> plainjson.MergeConflict
	3,  // 1: plainjson.MergeRule.cardinality:type_name -> plainjson.Cardinality
	8,  // 2: plainjson.MergeRule.enum_format:type_name -> plainjson.EnumFormat
	9,  // 3: plainjson.MergeRule.int64_format:type_name -> plainjson.Int64Format
	10, // 4: plainjson.MergeRule.bytes_format:type_name -> plainjson.BytesFormat
	11, // 5: plainjson.MergeRule.time_format:type_name -> plainjson.TimeFormat
	12, // 6: plainjson.MergeRule.duration_format:type_name -> plainjson.DurationFormat
	0,  // 7: plainjson.FileOptions.flatten:type_name -> plainjson.FlattenMode
	1,  // 8: plainjson.FileOptions.key_from:type_name -> plainjson.KeyFrom
	2,  // 9: plainjson.FileOptions.key_case:type_name -> plainjson.KeyCase
	5,  // 10: plainjson.FileOptions.collision_policy:type_name -> plainjson.CollisionPolicy
	6,  // 11: plainjson.FileOptions.collision_wins:type_name -> plainjson.CollisionWins
	3,  // 12: plainjson.FileOptions.cardinality:type_name -> plainjson.Cardinality
	8,  // 13: plainjson.FileOptions.enum_format:type_name -> plainjson.EnumFormat
	9,  // 14: plainjson.FileOptions.int64_format:type_name -> plainjson.Int64Format
	10, // 15: plainjson.FileOptions.bytes_format:type_name -> plainjson.BytesFormat
	11, // 16: plainjson.FileOptions.time_format:type_name -> plainjson.TimeFormat
	12, // 17: plainjson.FileOptions.duration_format:type_name -> plainjson.DurationFormat
	0,  // 18: plainjson.MessageOptions.flatten:type_name -> plainjson.FlattenMode
	1,  // 19: plainjson.MessageOptions.key_from:type_name -> plainjson.KeyFrom
	2,  // 20: plainjson.MessageOptions.key_case:type_name -> plainjson.KeyCase
	5,  // 21: plainjson.MessageOptions.collision_policy:type_name -> plainjson.CollisionPolicy
	6,  // 22: plainjson.MessageOptions.collision_wins:type_name -> plainjson.CollisionWins
	3,  // 23: plainjson.MessageOptions.cardinality:type_name -> plainjson.Cardinality
	8,  // 24: plainjson.MessageOptions.enum_format:type_name -> plainjson.EnumFormat
	9,  // 25: plainjson.MessageOptions.int64_format:type_name -> plainjson.Int64Format
	10, // 26: plainjson.MessageOptions.bytes_format:type_name -> plainjson.BytesFormat
	11, // 27: plainjson.MessageOptions.time_format:type_name -> plainjson.TimeFormat
	12, // 28: plainjson.MessageOptions.duration_format:type_name -> plainjson.DurationFormat
	14, // 29: plainjson.MessageOptions.merge:type_name -> plainjson.MergeRule
	15, // 30: plainjson.MessageOptions.constants:type_name -> plainjson.Constant
	16, // 31: plainjson.MessageOptions.exclusive_groups:type_name -> plainjson.ExclusiveGroup
	4,  // 32: plainjson.OneofOptions.mode:type_name -> plainjson.OneofMode
	1,  // 33: plainjson.OneofOptions.key_from:type_name -> plainjson.KeyFrom
	2,  // 34: plainjson.OneofOptions.key_case:type_name -> plainjson.KeyCase
	3,  // 35: plainjson.OneofOptions.cardinality:type_name -> plainjson.Cardinality
	8,  // 36: plainjson.OneofOptions.enum_format:type_name -> plainjson.EnumFormat
	9,  // 37: plainjson.OneofOptions.int64_format:type_name -> plainjson.Int64Format
	10, // 38: plainjson.OneofOptions.bytes_format:type_name -> plainjson.BytesFormat
	11, // 39: plainjson.OneofOptions.time_format:type_name -> plainjson.TimeFormat
	12, // 40: plainjson.OneofOptions.duration_format:type_name -> plainjson.DurationFormat
	0,  // 41: plainjson.FieldOptions.flatten:type_name -> plainjson.FlattenMode
	13, // 42: plainjson.FieldOptions.lift:type_name -> plainjson.Lift
	3,  // 43: plainjson.FieldOptions.cardinality:type_name -> plainjson.Cardinality
	1,  // 44: plainjson.FieldOptions.key_from:type_name -> plainjson.KeyFrom
	2,  // 45: plainjson.FieldOptions.key_case:type_name -> plainjson.KeyCase
	8,  // 46: plainjson.FieldOptions.enum_format:type_name -> plainjson.EnumFormat
	9,  // 47: plainjson.FieldOptions.int64_format:type_name -> plainjson.Int64Format
	10, // 48: plainjson.FieldOptions.bytes_format:type_name -> plainjson.BytesFormat
	11, // 49: plainjson.FieldOptions.time_format:type_name -> plainjson.TimeFormat
	12, // 50: plainjson.FieldOptions.duration_format:type_name -> plainjson.DurationFormat
	8,  // 51: plainjson.EnumOptions.format:type_name -> plainjson.EnumFormat
	23, // 52: plainjson.file:extendee -> google.protobuf.FileOptions
	24, // 53: plainjson.message:extendee -> google.protobuf.MessageOptions
	25, // 54: plainjson.field:extendee -> google.protobuf.FieldOptions
	26, // 55: plainjson.oneof:extendee -> google.protobuf.OneofOptions
	27, // 56: plainjson.enum:extendee -> google.protobuf.EnumOptions
	28, // 57: plainjson.enum_value:extendee -> google.protobuf.EnumValueOptions
	17, // 58: plainjson.file:type_name -> plainjson.FileOptions
	18, // 59: plainjson.message:type_name -> plainjson.MessageOptions
	20, // 60: plainjson.field:type_name -> plainjson.FieldOptions
	19, // 61: plainjson.oneof:type_name -> plainjson.OneofOptions
	21, // 62: plainjson.enum:type_name -> plainjson.EnumOptions
	22, // 63: plainjson.enum_value:type_name -> plainjson.EnumValueOptions
	64, // [64:64] is the sub-list for method output_type
	64, // [64:64] is the sub-list for method input_type
	58, // [58:64] is the sub-list for extension type_name
	52, // [52:58] is the sub-list for extension extendee
	0,  // [0:52] is the sub-list for field type_name
}

func init() { file_plainjson_plainjson_proto_init() }
func file_plainjson_plainjson_proto_init() {
	if File_plainjson_plainjson_proto != nil {
		return
	}
	file_plainjson_plainjson_proto_msgTypes[1].OneofWrappers = []any{}
	file_plainjson_plainjson_proto_msgTypes[4].OneofWrappers = []any{}
	file_plainjson_plainjson_proto_msgTypes[5].OneofWrappers = []any{}
	file_plainjson_plainjson_proto_msgTypes[6].OneofWrappers = []any{}
	file_plainjson_plainjson_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plainjson_plainjson_proto_rawDesc), len(file_plainjson_plainjson_proto_rawDesc)),
			NumEnums:      13,
			NumMessages:   10,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_plainjson_plainjson_proto_goTypes,
		DependencyIndexes: file_plainjson_plainjson_proto_depIdxs,
		EnumInfos:         file_plainjson_plainjson_proto_enumTypes,
		MessageInfos:      file_plainjson_plainjson_proto_msgTypes,
		ExtensionInfos:    file_plainjson_plainjson_proto_extTypes,
	}.Build()
	File_plainjson_plainjson_proto = out.File
	file_plainjson_plainjson_proto_goTypes = nil
	file_plainjson_plainjson_proto_depIdxs = nil
}
