// Package generator turns protobuf descriptors annotated with plainjson
// options into one-way JSON marshalers.
//
// Generation happens in three passes: options resolve along
// file -> message -> oneof -> field; the message tree is flattened into an
// ordered plan of writes; the plan is emitted as direct jx calls. Nothing is
// resolved at run time, and nothing reflects over descriptors.
package generator

import (
	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateFile emits <prefix>.pb.plainjson.go next to the .pb.go for one proto
// file. Files whose messages are all opted out produce nothing.
func GenerateFile(plugin *protogen.Plugin, file *protogen.File) error {
	msgs := generatedMessages(file.Messages)
	if len(msgs) == 0 {
		return nil
	}

	g := plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".pb.plainjson.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-plainjson. DO NOT EDIT.")
	g.P("//")
	g.P("// The marshalers below are one-way: they flatten a message into JSON and")
	g.P("// cannot read it back.")
	g.P("//")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	em := &emitter{
		g:     g,
		names: map[string]string{},
		enums: map[string]string{},
	}
	em.declareEnums(msgs)
	for _, msg := range msgs {
		if err := em.emitMethods(msg); err != nil {
			return err
		}
	}
	return em.flush()
}

// generatedMessages returns every message in the file the plugin generates
// for, including nested ones. Map entries are synthetic and never generated.
func generatedMessages(msgs []*protogen.Message) []*protogen.Message {
	var out []*protogen.Message
	for _, m := range msgs {
		if m.Desc.IsMapEntry() {
			continue
		}
		if generates(m) {
			out = append(out, m)
		}
		out = append(out, generatedMessages(m.Messages)...)
	}
	return out
}
