// Code generated by protoc-gen-go-plainjson. DO NOT EDIT.
//
// The marshalers below are one-way: they flatten a message into JSON and
// cannot read it back.
//
// source: example/spec/scalars/scalars.proto

package scalars

import (
	jx "github.com/go-faster/jx"
	plainjsonpb "github.com/gopherex/protoc-gen-go-plainjson/plainjsonpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	strings "strings"
)

// plainjsonEnumName_Severity renders spec.scalars.Severity the way its options ask for.
func plainjsonEnumName_Severity(v Severity) string {
	switch v {
	case Severity_SEVERITY_UNSPECIFIED:
		return "SEVERITY_UNSPECIFIED"
	case Severity_SEVERITY_LOW:
		return "SEVERITY_LOW"
	case Severity_SEVERITY_HIGH:
		return "SEVERITY_HIGH"
	}
	return v.String()
}

// plainjsonEnumName_Stripped renders spec.scalars.Stripped the way its options ask for.
func plainjsonEnumName_Stripped(v Stripped) string {
	switch v {
	case Stripped_STRIPPED_UNSPECIFIED:
		return "UNSPECIFIED"
	case Stripped_STRIPPED_LOW:
		return "LOW"
	case Stripped_STRIPPED_HIGH:
		return "HIGH"
	}
	return v.String()
}

// plainjsonEnumName_Numeric renders spec.scalars.Numeric the way its options ask for.
func plainjsonEnumName_Numeric(v Numeric) string {
	switch v {
	case Numeric_NUMERIC_UNSPECIFIED:
		return "NUMERIC_UNSPECIFIED"
	case Numeric_NUMERIC_ONE:
		return "NUMERIC_ONE"
	}
	return v.String()
}

// plainjsonEnumName_Renamed renders spec.scalars.Renamed the way its options ask for.
func plainjsonEnumName_Renamed(v Renamed) string {
	switch v {
	case Renamed_RENAMED_UNSPECIFIED:
		return "RENAMED_UNSPECIFIED"
	case Renamed_RENAMED_LOW:
		return "low"
	case Renamed_RENAMED_HIGH:
		return "high"
	case Renamed_RENAMED_HIDDEN:
		return "RENAMED_HIDDEN"
	}
	return v.String()
}

// plainjsonEnumOmit_Renamed reports values of spec.scalars.Renamed that are not emitted.
func plainjsonEnumOmit_Renamed(v Renamed) bool {
	switch v {
	case Renamed_RENAMED_HIDDEN:
		return true
	}
	return false
}

// plainjsonEnumName_NullValue renders google.protobuf.NullValue the way its options ask for.
func plainjsonEnumName_NullValue(v structpb.NullValue) string {
	switch v {
	case structpb.NullValue_NULL_VALUE:
		return "NULL_VALUE"
	}
	return v.String()
}

// EncodePlainJSON writes the flattened form of Baseline into e.
func (m *Baseline) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_Baseline(m, e)
}

// MarshalPlainJSON returns the flattened form of Baseline.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *Baseline) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_Baseline(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of SpecialFloats into e.
func (m *SpecialFloats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_SpecialFloats(m, e)
}

// MarshalPlainJSON returns the flattened form of SpecialFloats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *SpecialFloats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_SpecialFloats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of Int64AsNumber into e.
func (m *Int64AsNumber) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_Int64AsNumber(m, e)
}

// MarshalPlainJSON returns the flattened form of Int64AsNumber.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *Int64AsNumber) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_Int64AsNumber(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of Int64Mixed into e.
func (m *Int64Mixed) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_Int64Mixed(m, e)
}

// MarshalPlainJSON returns the flattened form of Int64Mixed.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *Int64Mixed) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_Int64Mixed(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of BytesFormats into e.
func (m *BytesFormats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_BytesFormats(m, e)
}

// MarshalPlainJSON returns the flattened form of BytesFormats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *BytesFormats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_BytesFormats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of EnumFormats into e.
func (m *EnumFormats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_EnumFormats(m, e)
}

// MarshalPlainJSON returns the flattened form of EnumFormats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *EnumFormats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_EnumFormats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of EnumFieldOverridesType into e.
func (m *EnumFieldOverridesType) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_EnumFieldOverridesType(m, e)
}

// MarshalPlainJSON returns the flattened form of EnumFieldOverridesType.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *EnumFieldOverridesType) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_EnumFieldOverridesType(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of WellKnown into e.
func (m *WellKnown) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_WellKnown(m, e)
}

// MarshalPlainJSON returns the flattened form of WellKnown.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *WellKnown) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_WellKnown(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of TimeFormats into e.
func (m *TimeFormats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_TimeFormats(m, e)
}

// MarshalPlainJSON returns the flattened form of TimeFormats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *TimeFormats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_TimeFormats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of DurationFormats into e.
func (m *DurationFormats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_DurationFormats(m, e)
}

// MarshalPlainJSON returns the flattened form of DurationFormats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *DurationFormats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_DurationFormats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of FormatsPropagate into e.
func (m *FormatsPropagate) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_FormatsPropagate(m, e)
}

// MarshalPlainJSON returns the flattened form of FormatsPropagate.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *FormatsPropagate) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_FormatsPropagate(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of ExplicitProtojsonDefaults into e.
func (m *ExplicitProtojsonDefaults) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_ExplicitProtojsonDefaults(m, e)
}

// MarshalPlainJSON returns the flattened form of ExplicitProtojsonDefaults.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *ExplicitProtojsonDefaults) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_ExplicitProtojsonDefaults(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of MessageLevelTimeFormats into e.
func (m *MessageLevelTimeFormats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_MessageLevelTimeFormats(m, e)
}

// MarshalPlainJSON returns the flattened form of MessageLevelTimeFormats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *MessageLevelTimeFormats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_MessageLevelTimeFormats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of MessageLevelEnumBytesJoin into e.
func (m *MessageLevelEnumBytesJoin) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_MessageLevelEnumBytesJoin(m, e)
}

// MarshalPlainJSON returns the flattened form of MessageLevelEnumBytesJoin.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *MessageLevelEnumBytesJoin) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_MessageLevelEnumBytesJoin(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// encodePlainJSON_Baseline writes spec.scalars.Baseline as a flat JSON object.
func encodePlainJSON_Baseline(m *Baseline, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// i32 <- i32
	if v := m.GetI32(); v != 0 {
		e.FieldStart("i32")
		e.Int32(v)
	}
	// u32 <- u32
	if v := m.GetU32(); v != 0 {
		e.FieldStart("u32")
		e.UInt32(v)
	}
	// i64 <- i64
	if v := m.GetI64(); v != 0 {
		e.FieldStart("i64")
		plainjsonpb.Int64(e, v, false)
	}
	// u64 <- u64
	if v := m.GetU64(); v != 0 {
		e.FieldStart("u64")
		plainjsonpb.UInt64(e, v, false)
	}
	// f32 <- f32
	if v := m.GetF32(); v != 0 {
		e.FieldStart("f32")
		plainjsonpb.Float32(e, v)
	}
	// f64 <- f64
	if v := m.GetF64(); v != 0 {
		e.FieldStart("f64")
		plainjsonpb.Float64(e, v)
	}
	// b <- b
	if v := m.GetB(); v {
		e.FieldStart("b")
		e.Bool(v)
	}
	// s <- s
	if v := m.GetS(); v != "" {
		e.FieldStart("s")
		e.Str(v)
	}
	// by <- by
	if v := m.GetBy(); len(v) > 0 {
		e.FieldStart("by")
		plainjsonpb.Bytes(e, v, 1)
	}
	// sev <- sev
	if v := m.GetSev(); v != 0 {
		e.FieldStart("sev")
		e.Str(plainjsonEnumName_Severity(v))
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_SpecialFloats writes spec.scalars.SpecialFloats as a flat JSON object.
func encodePlainJSON_SpecialFloats(m *SpecialFloats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// nan <- nan
	e.FieldStart("nan")
	plainjsonpb.Float64(e, m.GetNan())
	// inf <- inf
	e.FieldStart("inf")
	plainjsonpb.Float64(e, m.GetInf())
	// ninf <- ninf
	e.FieldStart("ninf")
	plainjsonpb.Float64(e, m.GetNinf())
	// negzero <- negzero
	e.FieldStart("negzero")
	plainjsonpb.Float64(e, m.GetNegzero())
	e.ObjEnd()
	return nil
}

// encodePlainJSON_Int64AsNumber writes spec.scalars.Int64AsNumber as a flat JSON object.
func encodePlainJSON_Int64AsNumber(m *Int64AsNumber, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// i64 <- i64
	if v := m.GetI64(); v != 0 {
		e.FieldStart("i64")
		plainjsonpb.Int64(e, v, true)
	}
	// u64 <- u64
	if v := m.GetU64(); v != 0 {
		e.FieldStart("u64")
		plainjsonpb.UInt64(e, v, true)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_Int64Mixed writes spec.scalars.Int64Mixed as a flat JSON object.
func encodePlainJSON_Int64Mixed(m *Int64Mixed, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// asString <- as_string
	if v := m.GetAsString(); v != 0 {
		e.FieldStart("asString")
		plainjsonpb.Int64(e, v, false)
	}
	// asNumber <- as_number
	if v := m.GetAsNumber(); v != 0 {
		e.FieldStart("asNumber")
		plainjsonpb.Int64(e, v, true)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_BytesFormats writes spec.scalars.BytesFormats as a flat JSON object.
func encodePlainJSON_BytesFormats(m *BytesFormats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// b64 <- b64
	if v := m.GetB64(); len(v) > 0 {
		e.FieldStart("b64")
		plainjsonpb.Bytes(e, v, 1)
	}
	// b64url <- b64url
	if v := m.GetB64Url(); len(v) > 0 {
		e.FieldStart("b64url")
		plainjsonpb.Bytes(e, v, 2)
	}
	// hex <- hex
	if v := m.GetHex(); len(v) > 0 {
		e.FieldStart("hex")
		plainjsonpb.Bytes(e, v, 3)
	}
	// arr <- arr
	if v := m.GetArr(); len(v) > 0 {
		e.FieldStart("arr")
		plainjsonpb.Bytes(e, v, 4)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_EnumFormats writes spec.scalars.EnumFormats as a flat JSON object.
func encodePlainJSON_EnumFormats(m *EnumFormats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// name <- name
	if v := m.GetName(); v != 0 {
		e.FieldStart("name")
		e.Str(plainjsonEnumName_Severity(v))
	}
	// number <- number
	if v := m.GetNumber(); v != 0 {
		e.FieldStart("number")
		e.Int32(int32(v))
	}
	// stripped <- stripped
	if v := m.GetStripped(); v != 0 {
		e.FieldStart("stripped")
		e.Str(plainjsonEnumName_Stripped(v))
	}
	// enumLevel <- enum_level
	if v := m.GetEnumLevel(); v != 0 {
		e.FieldStart("enumLevel")
		e.Int32(int32(v))
	}
	// renamed <- renamed
	if v := m.GetRenamed(); !plainjsonEnumOmit_Renamed(v) {
		if v != 0 {
			e.FieldStart("renamed")
			e.Str(plainjsonEnumName_Renamed(v))
		}
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_EnumFieldOverridesType writes spec.scalars.EnumFieldOverridesType as a flat JSON object.
func encodePlainJSON_EnumFieldOverridesType(m *EnumFieldOverridesType, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// forcedName <- forced_name
	if v := m.GetForcedName(); v != 0 {
		e.FieldStart("forcedName")
		e.Str(plainjsonEnumName_Numeric(v))
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_WellKnown writes spec.scalars.WellKnown as a flat JSON object.
func encodePlainJSON_WellKnown(m *WellKnown, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// ts <- ts
	if v := m.GetTs(); v != nil {
		e.FieldStart("ts")
		plainjsonpb.Timestamp(e, v, 1)
	}
	// dur <- dur
	if v := m.GetDur(); v != nil {
		e.FieldStart("dur")
		plainjsonpb.Duration(e, v, 1)
	}
	// sv <- sv
	if v := m.GetSv(); v != nil {
		e.FieldStart("sv")
		e.Str(v.GetValue())
	}
	// iv <- iv
	if v := m.GetIv(); v != nil {
		e.FieldStart("iv")
		e.Int32(v.GetValue())
	}
	// bv <- bv
	if v := m.GetBv(); v != nil {
		e.FieldStart("bv")
		e.Bool(v.GetValue())
	}
	// st <- st
	if v := m.GetSt(); v != nil {
		e.FieldStart("st")
		plainjsonpb.Struct(e, v)
	}
	// val <- val
	if v := m.GetVal(); v != nil {
		e.FieldStart("val")
		plainjsonpb.Value(e, v)
	}
	// lst <- lst
	if v := m.GetLst(); v != nil {
		e.FieldStart("lst")
		plainjsonpb.ListValue(e, v)
	}
	// emp <- emp
	if v := m.GetEmp(); v != nil {
		e.FieldStart("emp")
		e.ObjStart()
		e.ObjEnd()
	}
	// fm <- fm
	if v := m.GetFm(); v != nil {
		e.FieldStart("fm")
		plainjsonpb.FieldMask(e, v, 0)
	}
	// any <- any
	if v := m.GetAny(); v != nil {
		e.FieldStart("any")
		if err := plainjsonpb.Any(e, v); err != nil {
			return err
		}
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_TimeFormats writes spec.scalars.TimeFormats as a flat JSON object.
func encodePlainJSON_TimeFormats(m *TimeFormats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// rfc <- rfc
	if v := m.GetRfc(); v != nil {
		e.FieldStart("rfc")
		plainjsonpb.Timestamp(e, v, 1)
	}
	// secs <- secs
	if v := m.GetSecs(); v != nil {
		e.FieldStart("secs")
		plainjsonpb.Timestamp(e, v, 2)
	}
	// millis <- millis
	if v := m.GetMillis(); v != nil {
		e.FieldStart("millis")
		plainjsonpb.Timestamp(e, v, 3)
	}
	// micros <- micros
	if v := m.GetMicros(); v != nil {
		e.FieldStart("micros")
		plainjsonpb.Timestamp(e, v, 4)
	}
	// nanos <- nanos
	if v := m.GetNanos(); v != nil {
		e.FieldStart("nanos")
		plainjsonpb.Timestamp(e, v, 5)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_DurationFormats writes spec.scalars.DurationFormats as a flat JSON object.
func encodePlainJSON_DurationFormats(m *DurationFormats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// pj <- pj
	if v := m.GetPj(); v != nil {
		e.FieldStart("pj")
		plainjsonpb.Duration(e, v, 1)
	}
	// secs <- secs
	if v := m.GetSecs(); v != nil {
		e.FieldStart("secs")
		plainjsonpb.Duration(e, v, 2)
	}
	// millis <- millis
	if v := m.GetMillis(); v != nil {
		e.FieldStart("millis")
		plainjsonpb.Duration(e, v, 3)
	}
	// nanos <- nanos
	if v := m.GetNanos(); v != nil {
		e.FieldStart("nanos")
		plainjsonpb.Duration(e, v, 4)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_FormatsPropagate writes spec.scalars.FormatsPropagate as a flat JSON object.
func encodePlainJSON_FormatsPropagate(m *FormatsPropagate, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// ts <- inner.ts
	if v := m.GetInner().GetTs(); v != nil {
		e.FieldStart("ts")
		plainjsonpb.Timestamp(e, v, 3)
	}
	// n <- inner.n
	if v := m.GetInner().GetN(); v != 0 {
		e.FieldStart("n")
		plainjsonpb.Int64(e, v, true)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_ExplicitProtojsonDefaults writes spec.scalars.ExplicitProtojsonDefaults as a flat JSON object.
func encodePlainJSON_ExplicitProtojsonDefaults(m *ExplicitProtojsonDefaults, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// by <- by
	if v := m.GetBy(); len(v) > 0 {
		e.FieldStart("by")
		plainjsonpb.Bytes(e, v, 1)
	}
	// ts <- ts
	if v := m.GetTs(); v != nil {
		e.FieldStart("ts")
		plainjsonpb.Timestamp(e, v, 1)
	}
	// dur <- dur
	if v := m.GetDur(); v != nil {
		e.FieldStart("dur")
		plainjsonpb.Duration(e, v, 1)
	}
	// sev <- sev
	if v := m.GetSev(); v != 0 {
		e.FieldStart("sev")
		e.Str(plainjsonEnumName_Severity(v))
	}
	// argv <- argv
	if len(m.GetArgv()) > 0 {
		e.FieldStart("argv")
		e.ArrStart()
		for _, item := range m.GetArgv() {
			e.Str(item)
		}
		e.ArrEnd()
	}
	// pid <- pid
	if v := m.GetPid(); v != 0 {
		e.FieldStart("pid")
		plainjsonpb.Int64(e, v, false)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_MessageLevelTimeFormats writes spec.scalars.MessageLevelTimeFormats as a flat JSON object.
func encodePlainJSON_MessageLevelTimeFormats(m *MessageLevelTimeFormats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// a <- a
	if v := m.GetA(); v != nil {
		e.FieldStart("a")
		plainjsonpb.Timestamp(e, v, 3)
	}
	// b <- b
	if v := m.GetB(); v != nil {
		e.FieldStart("b")
		plainjsonpb.Timestamp(e, v, 3)
	}
	// took <- took
	if v := m.GetTook(); v != nil {
		e.FieldStart("took")
		plainjsonpb.Duration(e, v, 3)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_MessageLevelEnumBytesJoin writes spec.scalars.MessageLevelEnumBytesJoin as a flat JSON object.
func encodePlainJSON_MessageLevelEnumBytesJoin(m *MessageLevelEnumBytesJoin, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// sev <- sev
	if v := m.GetSev(); v != 0 {
		e.FieldStart("sev")
		e.Int32(int32(v))
	}
	// by <- by
	if v := m.GetBy(); len(v) > 0 {
		e.FieldStart("by")
		plainjsonpb.Bytes(e, v, 3)
	}
	// argv <- argv
	if len(m.GetArgv()) > 0 {
		e.FieldStart("argv")
		{
			var sb strings.Builder
			for i, item := range m.GetArgv() {
				if i > 0 {
					sb.WriteString("::")
				}
				sb.WriteString(item)
			}
			e.Str(sb.String())
		}
	}
	e.ObjEnd()
	return nil
}
