// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: example/spec/scalars/scalars.proto

package scalars

import (
	_ "github.com/gopherex/protoc-gen-go-plainjson/plainjson"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_HIGH        Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_HIGH",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_HIGH":        2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_example_spec_scalars_scalars_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_example_spec_scalars_scalars_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{0}
}

type Stripped int32

const (
	Stripped_STRIPPED_UNSPECIFIED Stripped = 0
	Stripped_STRIPPED_LOW         Stripped = 1
	Stripped_STRIPPED_HIGH        Stripped = 2
)

// Enum value maps for Stripped.
var (
	Stripped_name = map[int32]string{
		0: "STRIPPED_UNSPECIFIED",
		1: "STRIPPED_LOW",
		2: "STRIPPED_HIGH",
	}
	Stripped_value = map[string]int32{
		"STRIPPED_UNSPECIFIED": 0,
		"STRIPPED_LOW":         1,
		"STRIPPED_HIGH":        2,
	}
)

func (x Stripped) Enum() *Stripped {
	p := new(Stripped)
	*p = x
	return p
}

func (x Stripped) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stripped) Descriptor() protoreflect.EnumDescriptor {
	return file_example_spec_scalars_scalars_proto_enumTypes[1].Descriptor()
}

func (Stripped) Type() protoreflect.EnumType {
	return &file_example_spec_scalars_scalars_proto_enumTypes[1]
}

func (x Stripped) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stripped.Descriptor instead.
func (Stripped) EnumDescriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{1}
}

type Numeric int32

const (
	Numeric_NUMERIC_UNSPECIFIED Numeric = 0
	Numeric_NUMERIC_ONE         Numeric = 1
)

// Enum value maps for Numeric.
var (
	Numeric_name = map[int32]string{
		0: "NUMERIC_UNSPECIFIED",
		1: "NUMERIC_ONE",
	}
	Numeric_value = map[string]int32{
		"NUMERIC_UNSPECIFIED": 0,
		"NUMERIC_ONE":         1,
	}
)

func (x Numeric) Enum() *Numeric {
	p := new(Numeric)
	*p = x
	return p
}

func (x Numeric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Numeric) Descriptor() protoreflect.EnumDescriptor {
	return file_example_spec_scalars_scalars_proto_enumTypes[2].Descriptor()
}

func (Numeric) Type() protoreflect.EnumType {
	return &file_example_spec_scalars_scalars_proto_enumTypes[2]
}

func (x Numeric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Numeric.Descriptor instead.
func (Numeric) EnumDescriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{2}
}

type Renamed int32

const (
	Renamed_RENAMED_UNSPECIFIED Renamed = 0
	Renamed_RENAMED_LOW         Renamed = 1
	Renamed_RENAMED_HIGH        Renamed = 2
	Renamed_RENAMED_HIDDEN      Renamed = 3
)

// Enum value maps for Renamed.
var (
	Renamed_name = map[int32]string{
		0: "RENAMED_UNSPECIFIED",
		1: "RENAMED_LOW",
		2: "RENAMED_HIGH",
		3: "RENAMED_HIDDEN",
	}
	Renamed_value = map[string]int32{
		"RENAMED_UNSPECIFIED": 0,
		"RENAMED_LOW":         1,
		"RENAMED_HIGH":        2,
		"RENAMED_HIDDEN":      3,
	}
)

func (x Renamed) Enum() *Renamed {
	p := new(Renamed)
	*p = x
	return p
}

func (x Renamed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Renamed) Descriptor() protoreflect.EnumDescriptor {
	return file_example_spec_scalars_scalars_proto_enumTypes[3].Descriptor()
}

func (Renamed) Type() protoreflect.EnumType {
	return &file_example_spec_scalars_scalars_proto_enumTypes[3]
}

func (x Renamed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Renamed.Descriptor instead.
func (Renamed) EnumDescriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{3}
}

// protojson baseline, no overrides.
// {"i32":-1,"u32":2,"i64":"-3","u64":"4","f32":1.5,"f64":-0,"b":true,
//
//	"s":"hi","by":"AQID","sev":"SEVERITY_HIGH"}
type Baseline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I32           int32                  `protobuf:"varint,1,opt,name=i32,proto3" json:"i32,omitempty"`
	U32           uint32                 `protobuf:"varint,2,opt,name=u32,proto3" json:"u32,omitempty"`
	I64           int64                  `protobuf:"varint,3,opt,name=i64,proto3" json:"i64,omitempty"`
	U64           uint64                 `protobuf:"varint,4,opt,name=u64,proto3" json:"u64,omitempty"`
	F32           float32                `protobuf:"fixed32,5,opt,name=f32,proto3" json:"f32,omitempty"`
	F64           float64                `protobuf:"fixed64,6,opt,name=f64,proto3" json:"f64,omitempty"`
	B             bool                   `protobuf:"varint,7,opt,name=b,proto3" json:"b,omitempty"`
	S             string                 `protobuf:"bytes,8,opt,name=s,proto3" json:"s,omitempty"`
	By            []byte                 `protobuf:"bytes,9,opt,name=by,proto3" json:"by,omitempty"`
	Sev           Severity               `protobuf:"varint,10,opt,name=sev,proto3,enum=spec.scalars.Severity" json:"sev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Baseline) Reset() {
	*x = Baseline{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Baseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Baseline) ProtoMessage() {}

func (x *Baseline) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Baseline.ProtoReflect.Descriptor instead.
func (*Baseline) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{0}
}

func (x *Baseline) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *Baseline) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *Baseline) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Baseline) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *Baseline) GetF32() float32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *Baseline) GetF64() float64 {
	if x != nil {
		return x.F64
	}
	return 0
}

func (x *Baseline) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *Baseline) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Baseline) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *Baseline) GetSev() Severity {
	if x != nil {
		return x.Sev
	}
	return Severity_SEVERITY_UNSPECIFIED
}

// Special float values keep their protojson spelling.
// {"nan":"NaN","inf":"Infinity","ninf":"-Infinity","negzero":-0}
type SpecialFloats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nan           float64                `protobuf:"fixed64,1,opt,name=nan,proto3" json:"nan,omitempty"`
	Inf           float64                `protobuf:"fixed64,2,opt,name=inf,proto3" json:"inf,omitempty"`
	Ninf          float64                `protobuf:"fixed64,3,opt,name=ninf,proto3" json:"ninf,omitempty"`
	Negzero       float64                `protobuf:"fixed64,4,opt,name=negzero,proto3" json:"negzero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialFloats) Reset() {
	*x = SpecialFloats{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialFloats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialFloats) ProtoMessage() {}

func (x *SpecialFloats) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialFloats.ProtoReflect.Descriptor instead.
func (*SpecialFloats) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{1}
}

func (x *SpecialFloats) GetNan() float64 {
	if x != nil {
		return x.Nan
	}
	return 0
}

func (x *SpecialFloats) GetInf() float64 {
	if x != nil {
		return x.Inf
	}
	return 0
}

func (x *SpecialFloats) GetNinf() float64 {
	if x != nil {
		return x.Ninf
	}
	return 0
}

func (x *SpecialFloats) GetNegzero() float64 {
	if x != nil {
		return x.Negzero
	}
	return 0
}

// {"i64":-3,"u64":4}
type Int64AsNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I64           int64                  `protobuf:"varint,1,opt,name=i64,proto3" json:"i64,omitempty"`
	U64           uint64                 `protobuf:"varint,2,opt,name=u64,proto3" json:"u64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64AsNumber) Reset() {
	*x = Int64AsNumber{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64AsNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64AsNumber) ProtoMessage() {}

func (x *Int64AsNumber) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64AsNumber.ProtoReflect.Descriptor instead.
func (*Int64AsNumber) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{2}
}

func (x *Int64AsNumber) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Int64AsNumber) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

// Per-field override beats the message default.
// {"asString":"-3","asNumber":-3}
type Int64Mixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AsString      int64                  `protobuf:"varint,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	AsNumber      int64                  `protobuf:"varint,2,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int64Mixed) Reset() {
	*x = Int64Mixed{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int64Mixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Mixed) ProtoMessage() {}

func (x *Int64Mixed) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Mixed.ProtoReflect.Descriptor instead.
func (*Int64Mixed) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{3}
}

func (x *Int64Mixed) GetAsString() int64 {
	if x != nil {
		return x.AsString
	}
	return 0
}

func (x *Int64Mixed) GetAsNumber() int64 {
	if x != nil {
		return x.AsNumber
	}
	return 0
}

// {"b64":"AQID","b64url":"AQID","hex":"010203","arr":[1,2,3]}
type BytesFormats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B64           []byte                 `protobuf:"bytes,1,opt,name=b64,proto3" json:"b64,omitempty"`
	B64Url        []byte                 `protobuf:"bytes,2,opt,name=b64url,proto3" json:"b64url,omitempty"`
	Hex           []byte                 `protobuf:"bytes,3,opt,name=hex,proto3" json:"hex,omitempty"`
	Arr           []byte                 `protobuf:"bytes,4,opt,name=arr,proto3" json:"arr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesFormats) Reset() {
	*x = BytesFormats{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesFormats) ProtoMessage() {}

func (x *BytesFormats) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesFormats.ProtoReflect.Descriptor instead.
func (*BytesFormats) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{4}
}

func (x *BytesFormats) GetB64() []byte {
	if x != nil {
		return x.B64
	}
	return nil
}

func (x *BytesFormats) GetB64Url() []byte {
	if x != nil {
		return x.B64Url
	}
	return nil
}

func (x *BytesFormats) GetHex() []byte {
	if x != nil {
		return x.Hex
	}
	return nil
}

func (x *BytesFormats) GetArr() []byte {
	if x != nil {
		return x.Arr
	}
	return nil
}

// {"name":"SEVERITY_HIGH","number":2,"stripped":"HIGH","enumLevel":1,
//
//	"renamed":"high"}
type EnumFormats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          Severity               `protobuf:"varint,1,opt,name=name,proto3,enum=spec.scalars.Severity" json:"name,omitempty"`
	Number        Severity               `protobuf:"varint,2,opt,name=number,proto3,enum=spec.scalars.Severity" json:"number,omitempty"`
	Stripped      Stripped               `protobuf:"varint,3,opt,name=stripped,proto3,enum=spec.scalars.Stripped" json:"stripped,omitempty"`
	EnumLevel     Numeric                `protobuf:"varint,4,opt,name=enum_level,json=enumLevel,proto3,enum=spec.scalars.Numeric" json:"enum_level,omitempty"`
	Renamed       Renamed                `protobuf:"varint,5,opt,name=renamed,proto3,enum=spec.scalars.Renamed" json:"renamed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumFormats) Reset() {
	*x = EnumFormats{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumFormats) ProtoMessage() {}

func (x *EnumFormats) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumFormats.ProtoReflect.Descriptor instead.
func (*EnumFormats) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{5}
}

func (x *EnumFormats) GetName() Severity {
	if x != nil {
		return x.Name
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *EnumFormats) GetNumber() Severity {
	if x != nil {
		return x.Number
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *EnumFormats) GetStripped() Stripped {
	if x != nil {
		return x.Stripped
	}
	return Stripped_STRIPPED_UNSPECIFIED
}

func (x *EnumFormats) GetEnumLevel() Numeric {
	if x != nil {
		return x.EnumLevel
	}
	return Numeric_NUMERIC_UNSPECIFIED
}

func (x *EnumFormats) GetRenamed() Renamed {
	if x != nil {
		return x.Renamed
	}
	return Renamed_RENAMED_UNSPECIFIED
}

// A field-level format overrides the enum-level one.
// {"forcedName":"NUMERIC_ONE"}
type EnumFieldOverridesType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForcedName    Numeric                `protobuf:"varint,1,opt,name=forced_name,json=forcedName,proto3,enum=spec.scalars.Numeric" json:"forced_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumFieldOverridesType) Reset() {
	*x = EnumFieldOverridesType{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumFieldOverridesType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumFieldOverridesType) ProtoMessage() {}

func (x *EnumFieldOverridesType) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumFieldOverridesType.ProtoReflect.Descriptor instead.
func (*EnumFieldOverridesType) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{6}
}

func (x *EnumFieldOverridesType) GetForcedName() Numeric {
	if x != nil {
		return x.ForcedName
	}
	return Numeric_NUMERIC_UNSPECIFIED
}

// Well-known types are leaves: flatten never descends into them.
// {"ts":"2026-08-25T12:00:00Z","dur":"1.500s","sv":"x","iv":7,"bv":true,
//
//	"st":{"a":1},"val":"v","lst":[1,2],"emp":{},"fm":"aB,c","any":{"@type":"…"}}
type WellKnown struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Dur           *durationpb.Duration    `protobuf:"bytes,2,opt,name=dur,proto3" json:"dur,omitempty"`
	Sv            *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=sv,proto3" json:"sv,omitempty"`
	Iv            *wrapperspb.Int32Value  `protobuf:"bytes,4,opt,name=iv,proto3" json:"iv,omitempty"`
	Bv            *wrapperspb.BoolValue   `protobuf:"bytes,5,opt,name=bv,proto3" json:"bv,omitempty"`
	St            *structpb.Struct        `protobuf:"bytes,6,opt,name=st,proto3" json:"st,omitempty"`
	Val           *structpb.Value         `protobuf:"bytes,7,opt,name=val,proto3" json:"val,omitempty"`
	Lst           *structpb.ListValue     `protobuf:"bytes,8,opt,name=lst,proto3" json:"lst,omitempty"`
	Emp           *emptypb.Empty          `protobuf:"bytes,9,opt,name=emp,proto3" json:"emp,omitempty"`
	Fm            *fieldmaskpb.FieldMask  `protobuf:"bytes,10,opt,name=fm,proto3" json:"fm,omitempty"`
	Any           *anypb.Any              `protobuf:"bytes,11,opt,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WellKnown) Reset() {
	*x = WellKnown{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WellKnown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WellKnown) ProtoMessage() {}

func (x *WellKnown) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WellKnown.ProtoReflect.Descriptor instead.
func (*WellKnown) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{7}
}

func (x *WellKnown) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WellKnown) GetDur() *durationpb.Duration {
	if x != nil {
		return x.Dur
	}
	return nil
}

func (x *WellKnown) GetSv() *wrapperspb.StringValue {
	if x != nil {
		return x.Sv
	}
	return nil
}

func (x *WellKnown) GetIv() *wrapperspb.Int32Value {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *WellKnown) GetBv() *wrapperspb.BoolValue {
	if x != nil {
		return x.Bv
	}
	return nil
}

func (x *WellKnown) GetSt() *structpb.Struct {
	if x != nil {
		return x.St
	}
	return nil
}

func (x *WellKnown) GetVal() *structpb.Value {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *WellKnown) GetLst() *structpb.ListValue {
	if x != nil {
		return x.Lst
	}
	return nil
}

func (x *WellKnown) GetEmp() *emptypb.Empty {
	if x != nil {
		return x.Emp
	}
	return nil
}

func (x *WellKnown) GetFm() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Fm
	}
	return nil
}

func (x *WellKnown) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

// {"rfc":"2026-08-25T12:00:00Z","secs":1787832000,"millis":1787832000000,
//
//	"micros":1787832000000000,"nanos":1787832000000000000}
type TimeFormats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rfc           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=rfc,proto3" json:"rfc,omitempty"`
	Secs          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=secs,proto3" json:"secs,omitempty"`
	Millis        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=millis,proto3" json:"millis,omitempty"`
	Micros        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=micros,proto3" json:"micros,omitempty"`
	Nanos         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeFormats) Reset() {
	*x = TimeFormats{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeFormats) ProtoMessage() {}

func (x *TimeFormats) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeFormats.ProtoReflect.Descriptor instead.
func (*TimeFormats) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{8}
}

func (x *TimeFormats) GetRfc() *timestamppb.Timestamp {
	if x != nil {
		return x.Rfc
	}
	return nil
}

func (x *TimeFormats) GetSecs() *timestamppb.Timestamp {
	if x != nil {
		return x.Secs
	}
	return nil
}

func (x *TimeFormats) GetMillis() *timestamppb.Timestamp {
	if x != nil {
		return x.Millis
	}
	return nil
}

func (x *TimeFormats) GetMicros() *timestamppb.Timestamp {
	if x != nil {
		return x.Micros
	}
	return nil
}

func (x *TimeFormats) GetNanos() *timestamppb.Timestamp {
	if x != nil {
		return x.Nanos
	}
	return nil
}

// {"pj":"1.500s","secs":1.5,"millis":1500,"nanos":1500000000}
type DurationFormats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pj            *durationpb.Duration   `protobuf:"bytes,1,opt,name=pj,proto3" json:"pj,omitempty"`
	Secs          *durationpb.Duration   `protobuf:"bytes,2,opt,name=secs,proto3" json:"secs,omitempty"`
	Millis        *durationpb.Duration   `protobuf:"bytes,3,opt,name=millis,proto3" json:"millis,omitempty"`
	Nanos         *durationpb.Duration   `protobuf:"bytes,4,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurationFormats) Reset() {
	*x = DurationFormats{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationFormats) ProtoMessage() {}

func (x *DurationFormats) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationFormats.ProtoReflect.Descriptor instead.
func (*DurationFormats) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{9}
}

func (x *DurationFormats) GetPj() *durationpb.Duration {
	if x != nil {
		return x.Pj
	}
	return nil
}

func (x *DurationFormats) GetSecs() *durationpb.Duration {
	if x != nil {
		return x.Secs
	}
	return nil
}

func (x *DurationFormats) GetMillis() *durationpb.Duration {
	if x != nil {
		return x.Millis
	}
	return nil
}

func (x *DurationFormats) GetNanos() *durationpb.Duration {
	if x != nil {
		return x.Nanos
	}
	return nil
}

// Formats propagate down a subtree, unlike flatten.
type Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	N             int64                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{10}
}

func (x *Inner) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Inner) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

// {"ts":1787832000000,"n":5}
type FormatsPropagate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *Inner                 `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatsPropagate) Reset() {
	*x = FormatsPropagate{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatsPropagate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatsPropagate) ProtoMessage() {}

func (x *FormatsPropagate) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatsPropagate.ProtoReflect.Descriptor instead.
func (*FormatsPropagate) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{11}
}

func (x *FormatsPropagate) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

// Message-level formats, and the explicit spelling of every protojson default:
// stating a default must not change the output.
// {"by":"AQID","ts":"2026-08-25T12:00:00Z","dur":"1.500s","sev":"SEVERITY_HIGH",
//
//	"argv":["a","b"],"pid":"7"}
type ExplicitProtojsonDefaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            []byte                 `protobuf:"bytes,1,opt,name=by,proto3" json:"by,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Dur           *durationpb.Duration   `protobuf:"bytes,3,opt,name=dur,proto3" json:"dur,omitempty"`
	Sev           Severity               `protobuf:"varint,4,opt,name=sev,proto3,enum=spec.scalars.Severity" json:"sev,omitempty"`
	Argv          []string               `protobuf:"bytes,5,rep,name=argv,proto3" json:"argv,omitempty"`
	Pid           int64                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplicitProtojsonDefaults) Reset() {
	*x = ExplicitProtojsonDefaults{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplicitProtojsonDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplicitProtojsonDefaults) ProtoMessage() {}

func (x *ExplicitProtojsonDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplicitProtojsonDefaults.ProtoReflect.Descriptor instead.
func (*ExplicitProtojsonDefaults) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{12}
}

func (x *ExplicitProtojsonDefaults) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *ExplicitProtojsonDefaults) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ExplicitProtojsonDefaults) GetDur() *durationpb.Duration {
	if x != nil {
		return x.Dur
	}
	return nil
}

func (x *ExplicitProtojsonDefaults) GetSev() Severity {
	if x != nil {
		return x.Sev
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ExplicitProtojsonDefaults) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExplicitProtojsonDefaults) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// Message-level time and duration formats, inherited by every field below.
// {"a":1787832000000,"b":1787832000000,"took":1500}
type MessageLevelTimeFormats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	Took          *durationpb.Duration   `protobuf:"bytes,3,opt,name=took,proto3" json:"took,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageLevelTimeFormats) Reset() {
	*x = MessageLevelTimeFormats{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageLevelTimeFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageLevelTimeFormats) ProtoMessage() {}

func (x *MessageLevelTimeFormats) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageLevelTimeFormats.ProtoReflect.Descriptor instead.
func (*MessageLevelTimeFormats) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{13}
}

func (x *MessageLevelTimeFormats) GetA() *timestamppb.Timestamp {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *MessageLevelTimeFormats) GetB() *timestamppb.Timestamp {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *MessageLevelTimeFormats) GetTook() *durationpb.Duration {
	if x != nil {
		return x.Took
	}
	return nil
}

// Message-level enum and bytes formats plus a join separator.
// {"sev":2,"by":"010203","argv":"a::b"}
type MessageLevelEnumBytesJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sev           Severity               `protobuf:"varint,1,opt,name=sev,proto3,enum=spec.scalars.Severity" json:"sev,omitempty"`
	By            []byte                 `protobuf:"bytes,2,opt,name=by,proto3" json:"by,omitempty"`
	Argv          []string               `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageLevelEnumBytesJoin) Reset() {
	*x = MessageLevelEnumBytesJoin{}
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageLevelEnumBytesJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageLevelEnumBytesJoin) ProtoMessage() {}

func (x *MessageLevelEnumBytesJoin) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_scalars_scalars_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageLevelEnumBytesJoin.ProtoReflect.Descriptor instead.
func (*MessageLevelEnumBytesJoin) Descriptor() ([]byte, []int) {
	return file_example_spec_scalars_scalars_proto_rawDescGZIP(), []int{14}
}

func (x *MessageLevelEnumBytesJoin) GetSev() Severity {
	if x != nil {
		return x.Sev
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *MessageLevelEnumBytesJoin) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *MessageLevelEnumBytesJoin) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

var File_example_spec_scalars_scalars_proto protoreflect.FileDescriptor

const file_example_spec_scalars_scalars_proto_rawDesc = "" +
	"\n" +
	"\"example/spec/scalars/scalars.proto\x12\fspec.scalars\x1a\x19plainjson/plainjson.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xd4\x01\n" +
	"\bBaseline\x12\x10\n" +
	"\x03i32\x18\x01 \x01(\x05R\x03i32\x12\x10\n" +
	"\x03u32\x18\x02 \x01(\rR\x03u32\x12\x10\n" +
	"\x03i64\x18\x03 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03u64\x18\x04 \x01(\x04R\x03u64\x12\x10\n" +
	"\x03f32\x18\x05 \x01(\x02R\x03f32\x12\x10\n" +
	"\x03f64\x18\x06 \x01(\x01R\x03f64\x12\f\n" +
	"\x01b\x18\a \x01(\bR\x01b\x12\f\n" +
	"\x01s\x18\b \x01(\tR\x01s\x12\x0e\n" +
	"\x02by\x18\t \x01(\fR\x02by\x12(\n" +
	"\x03sev\x18\n" +
	" \x01(\x0e2\x16.spec.scalars.SeverityR\x03sev:\x06¨\x1d\x02\b\x01\"k\n" +
	"\rSpecialFloats\x12\x10\n" +
	"\x03nan\x18\x01 \x01(\x01R\x03nan\x12\x10\n" +
	"\x03inf\x18\x02 \x01(\x01R\x03inf\x12\x12\n" +
	"\x04ninf\x18\x03 \x01(\x01R\x04ninf\x12\x18\n" +
	"\anegzero\x18\x04 \x01(\x01R\anegzero:\b¨\x1d\x04\b\x01p\x01\">\n" +
	"\rInt64AsNumber\x12\x10\n" +
	"\x03i64\x18\x01 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03u64\x18\x02 \x01(\x04R\x03u64:\t¨\x1d\x05\b\x01\xc8\x02\x02\"Z\n" +
	"\n" +
	"Int64Mixed\x12$\n" +
	"\tas_string\x18\x01 \x01(\x03B\a¨\x1d\x03\xc8\x02\x01R\basString\x12\x1b\n" +
	"\tas_number\x18\x02 \x01(\x03R\basNumber:\t¨\x1d\x05\b\x01\xc8\x02\x02\"\x7f\n" +
	"\fBytesFormats\x12\x10\n" +
	"\x03b64\x18\x01 \x01(\fR\x03b64\x12\x1f\n" +
	"\x06b64url\x18\x02 \x01(\fB\a¨\x1d\x03\xd0\x02\x02R\x06b64url\x12\x19\n" +
	"\x03hex\x18\x03 \x01(\fB\a¨\x1d\x03\xd0\x02\x03R\x03hex\x12\x19\n" +
	"\x03arr\x18\x04 \x01(\fB\a¨\x1d\x03\xd0\x02\x04R\x03arr:\x06¨\x1d\x02\b\x01\"\x95\x02\n" +
	"\vEnumFormats\x12*\n" +
	"\x04name\x18\x01 \x01(\x0e2\x16.spec.scalars.SeverityR\x04name\x127\n" +
	"\x06number\x18\x02 \x01(\x0e2\x16.spec.scalars.SeverityB\a¨\x1d\x03\xc0\x02\x02R\x06number\x122\n" +
	"\bstripped\x18\x03 \x01(\x0e2\x16.spec.scalars.StrippedR\bstripped\x124\n" +
	"\n" +
	"enum_level\x18\x04 \x01(\x0e2\x15.spec.scalars.NumericR\tenumLevel\x12/\n" +
	"\arenamed\x18\x05 \x01(\x0e2\x15.spec.scalars.RenamedR\arenamed:\x06¨\x1d\x02\b\x01\"a\n" +
	"\x16EnumFieldOverridesType\x12?\n" +
	"\vforced_name\x18\x01 \x01(\x0e2\x15.spec.scalars.NumericB\a¨\x1d\x03\xc0\x02\x01R\n" +
	"forcedName:\x06¨\x1d\x02\b\x01\"\xf2\x03\n" +
	"\tWellKnown\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12+\n" +
	"\x03dur\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03dur\x12,\n" +
	"\x02sv\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x02sv\x12+\n" +
	"\x02iv\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\x02iv\x12*\n" +
	"\x02bv\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\x02bv\x12'\n" +
	"\x02st\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x02st\x12(\n" +
	"\x03val\x18\a \x01(\v2\x16.google.protobuf.ValueR\x03val\x12,\n" +
	"\x03lst\x18\b \x01(\v2\x1a.google.protobuf.ListValueR\x03lst\x12(\n" +
	"\x03emp\x18\t \x01(\v2\x16.google.protobuf.EmptyR\x03emp\x12*\n" +
	"\x02fm\x18\n" +
	" \x01(\v2\x1a.google.protobuf.FieldMaskR\x02fm\x12&\n" +
	"\x03any\x18\v \x01(\v2\x14.google.protobuf.AnyR\x03any:\x06¨\x1d\x02\b\x01\"\xb1\x02\n" +
	"\vTimeFormats\x12,\n" +
	"\x03rfc\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03rfc\x127\n" +
	"\x04secs\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\a¨\x1d\x03\xd8\x02\x02R\x04secs\x12;\n" +
	"\x06millis\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\a¨\x1d\x03\xd8\x02\x03R\x06millis\x12;\n" +
	"\x06micros\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\a¨\x1d\x03\xd8\x02\x04R\x06micros\x129\n" +
	"\x05nanos\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\a¨\x1d\x03\xd8\x02\x05R\x05nanos:\x06¨\x1d\x02\b\x01\"\xf2\x01\n" +
	"\x0fDurationFormats\x12)\n" +
	"\x02pj\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x02pj\x126\n" +
	"\x04secs\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\a¨\x1d\x03\xe0\x02\x02R\x04secs\x12:\n" +
	"\x06millis\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\a¨\x1d\x03\xe0\x02\x03R\x06millis\x128\n" +
	"\x05nanos\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\a¨\x1d\x03\xe0\x02\x04R\x05nanos:\x06¨\x1d\x02\b\x01\"A\n" +
	"\x05Inner\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\f\n" +
	"\x01n\x18\x02 \x01(\x03R\x01n\"Q\n" +
	"\x10FormatsPropagate\x125\n" +
	"\x05inner\x18\x01 \x01(\v2\x13.spec.scalars.InnerB\n" +
	"¨\x1d\x06\xc8\x02\x02\xd8\x02\x03R\x05inner:\x06¨\x1d\x02\b\x01\"\xfa\x01\n" +
	"\x19ExplicitProtojsonDefaults\x12\x0e\n" +
	"\x02by\x18\x01 \x01(\fR\x02by\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12+\n" +
	"\x03dur\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03dur\x12(\n" +
	"\x03sev\x18\x04 \x01(\x0e2\x16.spec.scalars.SeverityR\x03sev\x12\x12\n" +
	"\x04argv\x18\x05 \x03(\tR\x04argv\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x03R\x03pid:$¨\x1d \b\x01X\x01\xa0\x01\x01\xa8\x01\x01\xf0\x01\x01\xfa\x01\x01,\xc0\x02\x01\xc8\x02\x01\xd0\x02\x01\xd8\x02\x01\xe0\x02\x01\"\xaa\x01\n" +
	"\x17MessageLevelTimeFormats\x12(\n" +
	"\x01a\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x01a\x12(\n" +
	"\x01b\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x01b\x12-\n" +
	"\x04took\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x04took:\f¨\x1d\b\b\x01\xd8\x02\x03\xe0\x02\x03\"\x7f\n" +
	"\x19MessageLevelEnumBytesJoin\x12(\n" +
	"\x03sev\x18\x01 \x01(\x0e2\x16.spec.scalars.SeverityR\x03sev\x12\x0e\n" +
	"\x02by\x18\x02 \x01(\fR\x02by\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv:\x14¨\x1d\x10\b\x01\xf0\x01\x05\xfa\x01\x02::\xc0\x02\x02\xd0\x02\x03*I\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x02*Q\n" +
	"\bStripped\x12\x18\n" +
	"\x14STRIPPED_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTRIPPED_LOW\x10\x01\x12\x11\n" +
	"\rSTRIPPED_HIGH\x10\x02\x1a\x06¨\x1d\x02\x10\x01*;\n" +
	"\aNumeric\x12\x17\n" +
	"\x13NUMERIC_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vNUMERIC_ONE\x10\x01\x1a\x06¨\x1d\x02\b\x02*x\n" +
	"\aRenamed\x12\x17\n" +
	"\x13RENAMED_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\vRENAMED_LOW\x10\x01\x1a\t¨\x1d\x05\n" +
	"\x03low\x12\x1c\n" +
	"\fRENAMED_HIGH\x10\x02\x1a\n" +
	"¨\x1d\x06\n" +
	"\x04high\x12\x1a\n" +
	"\x0eRENAMED_HIDDEN\x10\x03\x1a\x06¨\x1d\x02\x10\x01BBZ@github.com/gopherex/protoc-gen-go-plainjson/example/spec/scalarsb\x06proto3"

var (
	file_example_spec_scalars_scalars_proto_rawDescOnce sync.Once
	file_example_spec_scalars_scalars_proto_rawDescData []byte
)

func file_example_spec_scalars_scalars_proto_rawDescGZIP() []byte {
	file_example_spec_scalars_scalars_proto_rawDescOnce.Do(func() {
		file_example_spec_scalars_scalars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_spec_scalars_scalars_proto_rawDesc), len(file_example_spec_scalars_scalars_proto_rawDesc)))
	})
	return file_example_spec_scalars_scalars_proto_rawDescData
}

var file_example_spec_scalars_scalars_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_example_spec_scalars_scalars_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_example_spec_scalars_scalars_proto_goTypes = []any{
	(Severity)(0),                     // 0: spec.scalars.Severity
	(Stripped)(0),                     // 1: spec.scalars.Stripped
	(Numeric)(0),                      // 2: spec.scalars.Numeric
	(Renamed)(0),                      // 3: spec.scalars.Renamed
	(*Baseline)(nil),                  // 4: spec.scalars.Baseline
	(*SpecialFloats)(nil),             // 5: spec.scalars.SpecialFloats
	(*Int64AsNumber)(nil),             // 6: spec.scalars.Int64AsNumber
	(*Int64Mixed)(nil),                // 7: spec.scalars.Int64Mixed
	(*BytesFormats)(nil),              // 8: spec.scalars.BytesFormats
	(*EnumFormats)(nil),               // 9: spec.scalars.EnumFormats
	(*EnumFieldOverridesType)(nil),    // 10: spec.scalars.EnumFieldOverridesType
	(*WellKnown)(nil),                 // 11: spec.scalars.WellKnown
	(*TimeFormats)(nil),               // 12: spec.scalars.TimeFormats
	(*DurationFormats)(nil),           // 13: spec.scalars.DurationFormats
	(*Inner)(nil),                     // 14: spec.scalars.Inner
	(*FormatsPropagate)(nil),          // 15: spec.scalars.FormatsPropagate
	(*ExplicitProtojsonDefaults)(nil), // 16: spec.scalars.ExplicitProtojsonDefaults
	(*MessageLevelTimeFormats)(nil),   // 17: spec.scalars.MessageLevelTimeFormats
	(*MessageLevelEnumBytesJoin)(nil), // 18: spec.scalars.MessageLevelEnumBytesJoin
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),       // 20: google.protobuf.Duration
	(*wrapperspb.StringValue)(nil),    // 21: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),     // 22: google.protobuf.Int32Value
	(*wrapperspb.BoolValue)(nil),      // 23: google.protobuf.BoolValue
	(*structpb.Struct)(nil),           // 24: google.protobuf.Struct
	(*structpb.Value)(nil),            // 25: google.protobuf.Value
	(*structpb.ListValue)(nil),        // 26: google.protobuf.ListValue
	(*emptypb.Empty)(nil),             // 27: google.protobuf.Empty
	(*fieldmaskpb.FieldMask)(nil),     // 28: google.protobuf.FieldMask
	(*anypb.Any)(nil),                 // 29: google.protobuf.Any
}
var file_example_spec_scalars_scalars_proto_depIdxs = []int32{
	0,  // 0: spec.scalars.Baseline.sev:type_name -> spec.scalars.Severity
	0,  // 1: spec.scalars.EnumFormats.name:type_name -> spec.scalars.Severity
	0,  // 2: spec.scalars.EnumFormats.number:type_name -> spec.scalars.Severity
	1,  // 3: spec.scalars.EnumFormats.stripped:type_name -> spec.scalars.Stripped
	2,  // 4: spec.scalars.EnumFormats.enum_level:type_name -> spec.scalars.Numeric
	3,  // 5: spec.scalars.EnumFormats.renamed:type_name -> spec.scalars.Renamed
	2,  // 6: spec.scalars.EnumFieldOverridesType.forced_name:type_name -> spec.scalars.Numeric
	19, // 7: spec.scalars.WellKnown.ts:type_name -> google.protobuf.Timestamp
	20, // 8: spec.scalars.WellKnown.dur:type_name -> google.protobuf.Duration
	21, // 9: spec.scalars.WellKnown.sv:type_name -> google.protobuf.StringValue
	22, // 10: spec.scalars.WellKnown.iv:type_name -> google.protobuf.Int32Value
	23, // 11: spec.scalars.WellKnown.bv:type_name -> google.protobuf.BoolValue
	24, // 12: spec.scalars.WellKnown.st:type_name -> google.protobuf.Struct
	25, // 13: spec.scalars.WellKnown.val:type_name -> google.protobuf.Value
	26, // 14: spec.scalars.WellKnown.lst:type_name -> google.protobuf.ListValue
	27, // 15: spec.scalars.WellKnown.emp:type_name -> google.protobuf.Empty
	28, // 16: spec.scalars.WellKnown.fm:type_name -> google.protobuf.FieldMask
	29, // 17: spec.scalars.WellKnown.any:type_name -> google.protobuf.Any
	19, // 18: spec.scalars.TimeFormats.rfc:type_name -> google.protobuf.Timestamp
	19, // 19: spec.scalars.TimeFormats.secs:type_name -> google.protobuf.Timestamp
	19, // 20: spec.scalars.TimeFormats.millis:type_name -> google.protobuf.Timestamp
	19, // 21: spec.scalars.TimeFormats.micros:type_name -> google.protobuf.Timestamp
	19, // 22: spec.scalars.TimeFormats.nanos:type_name -> google.protobuf.Timestamp
	20, // 23: spec.scalars.DurationFormats.pj:type_name -> google.protobuf.Duration
	20, // 24: spec.scalars.DurationFormats.secs:type_name -> google.protobuf.Duration
	20, // 25: spec.scalars.DurationFormats.millis:type_name -> google.protobuf.Duration
	20, // 26: spec.scalars.DurationFormats.nanos:type_name -> google.protobuf.Duration
	19, // 27: spec.scalars.Inner.ts:type_name -> google.protobuf.Timestamp
	14, // 28: spec.scalars.FormatsPropagate.inner:type_name -> spec.scalars.Inner
	19, // 29: spec.scalars.ExplicitProtojsonDefaults.ts:type_name -> google.protobuf.Timestamp
	20, // 30: spec.scalars.ExplicitProtojsonDefaults.dur:type_name -> google.protobuf.Duration
	0,  // 31: spec.scalars.ExplicitProtojsonDefaults.sev:type_name -> spec.scalars.Severity
	19, // 32: spec.scalars.MessageLevelTimeFormats.a:type_name -> google.protobuf.Timestamp
	19, // 33: spec.scalars.MessageLevelTimeFormats.b:type_name -> google.protobuf.Timestamp
	20, // 34: spec.scalars.MessageLevelTimeFormats.took:type_name -> google.protobuf.Duration
	0,  // 35: spec.scalars.MessageLevelEnumBytesJoin.sev:type_name -> spec.scalars.Severity
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_example_spec_scalars_scalars_proto_init() }
func file_example_spec_scalars_scalars_proto_init() {
	if File_example_spec_scalars_scalars_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_spec_scalars_scalars_proto_rawDesc), len(file_example_spec_scalars_scalars_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_spec_scalars_scalars_proto_goTypes,
		DependencyIndexes: file_example_spec_scalars_scalars_proto_depIdxs,
		EnumInfos:         file_example_spec_scalars_scalars_proto_enumTypes,
		MessageInfos:      file_example_spec_scalars_scalars_proto_msgTypes,
	}.Build()
	File_example_spec_scalars_scalars_proto = out.File
	file_example_spec_scalars_scalars_proto_goTypes = nil
	file_example_spec_scalars_scalars_proto_depIdxs = nil
}
