// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: example/spec/presence/presence.proto

package presence

import (
	_ "github.com/gopherex/protoc-gen-go-plainjson/plainjson"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Leaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	N             int32                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaf) Reset() {
	*x = Leaf{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaf) ProtoMessage() {}

func (x *Leaf) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaf.ProtoReflect.Descriptor instead.
func (*Leaf) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{0}
}

func (x *Leaf) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Leaf) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

// Implicit-presence zeros are omitted, matching protojson.
// zero input -> {}
type OmitsZeros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	B             bool                   `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	By            []byte                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	Msg           *Leaf                  `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OmitsZeros) Reset() {
	*x = OmitsZeros{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OmitsZeros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OmitsZeros) ProtoMessage() {}

func (x *OmitsZeros) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OmitsZeros.ProtoReflect.Descriptor instead.
func (*OmitsZeros) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{1}
}

func (x *OmitsZeros) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *OmitsZeros) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *OmitsZeros) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *OmitsZeros) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *OmitsZeros) GetMsg() *Leaf {
	if x != nil {
		return x.Msg
	}
	return nil
}

// emit_empty forces every key to appear with its zero value.
// zero input -> {"n":0,"s":"","b":false,"by":"","nested_a":"","nested_n":0}
type EmitsZeros struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	S             string                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	B             bool                   `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	By            []byte                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	Msg           *Leaf                  `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitsZeros) Reset() {
	*x = EmitsZeros{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitsZeros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitsZeros) ProtoMessage() {}

func (x *EmitsZeros) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitsZeros.ProtoReflect.Descriptor instead.
func (*EmitsZeros) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{2}
}

func (x *EmitsZeros) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *EmitsZeros) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *EmitsZeros) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *EmitsZeros) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *EmitsZeros) GetMsg() *Leaf {
	if x != nil {
		return x.Msg
	}
	return nil
}

// A per-field override wins over the message default, both ways.
// zero input -> {"forced":0}
type MixedEmitEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forced        int32                  `protobuf:"varint,1,opt,name=forced,proto3" json:"forced,omitempty"`
	Quiet         string                 `protobuf:"bytes,2,opt,name=quiet,proto3" json:"quiet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixedEmitEmpty) Reset() {
	*x = MixedEmitEmpty{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixedEmitEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixedEmitEmpty) ProtoMessage() {}

func (x *MixedEmitEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixedEmitEmpty.ProtoReflect.Descriptor instead.
func (*MixedEmitEmpty) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{3}
}

func (x *MixedEmitEmpty) GetForced() int32 {
	if x != nil {
		return x.Forced
	}
	return 0
}

func (x *MixedEmitEmpty) GetQuiet() string {
	if x != nil {
		return x.Quiet
	}
	return ""
}

// Explicit presence beats the zero check: an optional set to 0 is emitted.
// {"opt":0} when set to zero, {} when unset
type ExplicitPresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opt           *int32                 `protobuf:"varint,1,opt,name=opt,proto3,oneof" json:"opt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplicitPresence) Reset() {
	*x = ExplicitPresence{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplicitPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplicitPresence) ProtoMessage() {}

func (x *ExplicitPresence) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplicitPresence.ProtoReflect.Descriptor instead.
func (*ExplicitPresence) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{4}
}

func (x *ExplicitPresence) GetOpt() int32 {
	if x != nil && x.Opt != nil {
		return *x.Opt
	}
	return 0
}

// Wrappers carry presence too; a set wrapper holding 0 is emitted.
// {"iv":0,"sv":""}
type WrapperPresence struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Iv            *wrapperspb.Int32Value  `protobuf:"bytes,1,opt,name=iv,proto3" json:"iv,omitempty"`
	Sv            *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=sv,proto3" json:"sv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrapperPresence) Reset() {
	*x = WrapperPresence{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrapperPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrapperPresence) ProtoMessage() {}

func (x *WrapperPresence) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrapperPresence.ProtoReflect.Descriptor instead.
func (*WrapperPresence) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{5}
}

func (x *WrapperPresence) GetIv() *wrapperspb.Int32Value {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *WrapperPresence) GetSv() *wrapperspb.StringValue {
	if x != nil {
		return x.Sv
	}
	return nil
}

// An unset oneof contributes nothing.
// {"id":"x"}
type UnsetOneof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Choice:
	//
	//	*UnsetOneof_A
	//	*UnsetOneof_B
	Choice        isUnsetOneof_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsetOneof) Reset() {
	*x = UnsetOneof{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsetOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsetOneof) ProtoMessage() {}

func (x *UnsetOneof) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsetOneof.ProtoReflect.Descriptor instead.
func (*UnsetOneof) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{6}
}

func (x *UnsetOneof) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnsetOneof) GetChoice() isUnsetOneof_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *UnsetOneof) GetA() string {
	if x != nil {
		if x, ok := x.Choice.(*UnsetOneof_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *UnsetOneof) GetB() string {
	if x != nil {
		if x, ok := x.Choice.(*UnsetOneof_B); ok {
			return x.B
		}
	}
	return ""
}

type isUnsetOneof_Choice interface {
	isUnsetOneof_Choice()
}

type UnsetOneof_A struct {
	A string `protobuf:"bytes,2,opt,name=a,proto3,oneof"`
}

type UnsetOneof_B struct {
	B string `protobuf:"bytes,3,opt,name=b,proto3,oneof"`
}

func (*UnsetOneof_A) isUnsetOneof_Choice() {}

func (*UnsetOneof_B) isUnsetOneof_Choice() {}

// A set branch holding a zero value is still emitted: the branch has presence.
// {"a":""}
type OneofZeroBranch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choice:
	//
	//	*OneofZeroBranch_A
	//	*OneofZeroBranch_B
	Choice        isOneofZeroBranch_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofZeroBranch) Reset() {
	*x = OneofZeroBranch{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofZeroBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofZeroBranch) ProtoMessage() {}

func (x *OneofZeroBranch) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofZeroBranch.ProtoReflect.Descriptor instead.
func (*OneofZeroBranch) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{7}
}

func (x *OneofZeroBranch) GetChoice() isOneofZeroBranch_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *OneofZeroBranch) GetA() string {
	if x != nil {
		if x, ok := x.Choice.(*OneofZeroBranch_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *OneofZeroBranch) GetB() int32 {
	if x != nil {
		if x, ok := x.Choice.(*OneofZeroBranch_B); ok {
			return x.B
		}
	}
	return 0
}

type isOneofZeroBranch_Choice interface {
	isOneofZeroBranch_Choice()
}

type OneofZeroBranch_A struct {
	A string `protobuf:"bytes,1,opt,name=a,proto3,oneof"`
}

type OneofZeroBranch_B struct {
	B int32 `protobuf:"varint,2,opt,name=b,proto3,oneof"`
}

func (*OneofZeroBranch_A) isOneofZeroBranch_Choice() {}

func (*OneofZeroBranch_B) isOneofZeroBranch_Choice() {}

// emit_empty on a message field yields a fixed-shape record out of a sparse
// tree: every leaf key of the subtree appears.
// empty input -> {"a":"","n":0}
type FixedShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaf          *Leaf                  `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedShape) Reset() {
	*x = FixedShape{}
	mi := &file_example_spec_presence_presence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedShape) ProtoMessage() {}

func (x *FixedShape) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_presence_presence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedShape.ProtoReflect.Descriptor instead.
func (*FixedShape) Descriptor() ([]byte, []int) {
	return file_example_spec_presence_presence_proto_rawDescGZIP(), []int{8}
}

func (x *FixedShape) GetLeaf() *Leaf {
	if x != nil {
		return x.Leaf
	}
	return nil
}

var File_example_spec_presence_presence_proto protoreflect.FileDescriptor

const file_example_spec_presence_presence_proto_rawDesc = "" +
	"\n" +
	"$example/spec/presence/presence.proto\x12\rspec.presence\x1a\x19plainjson/plainjson.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\"\n" +
	"\x04Leaf\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n\"u\n" +
	"\n" +
	"OmitsZeros\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\f\n" +
	"\x01b\x18\x03 \x01(\bR\x01b\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\fR\x02by\x12%\n" +
	"\x03msg\x18\x05 \x01(\v2\x13.spec.presence.LeafR\x03msg:\x06¨\x1d\x02\b\x01\"\x88\x01\n" +
	"\n" +
	"EmitsZeros\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\x12\f\n" +
	"\x01s\x18\x02 \x01(\tR\x01s\x12\f\n" +
	"\x01b\x18\x03 \x01(\bR\x01b\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\fR\x02by\x124\n" +
	"\x03msg\x18\x05 \x01(\v2\x13.spec.presence.LeafB\r¨\x1d\t\x1a\anested_R\x03msg:\n" +
	"¨\x1d\x06\b\x01`\x03p\x01\"Q\n" +
	"\x0eMixedEmitEmpty\x12\x16\n" +
	"\x06forced\x18\x01 \x01(\x05R\x06forced\x12\x1d\n" +
	"\x05quiet\x18\x02 \x01(\tB\a¨\x1d\x03\x80\x02\x00R\x05quiet:\b¨\x1d\x04\b\x01p\x01\"9\n" +
	"\x10ExplicitPresence\x12\x15\n" +
	"\x03opt\x18\x01 \x01(\x05H\x00R\x03opt\x88\x01\x01:\x06¨\x1d\x02\b\x01B\x06\n" +
	"\x04_opt\"t\n" +
	"\x0fWrapperPresence\x12+\n" +
	"\x02iv\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x02iv\x12,\n" +
	"\x02sv\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x02sv:\x06¨\x1d\x02\b\x01\"N\n" +
	"\n" +
	"UnsetOneof\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x01a\x18\x02 \x01(\tH\x00R\x01a\x12\x0e\n" +
	"\x01b\x18\x03 \x01(\tH\x00R\x01b:\x06¨\x1d\x02\b\x01B\b\n" +
	"\x06choice\"C\n" +
	"\x0fOneofZeroBranch\x12\x0e\n" +
	"\x01a\x18\x01 \x01(\tH\x00R\x01a\x12\x0e\n" +
	"\x01b\x18\x02 \x01(\x05H\x00R\x01b:\x06¨\x1d\x02\b\x01B\b\n" +
	"\x06choice\"F\n" +
	"\n" +
	"FixedShape\x120\n" +
	"\x04leaf\x18\x01 \x01(\v2\x13.spec.presence.LeafB\a¨\x1d\x03\x80\x02\x01R\x04leaf:\x06¨\x1d\x02\b\x01BCZAgithub.com/gopherex/protoc-gen-go-plainjson/example/spec/presenceb\x06proto3"

var (
	file_example_spec_presence_presence_proto_rawDescOnce sync.Once
	file_example_spec_presence_presence_proto_rawDescData []byte
)

func file_example_spec_presence_presence_proto_rawDescGZIP() []byte {
	file_example_spec_presence_presence_proto_rawDescOnce.Do(func() {
		file_example_spec_presence_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_spec_presence_presence_proto_rawDesc), len(file_example_spec_presence_presence_proto_rawDesc)))
	})
	return file_example_spec_presence_presence_proto_rawDescData
}

var file_example_spec_presence_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_example_spec_presence_presence_proto_goTypes = []any{
	(*Leaf)(nil),                   // 0: spec.presence.Leaf
	(*OmitsZeros)(nil),             // 1: spec.presence.OmitsZeros
	(*EmitsZeros)(nil),             // 2: spec.presence.EmitsZeros
	(*MixedEmitEmpty)(nil),         // 3: spec.presence.MixedEmitEmpty
	(*ExplicitPresence)(nil),       // 4: spec.presence.ExplicitPresence
	(*WrapperPresence)(nil),        // 5: spec.presence.WrapperPresence
	(*UnsetOneof)(nil),             // 6: spec.presence.UnsetOneof
	(*OneofZeroBranch)(nil),        // 7: spec.presence.OneofZeroBranch
	(*FixedShape)(nil),             // 8: spec.presence.FixedShape
	(*wrapperspb.Int32Value)(nil),  // 9: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
}
var file_example_spec_presence_presence_proto_depIdxs = []int32{
	0,  // 0: spec.presence.OmitsZeros.msg:type_name -> spec.presence.Leaf
	0,  // 1: spec.presence.EmitsZeros.msg:type_name -> spec.presence.Leaf
	9,  // 2: spec.presence.WrapperPresence.iv:type_name -> google.protobuf.Int32Value
	10, // 3: spec.presence.WrapperPresence.sv:type_name -> google.protobuf.StringValue
	0,  // 4: spec.presence.FixedShape.leaf:type_name -> spec.presence.Leaf
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_example_spec_presence_presence_proto_init() }
func file_example_spec_presence_presence_proto_init() {
	if File_example_spec_presence_presence_proto != nil {
		return
	}
	file_example_spec_presence_presence_proto_msgTypes[4].OneofWrappers = []any{}
	file_example_spec_presence_presence_proto_msgTypes[6].OneofWrappers = []any{
		(*UnsetOneof_A)(nil),
		(*UnsetOneof_B)(nil),
	}
	file_example_spec_presence_presence_proto_msgTypes[7].OneofWrappers = []any{
		(*OneofZeroBranch_A)(nil),
		(*OneofZeroBranch_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_spec_presence_presence_proto_rawDesc), len(file_example_spec_presence_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_spec_presence_presence_proto_goTypes,
		DependencyIndexes: file_example_spec_presence_presence_proto_depIdxs,
		MessageInfos:      file_example_spec_presence_presence_proto_msgTypes,
	}.Build()
	File_example_spec_presence_presence_proto = out.File
	file_example_spec_presence_presence_proto_goTypes = nil
	file_example_spec_presence_presence_proto_depIdxs = nil
}
