// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: example/spec/collisions/collisions.proto

package collisions

import (
	_ "github.com/gopherex/protoc-gen-go-plainjson/plainjson"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cgroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cgroup) Reset() {
	*x = Cgroup{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cgroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cgroup) ProtoMessage() {}

func (x *Cgroup) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cgroup.ProtoReflect.Descriptor instead.
func (*Cgroup) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{0}
}

func (x *Cgroup) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Linux struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Cgroup        *Cgroup                `protobuf:"bytes,2,opt,name=cgroup,proto3" json:"cgroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Linux) Reset() {
	*x = Linux{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Linux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Linux) ProtoMessage() {}

func (x *Linux) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Linux.ProtoReflect.Descriptor instead.
func (*Linux) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{1}
}

func (x *Linux) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Linux) GetCgroup() *Cgroup {
	if x != nil {
		return x.Cgroup
	}
	return nil
}

type Exe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exe) Reset() {
	*x = Exe{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exe) ProtoMessage() {}

func (x *Exe) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exe.ProtoReflect.Descriptor instead.
func (*Exe) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{2}
}

func (x *Exe) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Exe) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// Two live subtrees both yield "path". Default policy IGNORE + wins FIRST:
// traversal order decides, silently.
// {"pid":4242,"path":"/sys/fs/x","sha256":"9f86"}
type IgnoreFirst struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linux         *Linux                 `protobuf:"bytes,1,opt,name=linux,proto3" json:"linux,omitempty"`
	Exe           *Exe                   `protobuf:"bytes,2,opt,name=exe,proto3" json:"exe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgnoreFirst) Reset() {
	*x = IgnoreFirst{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgnoreFirst) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnoreFirst) ProtoMessage() {}

func (x *IgnoreFirst) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnoreFirst.ProtoReflect.Descriptor instead.
func (*IgnoreFirst) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{3}
}

func (x *IgnoreFirst) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

func (x *IgnoreFirst) GetExe() *Exe {
	if x != nil {
		return x.Exe
	}
	return nil
}

// The same shape with LAST: the later writer wins (buffered).
// {"pid":4242,"path":"/usr/bin/curl","sha256":"9f86"}
type IgnoreLast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linux         *Linux                 `protobuf:"bytes,1,opt,name=linux,proto3" json:"linux,omitempty"`
	Exe           *Exe                   `protobuf:"bytes,2,opt,name=exe,proto3" json:"exe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgnoreLast) Reset() {
	*x = IgnoreLast{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgnoreLast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnoreLast) ProtoMessage() {}

func (x *IgnoreLast) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnoreLast.ProtoReflect.Descriptor instead.
func (*IgnoreLast) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{4}
}

func (x *IgnoreLast) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

func (x *IgnoreLast) GetExe() *Exe {
	if x != nil {
		return x.Exe
	}
	return nil
}

// FIRST means "first source that is actually non-empty": an empty earlier
// source does not claim the key.
// linux.cgroup.path empty -> {"pid":4242,"path":"/usr/bin/curl","sha256":"9f86"}
type FirstSkipsEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linux         *Linux                 `protobuf:"bytes,1,opt,name=linux,proto3" json:"linux,omitempty"`
	Exe           *Exe                   `protobuf:"bytes,2,opt,name=exe,proto3" json:"exe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirstSkipsEmpty) Reset() {
	*x = FirstSkipsEmpty{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirstSkipsEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstSkipsEmpty) ProtoMessage() {}

func (x *FirstSkipsEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstSkipsEmpty.ProtoReflect.Descriptor instead.
func (*FirstSkipsEmpty) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{5}
}

func (x *FirstSkipsEmpty) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

func (x *FirstSkipsEmpty) GetExe() *Exe {
	if x != nil {
		return x.Exe
	}
	return nil
}

// A prefix applies to every key of the subtree it is set on, so it goes on the
// clashing branch rather than on the whole message field.
type LinuxPrefixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Cgroup        *Cgroup                `protobuf:"bytes,2,opt,name=cgroup,proto3" json:"cgroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinuxPrefixed) Reset() {
	*x = LinuxPrefixed{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxPrefixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxPrefixed) ProtoMessage() {}

func (x *LinuxPrefixed) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxPrefixed.ProtoReflect.Descriptor instead.
func (*LinuxPrefixed) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{6}
}

func (x *LinuxPrefixed) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LinuxPrefixed) GetCgroup() *Cgroup {
	if x != nil {
		return x.Cgroup
	}
	return nil
}

// Disambiguated by prefix: no collision left.
// {"pid":4242,"cgroup_path":"/sys/fs/x","path":"/usr/bin/curl","sha256":"9f86"}
type ResolvedByPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linux         *LinuxPrefixed         `protobuf:"bytes,1,opt,name=linux,proto3" json:"linux,omitempty"`
	Exe           *Exe                   `protobuf:"bytes,2,opt,name=exe,proto3" json:"exe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedByPrefix) Reset() {
	*x = ResolvedByPrefix{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedByPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedByPrefix) ProtoMessage() {}

func (x *ResolvedByPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedByPrefix.ProtoReflect.Descriptor instead.
func (*ResolvedByPrefix) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{7}
}

func (x *ResolvedByPrefix) GetLinux() *LinuxPrefixed {
	if x != nil {
		return x.Linux
	}
	return nil
}

func (x *ResolvedByPrefix) GetExe() *Exe {
	if x != nil {
		return x.Exe
	}
	return nil
}

// Disambiguated by KEY_FROM_PATH: collision-free by construction.
// {"linuxPid":4242,"linuxCgroupPath":"/sys/fs/x","exePath":"/usr/bin/curl","exeSha256":"9f86"}
type ResolvedByPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linux         *Linux                 `protobuf:"bytes,1,opt,name=linux,proto3" json:"linux,omitempty"`
	Exe           *Exe                   `protobuf:"bytes,2,opt,name=exe,proto3" json:"exe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedByPath) Reset() {
	*x = ResolvedByPath{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedByPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedByPath) ProtoMessage() {}

func (x *ResolvedByPath) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedByPath.ProtoReflect.Descriptor instead.
func (*ResolvedByPath) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{8}
}

func (x *ResolvedByPath) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

func (x *ResolvedByPath) GetExe() *Exe {
	if x != nil {
		return x.Exe
	}
	return nil
}

// Runtime policy: the error fires only when both sources actually write.
type RuntimeDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Linux         *Linux                 `protobuf:"bytes,1,opt,name=linux,proto3" json:"linux,omitempty"`
	Exe           *Exe                   `protobuf:"bytes,2,opt,name=exe,proto3" json:"exe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeDetected) Reset() {
	*x = RuntimeDetected{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeDetected) ProtoMessage() {}

func (x *RuntimeDetected) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeDetected.ProtoReflect.Descriptor instead.
func (*RuntimeDetected) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{9}
}

func (x *RuntimeDetected) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

func (x *RuntimeDetected) GetExe() *Exe {
	if x != nil {
		return x.Exe
	}
	return nil
}

type Docker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Docker) Reset() {
	*x = Docker{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Docker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docker) ProtoMessage() {}

func (x *Docker) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docker.ProtoReflect.Descriptor instead.
func (*Docker) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{10}
}

func (x *Docker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Podman struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Podman) Reset() {
	*x = Podman{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Podman) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Podman) ProtoMessage() {}

func (x *Podman) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Podman.ProtoReflect.Descriptor instead.
func (*Podman) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{11}
}

func (x *Podman) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Containerd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Containerd) Reset() {
	*x = Containerd{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Containerd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Containerd) ProtoMessage() {}

func (x *Containerd) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Containerd.ProtoReflect.Descriptor instead.
func (*Containerd) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{12}
}

func (x *Containerd) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Declared exclusive: sharing "id" is not a collision even under
// ERROR_GENERATE, because at most one member is ever set.
// {"id":"c0ffee"}
type ExclusiveGroupOK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docker        *Docker                `protobuf:"bytes,1,opt,name=docker,proto3" json:"docker,omitempty"`
	Podman        *Podman                `protobuf:"bytes,2,opt,name=podman,proto3" json:"podman,omitempty"`
	Containerd    *Containerd            `protobuf:"bytes,3,opt,name=containerd,proto3" json:"containerd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExclusiveGroupOK) Reset() {
	*x = ExclusiveGroupOK{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExclusiveGroupOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusiveGroupOK) ProtoMessage() {}

func (x *ExclusiveGroupOK) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusiveGroupOK.ProtoReflect.Descriptor instead.
func (*ExclusiveGroupOK) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{13}
}

func (x *ExclusiveGroupOK) GetDocker() *Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *ExclusiveGroupOK) GetPodman() *Podman {
	if x != nil {
		return x.Podman
	}
	return nil
}

func (x *ExclusiveGroupOK) GetContainerd() *Containerd {
	if x != nil {
		return x.Containerd
	}
	return nil
}

// The same declaration under ERROR_RUNTIME: if the promise is broken and two
// members are set, the encode fails.
type ExclusiveGroupViolated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docker        *Docker                `protobuf:"bytes,1,opt,name=docker,proto3" json:"docker,omitempty"`
	Podman        *Podman                `protobuf:"bytes,2,opt,name=podman,proto3" json:"podman,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExclusiveGroupViolated) Reset() {
	*x = ExclusiveGroupViolated{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExclusiveGroupViolated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusiveGroupViolated) ProtoMessage() {}

func (x *ExclusiveGroupViolated) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusiveGroupViolated.ProtoReflect.Descriptor instead.
func (*ExclusiveGroupViolated) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{14}
}

func (x *ExclusiveGroupViolated) GetDocker() *Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *ExclusiveGroupViolated) GetPodman() *Podman {
	if x != nil {
		return x.Podman
	}
	return nil
}

// Exclusive group over dot paths rather than top-level fields.
type Wrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docker        *Docker                `protobuf:"bytes,1,opt,name=docker,proto3" json:"docker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrapper) Reset() {
	*x = Wrapper{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapper) ProtoMessage() {}

func (x *Wrapper) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapper.ProtoReflect.Descriptor instead.
func (*Wrapper) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{15}
}

func (x *Wrapper) GetDocker() *Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

type ExclusiveGroupDotPaths struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Wrapper               `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Wrapper               `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExclusiveGroupDotPaths) Reset() {
	*x = ExclusiveGroupDotPaths{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExclusiveGroupDotPaths) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExclusiveGroupDotPaths) ProtoMessage() {}

func (x *ExclusiveGroupDotPaths) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExclusiveGroupDotPaths.ProtoReflect.Descriptor instead.
func (*ExclusiveGroupDotPaths) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{16}
}

func (x *ExclusiveGroupDotPaths) GetLeft() *Wrapper {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *ExclusiveGroupDotPaths) GetRight() *Wrapper {
	if x != nil {
		return x.Right
	}
	return nil
}

// CARDINALITY_EXPLODE over several elements: a dynamic collision that only
// ERROR_RUNTIME can see.
type Elem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	K             string                 `protobuf:"bytes,1,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Elem) Reset() {
	*x = Elem{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Elem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Elem) ProtoMessage() {}

func (x *Elem) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Elem.ProtoReflect.Descriptor instead.
func (*Elem) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{17}
}

func (x *Elem) GetK() string {
	if x != nil {
		return x.K
	}
	return ""
}

type ExplodeCollision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elems         []*Elem                `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplodeCollision) Reset() {
	*x = ExplodeCollision{}
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplodeCollision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplodeCollision) ProtoMessage() {}

func (x *ExplodeCollision) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_collisions_collisions_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplodeCollision.ProtoReflect.Descriptor instead.
func (*ExplodeCollision) Descriptor() ([]byte, []int) {
	return file_example_spec_collisions_collisions_proto_rawDescGZIP(), []int{18}
}

func (x *ExplodeCollision) GetElems() []*Elem {
	if x != nil {
		return x.Elems
	}
	return nil
}

var File_example_spec_collisions_collisions_proto protoreflect.FileDescriptor

const file_example_spec_collisions_collisions_proto_rawDesc = "" +
	"\n" +
	"(example/spec/collisions/collisions.proto\x12\x0fspec.collisions\x1a\x19plainjson/plainjson.proto\"\x1c\n" +
	"\x06Cgroup\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"J\n" +
	"\x05Linux\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12/\n" +
	"\x06cgroup\x18\x02 \x01(\v2\x17.spec.collisions.CgroupR\x06cgroup\"1\n" +
	"\x03Exe\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"k\n" +
	"\vIgnoreFirst\x12,\n" +
	"\x05linux\x18\x01 \x01(\v2\x16.spec.collisions.LinuxR\x05linux\x12&\n" +
	"\x03exe\x18\x02 \x01(\v2\x14.spec.collisions.ExeR\x03exe:\x06¨\x1d\x02\b\x01\"m\n" +
	"\n" +
	"IgnoreLast\x12,\n" +
	"\x05linux\x18\x01 \x01(\v2\x16.spec.collisions.LinuxR\x05linux\x12&\n" +
	"\x03exe\x18\x02 \x01(\v2\x14.spec.collisions.ExeR\x03exe:\t¨\x1d\x05\b\x01\xa8\x01\x02\"o\n" +
	"\x0fFirstSkipsEmpty\x12,\n" +
	"\x05linux\x18\x01 \x01(\v2\x16.spec.collisions.LinuxR\x05linux\x12&\n" +
	"\x03exe\x18\x02 \x01(\v2\x14.spec.collisions.ExeR\x03exe:\x06¨\x1d\x02\b\x01\"a\n" +
	"\rLinuxPrefixed\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12>\n" +
	"\x06cgroup\x18\x02 \x01(\v2\x17.spec.collisions.CgroupB\r¨\x1d\t\x1a\acgroup_R\x06cgroup\"}\n" +
	"\x10ResolvedByPrefix\x124\n" +
	"\x05linux\x18\x01 \x01(\v2\x1e.spec.collisions.LinuxPrefixedR\x05linux\x12&\n" +
	"\x03exe\x18\x02 \x01(\v2\x14.spec.collisions.ExeR\x03exe:\v¨\x1d\a\b\x01`\x03\xa0\x01\x02\"s\n" +
	"\x0eResolvedByPath\x12,\n" +
	"\x05linux\x18\x01 \x01(\v2\x16.spec.collisions.LinuxR\x05linux\x12&\n" +
	"\x03exe\x18\x02 \x01(\v2\x14.spec.collisions.ExeR\x03exe:\v¨\x1d\a\b\x01X\x02\xa0\x01\x02\"r\n" +
	"\x0fRuntimeDetected\x12,\n" +
	"\x05linux\x18\x01 \x01(\v2\x16.spec.collisions.LinuxR\x05linux\x12&\n" +
	"\x03exe\x18\x02 \x01(\v2\x14.spec.collisions.ExeR\x03exe:\t¨\x1d\x05\b\x01\xa0\x01\x03\"\x18\n" +
	"\x06Docker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x06Podman\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"Containerd\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdb\x01\n" +
	"\x10ExclusiveGroupOK\x12/\n" +
	"\x06docker\x18\x01 \x01(\v2\x17.spec.collisions.DockerR\x06docker\x12/\n" +
	"\x06podman\x18\x02 \x01(\v2\x17.spec.collisions.PodmanR\x06podman\x12;\n" +
	"\n" +
	"containerd\x18\x03 \x01(\v2\x1b.spec.collisions.ContainerdR\n" +
	"containerd:(¨\x1d$\b\x01\xa0\x01\x02\xa2\x03\x1c\n" +
	"\x06docker\n" +
	"\x06podman\n" +
	"\n" +
	"containerd\"\x98\x01\n" +
	"\x16ExclusiveGroupViolated\x12/\n" +
	"\x06docker\x18\x01 \x01(\v2\x17.spec.collisions.DockerR\x06docker\x12/\n" +
	"\x06podman\x18\x02 \x01(\v2\x17.spec.collisions.PodmanR\x06podman:\x1c¨\x1d\x18\b\x01\xa0\x01\x03\xa2\x03\x10\n" +
	"\x06docker\n" +
	"\x06podman\":\n" +
	"\aWrapper\x12/\n" +
	"\x06docker\x18\x01 \x01(\v2\x17.spec.collisions.DockerR\x06docker\"\x9f\x01\n" +
	"\x16ExclusiveGroupDotPaths\x12,\n" +
	"\x04left\x18\x01 \x01(\v2\x18.spec.collisions.WrapperR\x04left\x12.\n" +
	"\x05right\x18\x02 \x01(\v2\x18.spec.collisions.WrapperR\x05right:'¨\x1d#\b\x01\xa0\x01\x02\xa2\x03\x1b\n" +
	"\vleft.docker\n" +
	"\fright.docker\"\x14\n" +
	"\x04Elem\x12\f\n" +
	"\x01k\x18\x01 \x01(\tR\x01k\"S\n" +
	"\x10ExplodeCollision\x124\n" +
	"\x05elems\x18\x01 \x03(\v2\x15.spec.collisions.ElemB\a¨\x1d\x03\xa0\x01\aR\x05elems:\t¨\x1d\x05\b\x01\xa0\x01\x03BEZCgithub.com/gopherex/protoc-gen-go-plainjson/example/spec/collisionsb\x06proto3"

var (
	file_example_spec_collisions_collisions_proto_rawDescOnce sync.Once
	file_example_spec_collisions_collisions_proto_rawDescData []byte
)

func file_example_spec_collisions_collisions_proto_rawDescGZIP() []byte {
	file_example_spec_collisions_collisions_proto_rawDescOnce.Do(func() {
		file_example_spec_collisions_collisions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_spec_collisions_collisions_proto_rawDesc), len(file_example_spec_collisions_collisions_proto_rawDesc)))
	})
	return file_example_spec_collisions_collisions_proto_rawDescData
}

var file_example_spec_collisions_collisions_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_example_spec_collisions_collisions_proto_goTypes = []any{
	(*Cgroup)(nil),                 // 0: spec.collisions.Cgroup
	(*Linux)(nil),                  // 1: spec.collisions.Linux
	(*Exe)(nil),                    // 2: spec.collisions.Exe
	(*IgnoreFirst)(nil),            // 3: spec.collisions.IgnoreFirst
	(*IgnoreLast)(nil),             // 4: spec.collisions.IgnoreLast
	(*FirstSkipsEmpty)(nil),        // 5: spec.collisions.FirstSkipsEmpty
	(*LinuxPrefixed)(nil),          // 6: spec.collisions.LinuxPrefixed
	(*ResolvedByPrefix)(nil),       // 7: spec.collisions.ResolvedByPrefix
	(*ResolvedByPath)(nil),         // 8: spec.collisions.ResolvedByPath
	(*RuntimeDetected)(nil),        // 9: spec.collisions.RuntimeDetected
	(*Docker)(nil),                 // 10: spec.collisions.Docker
	(*Podman)(nil),                 // 11: spec.collisions.Podman
	(*Containerd)(nil),             // 12: spec.collisions.Containerd
	(*ExclusiveGroupOK)(nil),       // 13: spec.collisions.ExclusiveGroupOK
	(*ExclusiveGroupViolated)(nil), // 14: spec.collisions.ExclusiveGroupViolated
	(*Wrapper)(nil),                // 15: spec.collisions.Wrapper
	(*ExclusiveGroupDotPaths)(nil), // 16: spec.collisions.ExclusiveGroupDotPaths
	(*Elem)(nil),                   // 17: spec.collisions.Elem
	(*ExplodeCollision)(nil),       // 18: spec.collisions.ExplodeCollision
}
var file_example_spec_collisions_collisions_proto_depIdxs = []int32{
	0,  // 0: spec.collisions.Linux.cgroup:type_name -> spec.collisions.Cgroup
	1,  // 1: spec.collisions.IgnoreFirst.linux:type_name -> spec.collisions.Linux
	2,  // 2: spec.collisions.IgnoreFirst.exe:type_name -> spec.collisions.Exe
	1,  // 3: spec.collisions.IgnoreLast.linux:type_name -> spec.collisions.Linux
	2,  // 4: spec.collisions.IgnoreLast.exe:type_name -> spec.collisions.Exe
	1,  // 5: spec.collisions.FirstSkipsEmpty.linux:type_name -> spec.collisions.Linux
	2,  // 6: spec.collisions.FirstSkipsEmpty.exe:type_name -> spec.collisions.Exe
	0,  // 7: spec.collisions.LinuxPrefixed.cgroup:type_name -> spec.collisions.Cgroup
	6,  // 8: spec.collisions.ResolvedByPrefix.linux:type_name -> spec.collisions.LinuxPrefixed
	2,  // 9: spec.collisions.ResolvedByPrefix.exe:type_name -> spec.collisions.Exe
	1,  // 10: spec.collisions.ResolvedByPath.linux:type_name -> spec.collisions.Linux
	2,  // 11: spec.collisions.ResolvedByPath.exe:type_name -> spec.collisions.Exe
	1,  // 12: spec.collisions.RuntimeDetected.linux:type_name -> spec.collisions.Linux
	2,  // 13: spec.collisions.RuntimeDetected.exe:type_name -> spec.collisions.Exe
	10, // 14: spec.collisions.ExclusiveGroupOK.docker:type_name -> spec.collisions.Docker
	11, // 15: spec.collisions.ExclusiveGroupOK.podman:type_name -> spec.collisions.Podman
	12, // 16: spec.collisions.ExclusiveGroupOK.containerd:type_name -> spec.collisions.Containerd
	10, // 17: spec.collisions.ExclusiveGroupViolated.docker:type_name -> spec.collisions.Docker
	11, // 18: spec.collisions.ExclusiveGroupViolated.podman:type_name -> spec.collisions.Podman
	10, // 19: spec.collisions.Wrapper.docker:type_name -> spec.collisions.Docker
	15, // 20: spec.collisions.ExclusiveGroupDotPaths.left:type_name -> spec.collisions.Wrapper
	15, // 21: spec.collisions.ExclusiveGroupDotPaths.right:type_name -> spec.collisions.Wrapper
	17, // 22: spec.collisions.ExplodeCollision.elems:type_name -> spec.collisions.Elem
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_example_spec_collisions_collisions_proto_init() }
func file_example_spec_collisions_collisions_proto_init() {
	if File_example_spec_collisions_collisions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_spec_collisions_collisions_proto_rawDesc), len(file_example_spec_collisions_collisions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_spec_collisions_collisions_proto_goTypes,
		DependencyIndexes: file_example_spec_collisions_collisions_proto_depIdxs,
		MessageInfos:      file_example_spec_collisions_collisions_proto_msgTypes,
	}.Build()
	File_example_spec_collisions_collisions_proto = out.File
	file_example_spec_collisions_collisions_proto_goTypes = nil
	file_example_spec_collisions_collisions_proto_depIdxs = nil
}
