// Code generated by protoc-gen-go-plainjson. DO NOT EDIT.
//
// The marshalers below are one-way: they flatten a message into JSON and
// cannot read it back.
//
// source: example/spec/oneofs/oneofs.proto

package oneofs

import (
	jx "github.com/go-faster/jx"
	plainjsonpb "github.com/gopherex/protoc-gen-go-plainjson/plainjsonpb"
	strings "strings"
)

// plainjsonEnumName_Level renders spec.oneofs.Level the way its options ask for.
func plainjsonEnumName_Level(v Level) string {
	switch v {
	case Level_LEVEL_UNSPECIFIED:
		return "LEVEL_UNSPECIFIED"
	case Level_LEVEL_ONE:
		return "LEVEL_ONE"
	}
	return v.String()
}

// EncodePlainJSON writes the flattened form of InlineMode into e.
func (m *InlineMode) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_InlineMode(m, e)
}

// MarshalPlainJSON returns the flattened form of InlineMode.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *InlineMode) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_InlineMode(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of BranchKeyMode into e.
func (m *BranchKeyMode) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_BranchKeyMode(m, e)
}

// MarshalPlainJSON returns the flattened form of BranchKeyMode.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *BranchKeyMode) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_BranchKeyMode(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of TaggedMode into e.
func (m *TaggedMode) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_TaggedMode(m, e)
}

// MarshalPlainJSON returns the flattened form of TaggedMode.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *TaggedMode) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_TaggedMode(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of SingleKeyMode into e.
func (m *SingleKeyMode) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_SingleKeyMode(m, e)
}

// MarshalPlainJSON returns the flattened form of SingleKeyMode.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *SingleKeyMode) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_SingleKeyMode(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of DiscriminatorOnlyMode into e.
func (m *DiscriminatorOnlyMode) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_DiscriminatorOnlyMode(m, e)
}

// MarshalPlainJSON returns the flattened form of DiscriminatorOnlyMode.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *DiscriminatorOnlyMode) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_DiscriminatorOnlyMode(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of OmitMode into e.
func (m *OmitMode) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_OmitMode(m, e)
}

// MarshalPlainJSON returns the flattened form of OmitMode.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *OmitMode) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_OmitMode(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of OmitIfUnsetFalse into e.
func (m *OmitIfUnsetFalse) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_OmitIfUnsetFalse(m, e)
}

// MarshalPlainJSON returns the flattened form of OmitIfUnsetFalse.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *OmitIfUnsetFalse) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_OmitIfUnsetFalse(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of ScalarBranches into e.
func (m *ScalarBranches) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_ScalarBranches(m, e)
}

// MarshalPlainJSON returns the flattened form of ScalarBranches.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *ScalarBranches) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_ScalarBranches(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of ScalarBranchesMerged into e.
func (m *ScalarBranchesMerged) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_ScalarBranchesMerged(m, e)
}

// MarshalPlainJSON returns the flattened form of ScalarBranchesMerged.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *ScalarBranchesMerged) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_ScalarBranchesMerged(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of ExclusiveLeafCollapse into e.
func (m *ExclusiveLeafCollapse) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_ExclusiveLeafCollapse(m, e)
}

// MarshalPlainJSON returns the flattened form of ExclusiveLeafCollapse.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *ExclusiveLeafCollapse) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_ExclusiveLeafCollapse(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of OneofLevelFormats into e.
func (m *OneofLevelFormats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_OneofLevelFormats(m, e)
}

// MarshalPlainJSON returns the flattened form of OneofLevelFormats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *OneofLevelFormats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_OneofLevelFormats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of OneofLevelTimeFormats into e.
func (m *OneofLevelTimeFormats) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_OneofLevelTimeFormats(m, e)
}

// MarshalPlainJSON returns the flattened form of OneofLevelTimeFormats.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *OneofLevelTimeFormats) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_OneofLevelTimeFormats(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of BranchOverridesOneof into e.
func (m *BranchOverridesOneof) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_BranchOverridesOneof(m, e)
}

// MarshalPlainJSON returns the flattened form of BranchOverridesOneof.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *BranchOverridesOneof) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_BranchOverridesOneof(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// encodePlainJSON_InlineMode writes spec.oneofs.InlineMode as a flat JSON object.
func encodePlainJSON_InlineMode(m *InlineMode, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	// x <- click.x
	if v := m.GetClick().GetX(); v != 0 {
		e.FieldStart("x")
		e.Int32(v)
	}
	// y <- click.y
	if v := m.GetClick().GetY(); v != 0 {
		e.FieldStart("y")
		e.Int32(v)
	}
	// dy <- scroll.dy
	if v := m.GetScroll().GetDy(); v != 0 {
		e.FieldStart("dy")
		e.Int32(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_BranchKeyMode writes spec.oneofs.BranchKeyMode as a flat JSON object.
func encodePlainJSON_BranchKeyMode(m *BranchKeyMode, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	// click <- click
	if v := m.GetClick(); v != nil {
		e.FieldStart("click")
		if err := encodePlainJSON_Click(v, e); err != nil {
			return err
		}
	}
	// scroll <- scroll
	if v := m.GetScroll(); v != nil {
		e.FieldStart("scroll")
		if err := encodePlainJSON_Scroll(v, e); err != nil {
			return err
		}
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_TaggedMode writes spec.oneofs.TaggedMode as a flat JSON object.
func encodePlainJSON_TaggedMode(m *TaggedMode, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	// type <- spec.oneofs.TaggedMode.payload discriminator
	switch m.GetPayload().(type) {
	case *TaggedMode_Click:
		e.FieldStart("type")
		e.Str("click")
	case *TaggedMode_Scroll:
		e.FieldStart("type")
		e.Str("SCROLL_EV")
	}
	// x <- click.x
	if v := m.GetClick().GetX(); v != 0 {
		e.FieldStart("x")
		e.Int32(v)
	}
	// y <- click.y
	if v := m.GetClick().GetY(); v != 0 {
		e.FieldStart("y")
		e.Int32(v)
	}
	// dy <- scroll.dy
	if v := m.GetScroll().GetDy(); v != 0 {
		e.FieldStart("dy")
		e.Int32(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_SingleKeyMode writes spec.oneofs.SingleKeyMode as a flat JSON object.
func encodePlainJSON_SingleKeyMode(m *SingleKeyMode, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	// payload <- spec.oneofs.SingleKeyMode.payload
	switch b := m.GetPayload().(type) {
	case *SingleKeyMode_Click:
		e.FieldStart("payload")
		if err := encodePlainJSON_Click(b.Click, e); err != nil {
			return err
		}
	case *SingleKeyMode_Scroll:
		e.FieldStart("payload")
		if err := encodePlainJSON_Scroll(b.Scroll, e); err != nil {
			return err
		}
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_DiscriminatorOnlyMode writes spec.oneofs.DiscriminatorOnlyMode as a flat JSON object.
func encodePlainJSON_DiscriminatorOnlyMode(m *DiscriminatorOnlyMode, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	// type <- spec.oneofs.DiscriminatorOnlyMode.payload discriminator
	switch m.GetPayload().(type) {
	case *DiscriminatorOnlyMode_Click:
		e.FieldStart("type")
		e.Str("click")
	case *DiscriminatorOnlyMode_Scroll:
		e.FieldStart("type")
		e.Str("scroll")
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_OmitMode writes spec.oneofs.OmitMode as a flat JSON object.
func encodePlainJSON_OmitMode(m *OmitMode, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_OmitIfUnsetFalse writes spec.oneofs.OmitIfUnsetFalse as a flat JSON object.
func encodePlainJSON_OmitIfUnsetFalse(m *OmitIfUnsetFalse, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	// type <- spec.oneofs.OmitIfUnsetFalse.payload discriminator
	switch m.GetPayload().(type) {
	case *OmitIfUnsetFalse_Click:
		e.FieldStart("type")
		e.Str("click")
	case *OmitIfUnsetFalse_Scroll:
		e.FieldStart("type")
		e.Str("scroll")
	default:
		e.FieldStart("type")
		e.Null()
	}
	// x <- click.x
	if v := m.GetClick().GetX(); v != 0 {
		e.FieldStart("x")
		e.Int32(v)
	}
	// y <- click.y
	if v := m.GetClick().GetY(); v != 0 {
		e.FieldStart("y")
		e.Int32(v)
	}
	// dy <- scroll.dy
	if v := m.GetScroll().GetDy(); v != 0 {
		e.FieldStart("dy")
		e.Int32(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_ScalarBranches writes spec.oneofs.ScalarBranches as a flat JSON object.
func encodePlainJSON_ScalarBranches(m *ScalarBranches, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// uuid <- uuid
	if b, ok := m.GetId().(*ScalarBranches_Uuid); ok {
		e.FieldStart("uuid")
		e.Str(b.Uuid)
	}
	// seq <- seq
	if b, ok := m.GetId().(*ScalarBranches_Seq); ok {
		e.FieldStart("seq")
		plainjsonpb.Int64(e, b.Seq, false)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_ScalarBranchesMerged writes spec.oneofs.ScalarBranchesMerged as a flat JSON object.
func encodePlainJSON_ScalarBranchesMerged(m *ScalarBranchesMerged, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- uuid
	if b, ok := m.GetId().(*ScalarBranchesMerged_Uuid); ok {
		e.FieldStart("id")
		e.Str(b.Uuid)
	}
	// id <- seq
	if b, ok := m.GetId().(*ScalarBranchesMerged_Seq); ok {
		e.FieldStart("id")
		plainjsonpb.Int64(e, b.Seq, false)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_ExclusiveLeafCollapse writes spec.oneofs.ExclusiveLeafCollapse as a flat JSON object.
func encodePlainJSON_ExclusiveLeafCollapse(m *ExclusiveLeafCollapse, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// pid <- linux.pid
	if v := m.GetLinux().GetPid(); v != 0 {
		e.FieldStart("pid")
		e.Int32(v)
	}
	// cgroup <- linux.cgroup
	if v := m.GetLinux().GetCgroup(); v != "" {
		e.FieldStart("cgroup")
		e.Str(v)
	}
	// pid <- windows.pid
	if v := m.GetWindows().GetPid(); v != 0 {
		e.FieldStart("pid")
		e.Int32(v)
	}
	// sid <- windows.sid
	if v := m.GetWindows().GetSid(); v != "" {
		e.FieldStart("sid")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_OneofLevelFormats writes spec.oneofs.OneofLevelFormats as a flat JSON object.
func encodePlainJSON_OneofLevelFormats(m *OneofLevelFormats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// n <- a.n
	if m.GetA() != nil {
		e.FieldStart("n")
		plainjsonpb.Int64(e, m.GetA().GetN(), true)
	}
	// by <- a.by
	if m.GetA() != nil {
		e.FieldStart("by")
		plainjsonpb.Bytes(e, m.GetA().GetBy(), 3)
	}
	// argv <- a.argv
	if m.GetA() != nil {
		e.FieldStart("argv")
		{
			var sb strings.Builder
			for i, item := range m.GetA().GetArgv() {
				if i > 0 {
					sb.WriteString("/")
				}
				sb.WriteString(item)
			}
			e.Str(sb.String())
		}
	}
	// n <- b.n
	if m.GetB() != nil {
		e.FieldStart("n")
		plainjsonpb.Int64(e, m.GetB().GetN(), true)
	}
	// by <- b.by
	if m.GetB() != nil {
		e.FieldStart("by")
		plainjsonpb.Bytes(e, m.GetB().GetBy(), 3)
	}
	// argv <- b.argv
	if m.GetB() != nil {
		e.FieldStart("argv")
		{
			var sb strings.Builder
			for i, item := range m.GetB().GetArgv() {
				if i > 0 {
					sb.WriteString("/")
				}
				sb.WriteString(item)
			}
			e.Str(sb.String())
		}
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_OneofLevelTimeFormats writes spec.oneofs.OneofLevelTimeFormats as a flat JSON object.
func encodePlainJSON_OneofLevelTimeFormats(m *OneofLevelTimeFormats, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// ts <- t.ts
	if v := m.GetT().GetTs(); v != nil {
		e.FieldStart("ts")
		plainjsonpb.Timestamp(e, v, 2)
	}
	// dur <- t.dur
	if v := m.GetT().GetDur(); v != nil {
		e.FieldStart("dur")
		plainjsonpb.Duration(e, v, 3)
	}
	// lvl <- t.lvl
	if v := m.GetT().GetLvl(); v != 0 {
		e.FieldStart("lvl")
		e.Int32(int32(v))
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_BranchOverridesOneof writes spec.oneofs.BranchOverridesOneof as a flat JSON object.
func encodePlainJSON_BranchOverridesOneof(m *BranchOverridesOneof, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// n <- a.n
	if v := m.GetA().GetN(); v != 0 {
		e.FieldStart("n")
		plainjsonpb.Int64(e, v, false)
	}
	// by <- a.by
	if v := m.GetA().GetBy(); len(v) > 0 {
		e.FieldStart("by")
		plainjsonpb.Bytes(e, v, 1)
	}
	// argv <- a.argv
	if len(m.GetA().GetArgv()) > 0 {
		e.FieldStart("argv")
		e.ArrStart()
		for _, item := range m.GetA().GetArgv() {
			e.Str(item)
		}
		e.ArrEnd()
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_Click writes spec.oneofs.Click as a flat JSON object.
func encodePlainJSON_Click(m *Click, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// x <- x
	if v := m.GetX(); v != 0 {
		e.FieldStart("x")
		e.Int32(v)
	}
	// y <- y
	if v := m.GetY(); v != 0 {
		e.FieldStart("y")
		e.Int32(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_Scroll writes spec.oneofs.Scroll as a flat JSON object.
func encodePlainJSON_Scroll(m *Scroll, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// dy <- dy
	if v := m.GetDy(); v != 0 {
		e.FieldStart("dy")
		e.Int32(v)
	}
	e.ObjEnd()
	return nil
}
