// Code generated by protoc-gen-go-plainjson. DO NOT EDIT.
//
// The marshalers below are one-way: they flatten a message into JSON and
// cannot read it back.
//
// source: example/spec/keys/keys.proto

package keys

import (
	jx "github.com/go-faster/jx"
)

// EncodePlainJSON writes the flattened form of LeafCamel into e.
func (m *LeafCamel) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_LeafCamel(m, e)
}

// MarshalPlainJSON returns the flattened form of LeafCamel.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *LeafCamel) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_LeafCamel(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of LeafSnake into e.
func (m *LeafSnake) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_LeafSnake(m, e)
}

// MarshalPlainJSON returns the flattened form of LeafSnake.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *LeafSnake) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_LeafSnake(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of LeafOriginal into e.
func (m *LeafOriginal) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_LeafOriginal(m, e)
}

// MarshalPlainJSON returns the flattened form of LeafOriginal.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *LeafOriginal) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_LeafOriginal(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of PathCamel into e.
func (m *PathCamel) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_PathCamel(m, e)
}

// MarshalPlainJSON returns the flattened form of PathCamel.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *PathCamel) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_PathCamel(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of PathSnake into e.
func (m *PathSnake) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_PathSnake(m, e)
}

// MarshalPlainJSON returns the flattened form of PathSnake.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *PathSnake) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_PathSnake(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of MixedKeyFrom into e.
func (m *MixedKeyFrom) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_MixedKeyFrom(m, e)
}

// MarshalPlainJSON returns the flattened form of MixedKeyFrom.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *MixedKeyFrom) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_MixedKeyFrom(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of NameOverride into e.
func (m *NameOverride) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_NameOverride(m, e)
}

// MarshalPlainJSON returns the flattened form of NameOverride.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *NameOverride) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_NameOverride(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of PrefixAccumulation into e.
func (m *PrefixAccumulation) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_PrefixAccumulation(m, e)
}

// MarshalPlainJSON returns the flattened form of PrefixAccumulation.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *PrefixAccumulation) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_PrefixAccumulation(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of PrefixOriginalCase into e.
func (m *PrefixOriginalCase) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_PrefixOriginalCase(m, e)
}

// MarshalPlainJSON returns the flattened form of PrefixOriginalCase.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *PrefixOriginalCase) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_PrefixOriginalCase(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of SuffixUse into e.
func (m *SuffixUse) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_SuffixUse(m, e)
}

// MarshalPlainJSON returns the flattened form of SuffixUse.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *SuffixUse) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_SuffixUse(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of NameAffectsPathSegment into e.
func (m *NameAffectsPathSegment) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_NameAffectsPathSegment(m, e)
}

// MarshalPlainJSON returns the flattened form of NameAffectsPathSegment.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *NameAffectsPathSegment) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_NameAffectsPathSegment(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of MixedKeyCase into e.
func (m *MixedKeyCase) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_MixedKeyCase(m, e)
}

// MarshalPlainJSON returns the flattened form of MixedKeyCase.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *MixedKeyCase) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_MixedKeyCase(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// encodePlainJSON_LeafCamel writes spec.keys.LeafCamel as a flat JSON object.
func encodePlainJSON_LeafCamel(m *LeafCamel, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// pid <- process.linux.pid
	if v := m.GetProcess().GetLinux().GetPid(); v != 0 {
		e.FieldStart("pid")
		e.Int32(v)
	}
	// cgroupPath <- process.linux.cgroup_path
	if v := m.GetProcess().GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("cgroupPath")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_LeafSnake writes spec.keys.LeafSnake as a flat JSON object.
func encodePlainJSON_LeafSnake(m *LeafSnake, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// pid <- process.linux.pid
	if v := m.GetProcess().GetLinux().GetPid(); v != 0 {
		e.FieldStart("pid")
		e.Int32(v)
	}
	// cgroup_path <- process.linux.cgroup_path
	if v := m.GetProcess().GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("cgroup_path")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_LeafOriginal writes spec.keys.LeafOriginal as a flat JSON object.
func encodePlainJSON_LeafOriginal(m *LeafOriginal, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// pid <- process.linux.pid
	if v := m.GetProcess().GetLinux().GetPid(); v != 0 {
		e.FieldStart("pid")
		e.Int32(v)
	}
	// cgroup_path <- process.linux.cgroup_path
	if v := m.GetProcess().GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("cgroup_path")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_PathCamel writes spec.keys.PathCamel as a flat JSON object.
func encodePlainJSON_PathCamel(m *PathCamel, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// processLinuxPid <- process.linux.pid
	if v := m.GetProcess().GetLinux().GetPid(); v != 0 {
		e.FieldStart("processLinuxPid")
		e.Int32(v)
	}
	// processLinuxCgroupPath <- process.linux.cgroup_path
	if v := m.GetProcess().GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("processLinuxCgroupPath")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_PathSnake writes spec.keys.PathSnake as a flat JSON object.
func encodePlainJSON_PathSnake(m *PathSnake, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// process_linux_pid <- process.linux.pid
	if v := m.GetProcess().GetLinux().GetPid(); v != 0 {
		e.FieldStart("process_linux_pid")
		e.Int32(v)
	}
	// process_linux_cgroup_path <- process.linux.cgroup_path
	if v := m.GetProcess().GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("process_linux_cgroup_path")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_MixedKeyFrom writes spec.keys.MixedKeyFrom as a flat JSON object.
func encodePlainJSON_MixedKeyFrom(m *MixedKeyFrom, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// leftLinuxPid <- left.linux.pid
	if v := m.GetLeft().GetLinux().GetPid(); v != 0 {
		e.FieldStart("leftLinuxPid")
		e.Int32(v)
	}
	// leftLinuxCgroupPath <- left.linux.cgroup_path
	if v := m.GetLeft().GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("leftLinuxCgroupPath")
		e.Str(v)
	}
	// pid <- right.linux.pid
	if v := m.GetRight().GetLinux().GetPid(); v != 0 {
		e.FieldStart("pid")
		e.Int32(v)
	}
	// cgroupPath <- right.linux.cgroup_path
	if v := m.GetRight().GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("cgroupPath")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_NameOverride writes spec.keys.NameOverride as a flat JSON object.
func encodePlainJSON_NameOverride(m *NameOverride, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// processId <- linux.pid
	if v := m.GetLinux().GetPid(); v != 0 {
		e.FieldStart("processId")
		e.Int32(v)
	}
	// cgroupPath <- linux.cgroup_path
	if v := m.GetLinux().GetCgroupPath(); v != "" {
		e.FieldStart("cgroupPath")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_PrefixAccumulation writes spec.keys.PrefixAccumulation as a flat JSON object.
func encodePlainJSON_PrefixAccumulation(m *PrefixAccumulation, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// shipName <- shipping.name
	if v := m.GetShipping().GetName(); v != "" {
		e.FieldStart("shipName")
		e.Str(v)
	}
	// shipAddrCity <- shipping.addr.city
	if v := m.GetShipping().GetAddr().GetCity(); v != "" {
		e.FieldStart("shipAddrCity")
		e.Str(v)
	}
	// billName <- billing.name
	if v := m.GetBilling().GetName(); v != "" {
		e.FieldStart("billName")
		e.Str(v)
	}
	// billAddrCity <- billing.addr.city
	if v := m.GetBilling().GetAddr().GetCity(); v != "" {
		e.FieldStart("billAddrCity")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_PrefixOriginalCase writes spec.keys.PrefixOriginalCase as a flat JSON object.
func encodePlainJSON_PrefixOriginalCase(m *PrefixOriginalCase, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// ship_name <- shipping.name
	if v := m.GetShipping().GetName(); v != "" {
		e.FieldStart("ship_name")
		e.Str(v)
	}
	// ship_addr_city <- shipping.addr.city
	if v := m.GetShipping().GetAddr().GetCity(); v != "" {
		e.FieldStart("ship_addr_city")
		e.Str(v)
	}
	// bill_name <- billing.name
	if v := m.GetBilling().GetName(); v != "" {
		e.FieldStart("bill_name")
		e.Str(v)
	}
	// bill_addr_city <- billing.addr.city
	if v := m.GetBilling().GetAddr().GetCity(); v != "" {
		e.FieldStart("bill_addr_city")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_SuffixUse writes spec.keys.SuffixUse as a flat JSON object.
func encodePlainJSON_SuffixUse(m *SuffixUse, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// cityHome <- home.city
	if v := m.GetHome().GetCity(); v != "" {
		e.FieldStart("cityHome")
		e.Str(v)
	}
	// cityWork <- work.city
	if v := m.GetWork().GetCity(); v != "" {
		e.FieldStart("cityWork")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_NameAffectsPathSegment writes spec.keys.NameAffectsPathSegment as a flat JSON object.
func encodePlainJSON_NameAffectsPathSegment(m *NameAffectsPathSegment, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// shipCity <- shipping_address.city
	if v := m.GetShippingAddress().GetCity(); v != "" {
		e.FieldStart("shipCity")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_MixedKeyCase writes spec.keys.MixedKeyCase as a flat JSON object.
func encodePlainJSON_MixedKeyCase(m *MixedKeyCase, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	var wrotePid bool // first non-empty writer of "pid" wins
	e.ObjStart()
	// pid <- left.pid
	if v := m.GetLeft().GetPid(); v != 0 {
		if !wrotePid {
			e.FieldStart("pid")
			e.Int32(v)
			wrotePid = true
		}
	}
	// cgroup_path <- left.cgroup_path
	if v := m.GetLeft().GetCgroupPath(); v != "" {
		e.FieldStart("cgroup_path")
		e.Str(v)
	}
	// pid <- right.pid
	if v := m.GetRight().GetPid(); v != 0 {
		if !wrotePid {
			e.FieldStart("pid")
			e.Int32(v)
			wrotePid = true
		}
	}
	// cgroupPath <- right.cgroup_path
	if v := m.GetRight().GetCgroupPath(); v != "" {
		e.FieldStart("cgroupPath")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}
