// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: example/spec/merging/merging.proto

package merging

import (
	_ "github.com/gopherex/protoc-gen-go-plainjson/plainjson"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	Kind_KIND_ONE         Kind = 1
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_ONE",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_ONE":         1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_example_spec_merging_merging_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_example_spec_merging_merging_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{0}
}

type Ucred struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ucred) Reset() {
	*x = Ucred{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ucred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ucred) ProtoMessage() {}

func (x *Ucred) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ucred.ProtoReflect.Descriptor instead.
func (*Ucred) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{0}
}

func (x *Ucred) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPid       int32                  `protobuf:"varint,1,opt,name=host_pid,json=hostPid,proto3" json:"host_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{1}
}

func (x *Runtime) GetHostPid() int32 {
	if x != nil {
		return x.HostPid
	}
	return 0
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       *Runtime               `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetRuntime() *Runtime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type Linux struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ucred         *Ucred                 `protobuf:"bytes,2,opt,name=ucred,proto3" json:"ucred,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Linux) Reset() {
	*x = Linux{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Linux) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Linux) ProtoMessage() {}

func (x *Linux) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Linux.ProtoReflect.Descriptor instead.
func (*Linux) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{3}
}

func (x *Linux) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Linux) GetUcred() *Ucred {
	if x != nil {
		return x.Ucred
	}
	return nil
}

func (x *Linux) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type Windows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int32                  `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Sid           string                 `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Windows) Reset() {
	*x = Windows{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Windows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Windows) ProtoMessage() {}

func (x *Windows) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Windows.ProtoReflect.Descriptor instead.
func (*Windows) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{4}
}

func (x *Windows) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Windows) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Windows) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// Sources in priority order; the first non-empty wins. Merged paths leave the
// normal plan, so no windowsProcessId / linuxPid keys appear.
// {"image":"nginx","pid":4242,"user":"1000","startedAt":1787000000123}
type Merge struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Container *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// Types that are valid to be assigned to Os:
	//
	//	*Merge_Linux
	//	*Merge_Windows
	Os            isMerge_Os `protobuf_oneof:"os"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merge) Reset() {
	*x = Merge{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merge) ProtoMessage() {}

func (x *Merge) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merge.ProtoReflect.Descriptor instead.
func (*Merge) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{5}
}

func (x *Merge) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *Merge) GetOs() isMerge_Os {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *Merge) GetLinux() *Linux {
	if x != nil {
		if x, ok := x.Os.(*Merge_Linux); ok {
			return x.Linux
		}
	}
	return nil
}

func (x *Merge) GetWindows() *Windows {
	if x != nil {
		if x, ok := x.Os.(*Merge_Windows); ok {
			return x.Windows
		}
	}
	return nil
}

type isMerge_Os interface {
	isMerge_Os()
}

type Merge_Linux struct {
	Linux *Linux `protobuf:"bytes,2,opt,name=linux,proto3,oneof"`
}

type Merge_Windows struct {
	Windows *Windows `protobuf:"bytes,3,opt,name=windows,proto3,oneof"`
}

func (*Merge_Linux) isMerge_Os() {}

func (*Merge_Windows) isMerge_Os() {}

// Priority: container.runtime.host_pid outranks linux.pid when both are set.
// {"pid":999}
type MergePriority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Linux         *Linux                 `protobuf:"bytes,2,opt,name=linux,proto3" json:"linux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergePriority) Reset() {
	*x = MergePriority{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergePriority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergePriority) ProtoMessage() {}

func (x *MergePriority) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergePriority.ProtoReflect.Descriptor instead.
func (*MergePriority) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{6}
}

func (x *MergePriority) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *MergePriority) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

// LAST_NON_EMPTY takes the last source that has a value.
// {"pid":4242}
type MergeLastWins struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Linux         *Linux                 `protobuf:"bytes,2,opt,name=linux,proto3" json:"linux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeLastWins) Reset() {
	*x = MergeLastWins{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeLastWins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeLastWins) ProtoMessage() {}

func (x *MergeLastWins) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeLastWins.ProtoReflect.Descriptor instead.
func (*MergeLastWins) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{7}
}

func (x *MergeLastWins) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *MergeLastWins) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

// ERROR fails at encode time when two sources are non-empty at once.
type MergeErrorOnConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Linux         *Linux                 `protobuf:"bytes,2,opt,name=linux,proto3" json:"linux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeErrorOnConflict) Reset() {
	*x = MergeErrorOnConflict{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeErrorOnConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeErrorOnConflict) ProtoMessage() {}

func (x *MergeErrorOnConflict) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeErrorOnConflict.ProtoReflect.Descriptor instead.
func (*MergeErrorOnConflict) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{8}
}

func (x *MergeErrorOnConflict) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *MergeErrorOnConflict) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

// Every source empty: the key is omitted, unless emit_empty says otherwise.
// {} / {"pid":null}
type MergeAllEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Linux         *Linux                 `protobuf:"bytes,2,opt,name=linux,proto3" json:"linux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeAllEmpty) Reset() {
	*x = MergeAllEmpty{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeAllEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeAllEmpty) ProtoMessage() {}

func (x *MergeAllEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeAllEmpty.ProtoReflect.Descriptor instead.
func (*MergeAllEmpty) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{9}
}

func (x *MergeAllEmpty) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *MergeAllEmpty) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

type MergeAllEmptyEmitted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Linux         *Linux                 `protobuf:"bytes,2,opt,name=linux,proto3" json:"linux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeAllEmptyEmitted) Reset() {
	*x = MergeAllEmptyEmitted{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeAllEmptyEmitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeAllEmptyEmitted) ProtoMessage() {}

func (x *MergeAllEmptyEmitted) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeAllEmptyEmitted.ProtoReflect.Descriptor instead.
func (*MergeAllEmptyEmitted) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{10}
}

func (x *MergeAllEmptyEmitted) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *MergeAllEmptyEmitted) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

// Sources inside mutually exclusive oneof branches; the rule just picks
// whichever is live. raw_key keeps the key verbatim.
// {"PID":77}
type MergeRawKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Os:
	//
	//	*MergeRawKey_Linux
	//	*MergeRawKey_Windows
	Os            isMergeRawKey_Os `protobuf_oneof:"os"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRawKey) Reset() {
	*x = MergeRawKey{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRawKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRawKey) ProtoMessage() {}

func (x *MergeRawKey) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRawKey.ProtoReflect.Descriptor instead.
func (*MergeRawKey) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{11}
}

func (x *MergeRawKey) GetOs() isMergeRawKey_Os {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *MergeRawKey) GetLinux() *Linux {
	if x != nil {
		if x, ok := x.Os.(*MergeRawKey_Linux); ok {
			return x.Linux
		}
	}
	return nil
}

func (x *MergeRawKey) GetWindows() *Windows {
	if x != nil {
		if x, ok := x.Os.(*MergeRawKey_Windows); ok {
			return x.Windows
		}
	}
	return nil
}

type isMergeRawKey_Os interface {
	isMergeRawKey_Os()
}

type MergeRawKey_Linux struct {
	Linux *Linux `protobuf:"bytes,1,opt,name=linux,proto3,oneof"`
}

type MergeRawKey_Windows struct {
	Windows *Windows `protobuf:"bytes,2,opt,name=windows,proto3,oneof"`
}

func (*MergeRawKey_Linux) isMergeRawKey_Os() {}

func (*MergeRawKey_Windows) isMergeRawKey_Os() {}

// Merge rules carry their own value formatting, independent of the fields the
// sources come from.
type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{12}
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Counted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []string               `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Counted) Reset() {
	*x = Counted{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counted) ProtoMessage() {}

func (x *Counted) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counted.ProtoReflect.Descriptor instead.
func (*Counted) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{13}
}

func (x *Counted) GetParts() []string {
	if x != nil {
		return x.Parts
	}
	return nil
}

type Typed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=spec.merging.Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Typed) Reset() {
	*x = Typed{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Typed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Typed) ProtoMessage() {}

func (x *Typed) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Typed.ProtoReflect.Descriptor instead.
func (*Typed) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{14}
}

func (x *Typed) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

type Timed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Took          *durationpb.Duration   `protobuf:"bytes,1,opt,name=took,proto3" json:"took,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timed) Reset() {
	*x = Timed{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timed) ProtoMessage() {}

func (x *Timed) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timed.ProtoReflect.Descriptor instead.
func (*Timed) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{15}
}

func (x *Timed) GetTook() *durationpb.Duration {
	if x != nil {
		return x.Took
	}
	return nil
}

// {"payload":"010203","joined":"a+b","kind":1,"n":-3,"took":1500}
type MergeFormats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          *Blob                  `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	Counted       *Counted               `protobuf:"bytes,2,opt,name=counted,proto3" json:"counted,omitempty"`
	Typed         *Typed                 `protobuf:"bytes,3,opt,name=typed,proto3" json:"typed,omitempty"`
	Linux         *Linux                 `protobuf:"bytes,4,opt,name=linux,proto3" json:"linux,omitempty"`
	Timed         *Timed                 `protobuf:"bytes,5,opt,name=timed,proto3" json:"timed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeFormats) Reset() {
	*x = MergeFormats{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeFormats) ProtoMessage() {}

func (x *MergeFormats) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeFormats.ProtoReflect.Descriptor instead.
func (*MergeFormats) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{16}
}

func (x *MergeFormats) GetBlob() *Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *MergeFormats) GetCounted() *Counted {
	if x != nil {
		return x.Counted
	}
	return nil
}

func (x *MergeFormats) GetTyped() *Typed {
	if x != nil {
		return x.Typed
	}
	return nil
}

func (x *MergeFormats) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

func (x *MergeFormats) GetTimed() *Timed {
	if x != nil {
		return x.Timed
	}
	return nil
}

// Stating FIRST_NON_EMPTY explicitly must behave exactly like the default.
// {"pid":4242}
type MergeExplicitDefaultConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *Container             `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Linux         *Linux                 `protobuf:"bytes,2,opt,name=linux,proto3" json:"linux,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeExplicitDefaultConflict) Reset() {
	*x = MergeExplicitDefaultConflict{}
	mi := &file_example_spec_merging_merging_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeExplicitDefaultConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeExplicitDefaultConflict) ProtoMessage() {}

func (x *MergeExplicitDefaultConflict) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_merging_merging_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeExplicitDefaultConflict.ProtoReflect.Descriptor instead.
func (*MergeExplicitDefaultConflict) Descriptor() ([]byte, []int) {
	return file_example_spec_merging_merging_proto_rawDescGZIP(), []int{17}
}

func (x *MergeExplicitDefaultConflict) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *MergeExplicitDefaultConflict) GetLinux() *Linux {
	if x != nil {
		return x.Linux
	}
	return nil
}

var File_example_spec_merging_merging_proto protoreflect.FileDescriptor

const file_example_spec_merging_merging_proto_rawDesc = "" +
	"\n" +
	"\"example/spec/merging/merging.proto\x12\fspec.merging\x1a\x19plainjson/plainjson.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x19\n" +
	"\x05Ucred\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"$\n" +
	"\aRuntime\x12\x19\n" +
	"\bhost_pid\x18\x01 \x01(\x05R\ahostPid\"R\n" +
	"\tContainer\x12/\n" +
	"\aruntime\x18\x01 \x01(\v2\x15.spec.merging.RuntimeR\aruntime\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\x7f\n" +
	"\x05Linux\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12)\n" +
	"\x05ucred\x18\x02 \x01(\v2\x13.spec.merging.UcredR\x05ucred\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"w\n" +
	"\aWindows\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\x12\x10\n" +
	"\x03sid\x18\x02 \x01(\tR\x03sid\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\xd1\x02\n" +
	"\x05Merge\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.spec.merging.ContainerR\tcontainer\x12+\n" +
	"\x05linux\x18\x02 \x01(\v2\x13.spec.merging.LinuxH\x00R\x05linux\x121\n" +
	"\awindows\x18\x03 \x01(\v2\x15.spec.merging.WindowsH\x00R\awindows:\xaa\x01¨\x1d\xa5\x01\b\x01\x92\x03@\n" +
	"\x03pid\x12\x1acontainer.runtime.host_pid\x12\tlinux.pid\x12\x12windows.process_id\x92\x03$\n" +
	"\x04user\x12\x0flinux.ucred.uid\x12\vwindows.sid\x92\x036\n" +
	"\n" +
	"started_at\x12\x10linux.start_time\x12\x13windows.create_time\xb8\x01\x03B\x04\n" +
	"\x02os\"\xae\x01\n" +
	"\rMergePriority\x12;\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.spec.merging.ContainerB\x04¨\x1d\x00R\tcontainer\x12)\n" +
	"\x05linux\x18\x02 \x01(\v2\x13.spec.merging.LinuxR\x05linux:5¨\x1d1\b\x01\x92\x03,\n" +
	"\x03pid\x12\x1acontainer.runtime.host_pid\x12\tlinux.pid\"\xaa\x01\n" +
	"\rMergeLastWins\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.spec.merging.ContainerR\tcontainer\x12)\n" +
	"\x05linux\x18\x02 \x01(\v2\x13.spec.merging.LinuxR\x05linux:7¨\x1d3\b\x01\x92\x03.\n" +
	"\x03pid\x12\x1acontainer.runtime.host_pid\x12\tlinux.pid\x18\x02\"\xb1\x01\n" +
	"\x14MergeErrorOnConflict\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.spec.merging.ContainerR\tcontainer\x12)\n" +
	"\x05linux\x18\x02 \x01(\v2\x13.spec.merging.LinuxR\x05linux:7¨\x1d3\b\x01\x92\x03.\n" +
	"\x03pid\x12\x1acontainer.runtime.host_pid\x12\tlinux.pid\x18\x03\"\xa8\x01\n" +
	"\rMergeAllEmpty\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.spec.merging.ContainerR\tcontainer\x12)\n" +
	"\x05linux\x18\x02 \x01(\v2\x13.spec.merging.LinuxR\x05linux:5¨\x1d1\b\x01\x92\x03,\n" +
	"\x03pid\x12\x1acontainer.runtime.host_pid\x12\tlinux.pid\"\xb1\x01\n" +
	"\x14MergeAllEmptyEmitted\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.spec.merging.ContainerR\tcontainer\x12)\n" +
	"\x05linux\x18\x02 \x01(\v2\x13.spec.merging.LinuxR\x05linux:7¨\x1d3\b\x01\x92\x03.\n" +
	"\x03pid\x12\x1acontainer.runtime.host_pid\x12\tlinux.pid \x01\"\xa4\x01\n" +
	"\vMergeRawKey\x12+\n" +
	"\x05linux\x18\x01 \x01(\v2\x13.spec.merging.LinuxH\x00R\x05linux\x121\n" +
	"\awindows\x18\x02 \x01(\v2\x15.spec.merging.WindowsH\x00R\awindows:/¨\x1d+\b\x01\x92\x03&\n" +
	"\x03PID\x12\tlinux.pid\x12\x12windows.process_id(\x01B\x04\n" +
	"\x02os\"\x1a\n" +
	"\x04Blob\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x1f\n" +
	"\aCounted\x12\x14\n" +
	"\x05parts\x18\x01 \x03(\tR\x05parts\"/\n" +
	"\x05Typed\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.spec.merging.KindR\x04kind\"6\n" +
	"\x05Timed\x12-\n" +
	"\x04took\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x04took\"\xf1\x02\n" +
	"\fMergeFormats\x12&\n" +
	"\x04blob\x18\x01 \x01(\v2\x12.spec.merging.BlobR\x04blob\x12/\n" +
	"\acounted\x18\x02 \x01(\v2\x15.spec.merging.CountedR\acounted\x12)\n" +
	"\x05typed\x18\x03 \x01(\v2\x13.spec.merging.TypedR\x05typed\x12)\n" +
	"\x05linux\x18\x04 \x01(\v2\x13.spec.merging.LinuxR\x05linux\x12)\n" +
	"\x05timed\x18\x05 \x01(\v2\x13.spec.merging.TimedR\x05timed:\x86\x01¨\x1d\x81\x01\b\x01`\x03\x92\x03\x17\n" +
	"\apayload\x12\tblob.data\xb0\x01\x03\x92\x03\x1c\n" +
	"\x06joined\x12\rcounted.partsP\x05Z\x01+\x92\x03\x15\n" +
	"\x04kind\x12\n" +
	"typed.kind\xa0\x01\x02\x92\x03\x11\n" +
	"\x01n\x12\tlinux.pid\xa8\x01\x02\x92\x03\x15\n" +
	"\x04took\x12\n" +
	"timed.took\xc0\x01\x03\"\xb9\x01\n" +
	"\x1cMergeExplicitDefaultConflict\x125\n" +
	"\tcontainer\x18\x01 \x01(\v2\x17.spec.merging.ContainerR\tcontainer\x12)\n" +
	"\x05linux\x18\x02 \x01(\v2\x13.spec.merging.LinuxR\x05linux:7¨\x1d3\b\x01\x92\x03.\n" +
	"\x03pid\x12\x1acontainer.runtime.host_pid\x12\tlinux.pid\x18\x01**\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bKIND_ONE\x10\x01BBZ@github.com/gopherex/protoc-gen-go-plainjson/example/spec/mergingb\x06proto3"

var (
	file_example_spec_merging_merging_proto_rawDescOnce sync.Once
	file_example_spec_merging_merging_proto_rawDescData []byte
)

func file_example_spec_merging_merging_proto_rawDescGZIP() []byte {
	file_example_spec_merging_merging_proto_rawDescOnce.Do(func() {
		file_example_spec_merging_merging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_spec_merging_merging_proto_rawDesc), len(file_example_spec_merging_merging_proto_rawDesc)))
	})
	return file_example_spec_merging_merging_proto_rawDescData
}

var file_example_spec_merging_merging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_spec_merging_merging_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_example_spec_merging_merging_proto_goTypes = []any{
	(Kind)(0),                            // 0: spec.merging.Kind
	(*Ucred)(nil),                        // 1: spec.merging.Ucred
	(*Runtime)(nil),                      // 2: spec.merging.Runtime
	(*Container)(nil),                    // 3: spec.merging.Container
	(*Linux)(nil),                        // 4: spec.merging.Linux
	(*Windows)(nil),                      // 5: spec.merging.Windows
	(*Merge)(nil),                        // 6: spec.merging.Merge
	(*MergePriority)(nil),                // 7: spec.merging.MergePriority
	(*MergeLastWins)(nil),                // 8: spec.merging.MergeLastWins
	(*MergeErrorOnConflict)(nil),         // 9: spec.merging.MergeErrorOnConflict
	(*MergeAllEmpty)(nil),                // 10: spec.merging.MergeAllEmpty
	(*MergeAllEmptyEmitted)(nil),         // 11: spec.merging.MergeAllEmptyEmitted
	(*MergeRawKey)(nil),                  // 12: spec.merging.MergeRawKey
	(*Blob)(nil),                         // 13: spec.merging.Blob
	(*Counted)(nil),                      // 14: spec.merging.Counted
	(*Typed)(nil),                        // 15: spec.merging.Typed
	(*Timed)(nil),                        // 16: spec.merging.Timed
	(*MergeFormats)(nil),                 // 17: spec.merging.MergeFormats
	(*MergeExplicitDefaultConflict)(nil), // 18: spec.merging.MergeExplicitDefaultConflict
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),          // 20: google.protobuf.Duration
}
var file_example_spec_merging_merging_proto_depIdxs = []int32{
	2,  // 0: spec.merging.Container.runtime:type_name -> spec.merging.Runtime
	1,  // 1: spec.merging.Linux.ucred:type_name -> spec.merging.Ucred
	19, // 2: spec.merging.Linux.start_time:type_name -> google.protobuf.Timestamp
	19, // 3: spec.merging.Windows.create_time:type_name -> google.protobuf.Timestamp
	3,  // 4: spec.merging.Merge.container:type_name -> spec.merging.Container
	4,  // 5: spec.merging.Merge.linux:type_name -> spec.merging.Linux
	5,  // 6: spec.merging.Merge.windows:type_name -> spec.merging.Windows
	3,  // 7: spec.merging.MergePriority.container:type_name -> spec.merging.Container
	4,  // 8: spec.merging.MergePriority.linux:type_name -> spec.merging.Linux
	3,  // 9: spec.merging.MergeLastWins.container:type_name -> spec.merging.Container
	4,  // 10: spec.merging.MergeLastWins.linux:type_name -> spec.merging.Linux
	3,  // 11: spec.merging.MergeErrorOnConflict.container:type_name -> spec.merging.Container
	4,  // 12: spec.merging.MergeErrorOnConflict.linux:type_name -> spec.merging.Linux
	3,  // 13: spec.merging.MergeAllEmpty.container:type_name -> spec.merging.Container
	4,  // 14: spec.merging.MergeAllEmpty.linux:type_name -> spec.merging.Linux
	3,  // 15: spec.merging.MergeAllEmptyEmitted.container:type_name -> spec.merging.Container
	4,  // 16: spec.merging.MergeAllEmptyEmitted.linux:type_name -> spec.merging.Linux
	4,  // 17: spec.merging.MergeRawKey.linux:type_name -> spec.merging.Linux
	5,  // 18: spec.merging.MergeRawKey.windows:type_name -> spec.merging.Windows
	0,  // 19: spec.merging.Typed.kind:type_name -> spec.merging.Kind
	20, // 20: spec.merging.Timed.took:type_name -> google.protobuf.Duration
	13, // 21: spec.merging.MergeFormats.blob:type_name -> spec.merging.Blob
	14, // 22: spec.merging.MergeFormats.counted:type_name -> spec.merging.Counted
	15, // 23: spec.merging.MergeFormats.typed:type_name -> spec.merging.Typed
	4,  // 24: spec.merging.MergeFormats.linux:type_name -> spec.merging.Linux
	16, // 25: spec.merging.MergeFormats.timed:type_name -> spec.merging.Timed
	3,  // 26: spec.merging.MergeExplicitDefaultConflict.container:type_name -> spec.merging.Container
	4,  // 27: spec.merging.MergeExplicitDefaultConflict.linux:type_name -> spec.merging.Linux
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_example_spec_merging_merging_proto_init() }
func file_example_spec_merging_merging_proto_init() {
	if File_example_spec_merging_merging_proto != nil {
		return
	}
	file_example_spec_merging_merging_proto_msgTypes[5].OneofWrappers = []any{
		(*Merge_Linux)(nil),
		(*Merge_Windows)(nil),
	}
	file_example_spec_merging_merging_proto_msgTypes[11].OneofWrappers = []any{
		(*MergeRawKey_Linux)(nil),
		(*MergeRawKey_Windows)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_spec_merging_merging_proto_rawDesc), len(file_example_spec_merging_merging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_spec_merging_merging_proto_goTypes,
		DependencyIndexes: file_example_spec_merging_merging_proto_depIdxs,
		EnumInfos:         file_example_spec_merging_merging_proto_enumTypes,
		MessageInfos:      file_example_spec_merging_merging_proto_msgTypes,
	}.Build()
	File_example_spec_merging_merging_proto = out.File
	file_example_spec_merging_merging_proto_goTypes = nil
	file_example_spec_merging_merging_proto_depIdxs = nil
}
