// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: example/spec/flatten/flatten.proto

package flatten

import (
	_ "github.com/gopherex/protoc-gen-go-plainjson/plainjson"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             string                 `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{0}
}

func (x *Inner) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type Outer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	In            *Inner                 `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{1}
}

func (x *Outer) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Outer) GetIn() *Inner {
	if x != nil {
		return x.In
	}
	return nil
}

// Default mode: FLATTEN_MODE_DEEP.
// {"id":"w","a":"x","b":"y"}
type DeepDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *Outer                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepDefault) Reset() {
	*x = DeepDefault{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepDefault) ProtoMessage() {}

func (x *DeepDefault) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepDefault.ProtoReflect.Descriptor instead.
func (*DeepDefault) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{2}
}

func (x *DeepDefault) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeepDefault) GetOut() *Outer {
	if x != nil {
		return x.Out
	}
	return nil
}

// {"id":"w","a":"x","in":{"b":"y"}}
type Shallow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *Outer                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shallow) Reset() {
	*x = Shallow{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shallow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shallow) ProtoMessage() {}

func (x *Shallow) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shallow.ProtoReflect.Descriptor instead.
func (*Shallow) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{3}
}

func (x *Shallow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shallow) GetOut() *Outer {
	if x != nil {
		return x.Out
	}
	return nil
}

// protojson shape. {"id":"w","out":{"a":"x","in":{"b":"y"}}}
type NoneMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *Outer                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoneMode) Reset() {
	*x = NoneMode{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoneMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoneMode) ProtoMessage() {}

func (x *NoneMode) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoneMode.ProtoReflect.Descriptor instead.
func (*NoneMode) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{4}
}

func (x *NoneMode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoneMode) GetOut() *Outer {
	if x != nil {
		return x.Out
	}
	return nil
}

// Nested by default, one field inlined. {"id":"w","a":"x","b":"y"}
type NoneWithInlinedField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *Outer                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoneWithInlinedField) Reset() {
	*x = NoneWithInlinedField{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoneWithInlinedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoneWithInlinedField) ProtoMessage() {}

func (x *NoneWithInlinedField) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoneWithInlinedField.ProtoReflect.Descriptor instead.
func (*NoneWithInlinedField) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{5}
}

func (x *NoneWithInlinedField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoneWithInlinedField) GetOut() *Outer {
	if x != nil {
		return x.Out
	}
	return nil
}

// A type that keeps its own shape wherever it is used.
type NestedInside struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	In            *Inner                 `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedInside) Reset() {
	*x = NestedInside{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedInside) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedInside) ProtoMessage() {}

func (x *NestedInside) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedInside.ProtoReflect.Descriptor instead.
func (*NestedInside) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{6}
}

func (x *NestedInside) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *NestedInside) GetIn() *Inner {
	if x != nil {
		return x.In
	}
	return nil
}

// Deep by default, one subtree kept nested. The field decides the boundary,
// the type decides the interior: NestedInside stays protojson-shaped.
// {"id":"w","out":{"a":"x","in":{"b":"y"}}}
type DeepWithNestedField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *NestedInside          `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepWithNestedField) Reset() {
	*x = DeepWithNestedField{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepWithNestedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepWithNestedField) ProtoMessage() {}

func (x *DeepWithNestedField) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepWithNestedField.ProtoReflect.Descriptor instead.
func (*DeepWithNestedField) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{7}
}

func (x *DeepWithNestedField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeepWithNestedField) GetOut() *NestedInside {
	if x != nil {
		return x.Out
	}
	return nil
}

// The same boundary over a type whose interior is DEEP: one grouped key,
// flat inside it.
// {"id":"w","out":{"a":"x","b":"y"}}
type NestedKeyFlatInterior struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *Outer                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedKeyFlatInterior) Reset() {
	*x = NestedKeyFlatInterior{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedKeyFlatInterior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedKeyFlatInterior) ProtoMessage() {}

func (x *NestedKeyFlatInterior) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedKeyFlatInterior.ProtoReflect.Descriptor instead.
func (*NestedKeyFlatInterior) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{8}
}

func (x *NestedKeyFlatInterior) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NestedKeyFlatInterior) GetOut() *Outer {
	if x != nil {
		return x.Out
	}
	return nil
}

type FlatInside struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	In            *Inner                 `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatInside) Reset() {
	*x = FlatInside{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatInside) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatInside) ProtoMessage() {}

func (x *FlatInside) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatInside.ProtoReflect.Descriptor instead.
func (*FlatInside) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{9}
}

func (x *FlatInside) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *FlatInside) GetIn() *Inner {
	if x != nil {
		return x.In
	}
	return nil
}

// {"id":"w","out":{"a":"x","b":"y"}}
type GroupedButFlatInside struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *FlatInside            `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupedButFlatInside) Reset() {
	*x = GroupedButFlatInside{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupedButFlatInside) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupedButFlatInside) ProtoMessage() {}

func (x *GroupedButFlatInside) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupedButFlatInside.ProtoReflect.Descriptor instead.
func (*GroupedButFlatInside) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{10}
}

func (x *GroupedButFlatInside) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupedButFlatInside) GetOut() *FlatInside {
	if x != nil {
		return x.Out
	}
	return nil
}

// The same type inlined at one use site, kept nested at another.
// {"a":"x","b":"y","grouped":{"a":"x2","b":"y2"}}
type SameTypeBothWays struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inlined       *FlatInside            `protobuf:"bytes,1,opt,name=inlined,proto3" json:"inlined,omitempty"`
	Grouped       *FlatInside            `protobuf:"bytes,2,opt,name=grouped,proto3" json:"grouped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SameTypeBothWays) Reset() {
	*x = SameTypeBothWays{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SameTypeBothWays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SameTypeBothWays) ProtoMessage() {}

func (x *SameTypeBothWays) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SameTypeBothWays.ProtoReflect.Descriptor instead.
func (*SameTypeBothWays) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{11}
}

func (x *SameTypeBothWays) GetInlined() *FlatInside {
	if x != nil {
		return x.Inlined
	}
	return nil
}

func (x *SameTypeBothWays) GetGrouped() *FlatInside {
	if x != nil {
		return x.Grouped
	}
	return nil
}

// {"id":"w","a":"x","in":{"b":"y"}}
type MaxDepthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Out           *Outer                 `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxDepthMessage) Reset() {
	*x = MaxDepthMessage{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxDepthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxDepthMessage) ProtoMessage() {}

func (x *MaxDepthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxDepthMessage.ProtoReflect.Descriptor instead.
func (*MaxDepthMessage) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{12}
}

func (x *MaxDepthMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MaxDepthMessage) GetOut() *Outer {
	if x != nil {
		return x.Out
	}
	return nil
}

type Level3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D             string                 `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level3) Reset() {
	*x = Level3{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level3) ProtoMessage() {}

func (x *Level3) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level3.ProtoReflect.Descriptor instead.
func (*Level3) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{13}
}

func (x *Level3) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

type Level2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C             string                 `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	L3            *Level3                `protobuf:"bytes,2,opt,name=l3,proto3" json:"l3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level2) Reset() {
	*x = Level2{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level2) ProtoMessage() {}

func (x *Level2) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level2.ProtoReflect.Descriptor instead.
func (*Level2) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{14}
}

func (x *Level2) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

func (x *Level2) GetL3() *Level3 {
	if x != nil {
		return x.L3
	}
	return nil
}

type Level1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             string                 `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	L2            *Level2                `protobuf:"bytes,2,opt,name=l2,proto3" json:"l2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level1) Reset() {
	*x = Level1{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level1) ProtoMessage() {}

func (x *Level1) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level1.ProtoReflect.Descriptor instead.
func (*Level1) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{15}
}

func (x *Level1) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *Level1) GetL2() *Level2 {
	if x != nil {
		return x.L2
	}
	return nil
}

// Depth bounded from the outside, without touching Level1's own options.
// {"a":"1","b":"2","l2":{"c":"3","l3":{"d":"4"}}}
type MaxDepthField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	L1            *Level1                `protobuf:"bytes,2,opt,name=l1,proto3" json:"l1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxDepthField) Reset() {
	*x = MaxDepthField{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxDepthField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxDepthField) ProtoMessage() {}

func (x *MaxDepthField) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxDepthField.ProtoReflect.Descriptor instead.
func (*MaxDepthField) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{16}
}

func (x *MaxDepthField) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *MaxDepthField) GetL1() *Level1 {
	if x != nil {
		return x.L1
	}
	return nil
}

// A self-recursive type that never flattens: the only shape that terminates
// without a depth bound.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Child         *Node                  `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{17}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetChild() *Node {
	if x != nil {
		return x.Child
	}
	return nil
}

// {"root":{"name":"a","child":{"name":"b","child":{"name":"c"}}}}
type RecursiveNone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *Node                  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecursiveNone) Reset() {
	*x = RecursiveNone{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveNone) ProtoMessage() {}

func (x *RecursiveNone) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveNone.ProtoReflect.Descriptor instead.
func (*RecursiveNone) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{18}
}

func (x *RecursiveNone) GetRoot() *Node {
	if x != nil {
		return x.Root
	}
	return nil
}

// A self-recursive type that does flatten. On its own it would cycle; a bound
// at the use site makes it legal.
type DeepNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Child         *DeepNode              `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepNode) Reset() {
	*x = DeepNode{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepNode) ProtoMessage() {}

func (x *DeepNode) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepNode.ProtoReflect.Descriptor instead.
func (*DeepNode) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{19}
}

func (x *DeepNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeepNode) GetChild() *DeepNode {
	if x != nil {
		return x.Child
	}
	return nil
}

// Two levels hoisted, the rest left nested. The later "name" loses to the
// earlier one under the default IGNORE/FIRST policy.
// {"name":"a","child":{"name":"c"}}
type RecursiveBounded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *DeepNode              `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecursiveBounded) Reset() {
	*x = RecursiveBounded{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveBounded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveBounded) ProtoMessage() {}

func (x *RecursiveBounded) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveBounded.ProtoReflect.Descriptor instead.
func (*RecursiveBounded) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{20}
}

func (x *RecursiveBounded) GetRoot() *DeepNode {
	if x != nil {
		return x.Root
	}
	return nil
}

// {"id":"w","items":[{"a":"x","b":"y"}],"tags":{"k":"v"}}
type StopsAtCollections struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []*Outer               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopsAtCollections) Reset() {
	*x = StopsAtCollections{}
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopsAtCollections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopsAtCollections) ProtoMessage() {}

func (x *StopsAtCollections) ProtoReflect() protoreflect.Message {
	mi := &file_example_spec_flatten_flatten_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopsAtCollections.ProtoReflect.Descriptor instead.
func (*StopsAtCollections) Descriptor() ([]byte, []int) {
	return file_example_spec_flatten_flatten_proto_rawDescGZIP(), []int{21}
}

func (x *StopsAtCollections) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopsAtCollections) GetItems() []*Outer {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StopsAtCollections) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_example_spec_flatten_flatten_proto protoreflect.FileDescriptor

const file_example_spec_flatten_flatten_proto_rawDesc = "" +
	"\n" +
	"\"example/spec/flatten/flatten.proto\x12\fspec.flatten\x1a\x19plainjson/plainjson.proto\"\x15\n" +
	"\x05Inner\x12\f\n" +
	"\x01b\x18\x01 \x01(\tR\x01b\":\n" +
	"\x05Outer\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12#\n" +
	"\x02in\x18\x02 \x01(\v2\x13.spec.flatten.InnerR\x02in\"L\n" +
	"\vDeepDefault\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x03out\x18\x02 \x01(\v2\x13.spec.flatten.OuterR\x03out:\x06¨\x1d\x02\b\x01\"J\n" +
	"\aShallow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x03out\x18\x02 \x01(\v2\x13.spec.flatten.OuterR\x03out:\b¨\x1d\x04\b\x01P\x02\"K\n" +
	"\bNoneMode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x03out\x18\x02 \x01(\v2\x13.spec.flatten.OuterR\x03out:\b¨\x1d\x04\b\x01P\x03\"_\n" +
	"\x14NoneWithInlinedField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x03out\x18\x02 \x01(\v2\x13.spec.flatten.OuterB\x06¨\x1d\x02(\x01R\x03out:\b¨\x1d\x04\b\x01P\x03\"I\n" +
	"\fNestedInside\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12#\n" +
	"\x02in\x18\x02 \x01(\v2\x13.spec.flatten.InnerR\x02in:\x06¨\x1d\x02P\x03\"e\n" +
	"\x13DeepWithNestedField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x03out\x18\x02 \x01(\v2\x1a.spec.flatten.NestedInsideB\x06¨\x1d\x02(\x03R\x03out:\b¨\x1d\x04\b\x01P\x01\"`\n" +
	"\x15NestedKeyFlatInterior\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x03out\x18\x02 \x01(\v2\x13.spec.flatten.OuterB\x06¨\x1d\x02(\x03R\x03out:\b¨\x1d\x04\b\x01P\x01\"G\n" +
	"\n" +
	"FlatInside\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12#\n" +
	"\x02in\x18\x02 \x01(\v2\x13.spec.flatten.InnerR\x02in:\x06¨\x1d\x02P\x01\"d\n" +
	"\x14GroupedButFlatInside\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x03out\x18\x02 \x01(\v2\x18.spec.flatten.FlatInsideB\x06¨\x1d\x02(\x03R\x03out:\b¨\x1d\x04\b\x01P\x01\"\x92\x01\n" +
	"\x10SameTypeBothWays\x12:\n" +
	"\ainlined\x18\x01 \x01(\v2\x18.spec.flatten.FlatInsideB\x06¨\x1d\x02(\x01R\ainlined\x12:\n" +
	"\agrouped\x18\x02 \x01(\v2\x18.spec.flatten.FlatInsideB\x06¨\x1d\x02(\x03R\agrouped:\x06¨\x1d\x02\b\x01\"R\n" +
	"\x0fMaxDepthMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x03out\x18\x02 \x01(\v2\x13.spec.flatten.OuterR\x03out:\b¨\x1d\x04\b\x01h\x01\"\x16\n" +
	"\x06Level3\x12\f\n" +
	"\x01d\x18\x01 \x01(\tR\x01d\"<\n" +
	"\x06Level2\x12\f\n" +
	"\x01c\x18\x01 \x01(\tR\x01c\x12$\n" +
	"\x02l3\x18\x02 \x01(\v2\x14.spec.flatten.Level3R\x02l3\"<\n" +
	"\x06Level1\x12\f\n" +
	"\x01b\x18\x01 \x01(\tR\x01b\x12$\n" +
	"\x02l2\x18\x02 \x01(\v2\x14.spec.flatten.Level2R\x02l2\"S\n" +
	"\rMaxDepthField\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12,\n" +
	"\x02l1\x18\x02 \x01(\v2\x14.spec.flatten.Level1B\x06¨\x1d\x02H\x01R\x02l1:\x06¨\x1d\x02\b\x01\"L\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x05child\x18\x02 \x01(\v2\x12.spec.flatten.NodeR\x05child:\x06¨\x1d\x02P\x03\"A\n" +
	"\rRecursiveNone\x12&\n" +
	"\x04root\x18\x01 \x01(\v2\x12.spec.flatten.NodeR\x04root:\b¨\x1d\x04\b\x01P\x03\"L\n" +
	"\bDeepNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x05child\x18\x02 \x01(\v2\x16.spec.flatten.DeepNodeR\x05child\"N\n" +
	"\x10RecursiveBounded\x122\n" +
	"\x04root\x18\x01 \x01(\v2\x16.spec.flatten.DeepNodeB\x06¨\x1d\x02H\x02R\x04root:\x06¨\x1d\x02\b\x01\"\xd0\x01\n" +
	"\x12StopsAtCollections\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.spec.flatten.OuterR\x05items\x12>\n" +
	"\x04tags\x18\x03 \x03(\v2*.spec.flatten.StopsAtCollections.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x06¨\x1d\x02\b\x01BBZ@github.com/gopherex/protoc-gen-go-plainjson/example/spec/flattenb\x06proto3"

var (
	file_example_spec_flatten_flatten_proto_rawDescOnce sync.Once
	file_example_spec_flatten_flatten_proto_rawDescData []byte
)

func file_example_spec_flatten_flatten_proto_rawDescGZIP() []byte {
	file_example_spec_flatten_flatten_proto_rawDescOnce.Do(func() {
		file_example_spec_flatten_flatten_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_spec_flatten_flatten_proto_rawDesc), len(file_example_spec_flatten_flatten_proto_rawDesc)))
	})
	return file_example_spec_flatten_flatten_proto_rawDescData
}

var file_example_spec_flatten_flatten_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_example_spec_flatten_flatten_proto_goTypes = []any{
	(*Inner)(nil),                 // 0: spec.flatten.Inner
	(*Outer)(nil),                 // 1: spec.flatten.Outer
	(*DeepDefault)(nil),           // 2: spec.flatten.DeepDefault
	(*Shallow)(nil),               // 3: spec.flatten.Shallow
	(*NoneMode)(nil),              // 4: spec.flatten.NoneMode
	(*NoneWithInlinedField)(nil),  // 5: spec.flatten.NoneWithInlinedField
	(*NestedInside)(nil),          // 6: spec.flatten.NestedInside
	(*DeepWithNestedField)(nil),   // 7: spec.flatten.DeepWithNestedField
	(*NestedKeyFlatInterior)(nil), // 8: spec.flatten.NestedKeyFlatInterior
	(*FlatInside)(nil),            // 9: spec.flatten.FlatInside
	(*GroupedButFlatInside)(nil),  // 10: spec.flatten.GroupedButFlatInside
	(*SameTypeBothWays)(nil),      // 11: spec.flatten.SameTypeBothWays
	(*MaxDepthMessage)(nil),       // 12: spec.flatten.MaxDepthMessage
	(*Level3)(nil),                // 13: spec.flatten.Level3
	(*Level2)(nil),                // 14: spec.flatten.Level2
	(*Level1)(nil),                // 15: spec.flatten.Level1
	(*MaxDepthField)(nil),         // 16: spec.flatten.MaxDepthField
	(*Node)(nil),                  // 17: spec.flatten.Node
	(*RecursiveNone)(nil),         // 18: spec.flatten.RecursiveNone
	(*DeepNode)(nil),              // 19: spec.flatten.DeepNode
	(*RecursiveBounded)(nil),      // 20: spec.flatten.RecursiveBounded
	(*StopsAtCollections)(nil),    // 21: spec.flatten.StopsAtCollections
	nil,                           // 22: spec.flatten.StopsAtCollections.TagsEntry
}
var file_example_spec_flatten_flatten_proto_depIdxs = []int32{
	0,  // 0: spec.flatten.Outer.in:type_name -> spec.flatten.Inner
	1,  // 1: spec.flatten.DeepDefault.out:type_name -> spec.flatten.Outer
	1,  // 2: spec.flatten.Shallow.out:type_name -> spec.flatten.Outer
	1,  // 3: spec.flatten.NoneMode.out:type_name -> spec.flatten.Outer
	1,  // 4: spec.flatten.NoneWithInlinedField.out:type_name -> spec.flatten.Outer
	0,  // 5: spec.flatten.NestedInside.in:type_name -> spec.flatten.Inner
	6,  // 6: spec.flatten.DeepWithNestedField.out:type_name -> spec.flatten.NestedInside
	1,  // 7: spec.flatten.NestedKeyFlatInterior.out:type_name -> spec.flatten.Outer
	0,  // 8: spec.flatten.FlatInside.in:type_name -> spec.flatten.Inner
	9,  // 9: spec.flatten.GroupedButFlatInside.out:type_name -> spec.flatten.FlatInside
	9,  // 10: spec.flatten.SameTypeBothWays.inlined:type_name -> spec.flatten.FlatInside
	9,  // 11: spec.flatten.SameTypeBothWays.grouped:type_name -> spec.flatten.FlatInside
	1,  // 12: spec.flatten.MaxDepthMessage.out:type_name -> spec.flatten.Outer
	13, // 13: spec.flatten.Level2.l3:type_name -> spec.flatten.Level3
	14, // 14: spec.flatten.Level1.l2:type_name -> spec.flatten.Level2
	15, // 15: spec.flatten.MaxDepthField.l1:type_name -> spec.flatten.Level1
	17, // 16: spec.flatten.Node.child:type_name -> spec.flatten.Node
	17, // 17: spec.flatten.RecursiveNone.root:type_name -> spec.flatten.Node
	19, // 18: spec.flatten.DeepNode.child:type_name -> spec.flatten.DeepNode
	19, // 19: spec.flatten.RecursiveBounded.root:type_name -> spec.flatten.DeepNode
	1,  // 20: spec.flatten.StopsAtCollections.items:type_name -> spec.flatten.Outer
	22, // 21: spec.flatten.StopsAtCollections.tags:type_name -> spec.flatten.StopsAtCollections.TagsEntry
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_example_spec_flatten_flatten_proto_init() }
func file_example_spec_flatten_flatten_proto_init() {
	if File_example_spec_flatten_flatten_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_spec_flatten_flatten_proto_rawDesc), len(file_example_spec_flatten_flatten_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_spec_flatten_flatten_proto_goTypes,
		DependencyIndexes: file_example_spec_flatten_flatten_proto_depIdxs,
		MessageInfos:      file_example_spec_flatten_flatten_proto_msgTypes,
	}.Build()
	File_example_spec_flatten_flatten_proto = out.File
	file_example_spec_flatten_flatten_proto_goTypes = nil
	file_example_spec_flatten_flatten_proto_depIdxs = nil
}
