// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: golden/golden.proto

package golden

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Top-level enum. Proto3 requires the first value to be zero (default).
type TopLevelEnum int32

const (
	TopLevelEnum_TOP_LEVEL_ENUM_UNSPECIFIED TopLevelEnum = 0
	TopLevelEnum_TOP_LEVEL_ENUM_FIRST       TopLevelEnum = 1
	TopLevelEnum_TOP_LEVEL_ENUM_SECOND      TopLevelEnum = 2
	TopLevelEnum_TOP_LEVEL_ENUM_NEGATIVE    TopLevelEnum = -1 // negative enum value
)

// Enum value maps for TopLevelEnum.
var (
	TopLevelEnum_name = map[int32]string{
		0:  "TOP_LEVEL_ENUM_UNSPECIFIED",
		1:  "TOP_LEVEL_ENUM_FIRST",
		2:  "TOP_LEVEL_ENUM_SECOND",
		-1: "TOP_LEVEL_ENUM_NEGATIVE",
	}
	TopLevelEnum_value = map[string]int32{
		"TOP_LEVEL_ENUM_UNSPECIFIED": 0,
		"TOP_LEVEL_ENUM_FIRST":       1,
		"TOP_LEVEL_ENUM_SECOND":      2,
		"TOP_LEVEL_ENUM_NEGATIVE":    -1,
	}
)

func (x TopLevelEnum) Enum() *TopLevelEnum {
	p := new(TopLevelEnum)
	*p = x
	return p
}

func (x TopLevelEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopLevelEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_golden_golden_proto_enumTypes[0].Descriptor()
}

func (TopLevelEnum) Type() protoreflect.EnumType {
	return &file_golden_golden_proto_enumTypes[0]
}

func (x TopLevelEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopLevelEnum.Descriptor instead.
func (TopLevelEnum) EnumDescriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{0}
}

// Enum with allow_alias: multiple names map to the same number.
type AliasedEnum int32

const (
	AliasedEnum_ALIASED_ENUM_UNSPECIFIED AliasedEnum = 0
	AliasedEnum_ALIASED_ENUM_RUNNING     AliasedEnum = 1
	AliasedEnum_ALIASED_ENUM_STARTED     AliasedEnum = 1 // alias of RUNNING
)

// Enum value maps for AliasedEnum.
var (
	AliasedEnum_name = map[int32]string{
		0: "ALIASED_ENUM_UNSPECIFIED",
		1: "ALIASED_ENUM_RUNNING",
		// Duplicate value: 1: "ALIASED_ENUM_STARTED",
	}
	AliasedEnum_value = map[string]int32{
		"ALIASED_ENUM_UNSPECIFIED": 0,
		"ALIASED_ENUM_RUNNING":     1,
		"ALIASED_ENUM_STARTED":     1,
	}
)

func (x AliasedEnum) Enum() *AliasedEnum {
	p := new(AliasedEnum)
	*p = x
	return p
}

func (x AliasedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AliasedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_golden_golden_proto_enumTypes[1].Descriptor()
}

func (AliasedEnum) Type() protoreflect.EnumType {
	return &file_golden_golden_proto_enumTypes[1]
}

func (x AliasedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AliasedEnum.Descriptor instead.
func (AliasedEnum) EnumDescriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{1}
}

// Nested enum type.
type Outer_NestedEnum int32

const (
	Outer_NESTED_ENUM_UNSPECIFIED Outer_NestedEnum = 0
	Outer_NESTED_ENUM_A           Outer_NestedEnum = 1
	Outer_NESTED_ENUM_B           Outer_NestedEnum = 2
)

// Enum value maps for Outer_NestedEnum.
var (
	Outer_NestedEnum_name = map[int32]string{
		0: "NESTED_ENUM_UNSPECIFIED",
		1: "NESTED_ENUM_A",
		2: "NESTED_ENUM_B",
	}
	Outer_NestedEnum_value = map[string]int32{
		"NESTED_ENUM_UNSPECIFIED": 0,
		"NESTED_ENUM_A":           1,
		"NESTED_ENUM_B":           2,
	}
)

func (x Outer_NestedEnum) Enum() *Outer_NestedEnum {
	p := new(Outer_NestedEnum)
	*p = x
	return p
}

func (x Outer_NestedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outer_NestedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_golden_golden_proto_enumTypes[2].Descriptor()
}

func (Outer_NestedEnum) Type() protoreflect.EnumType {
	return &file_golden_golden_proto_enumTypes[2]
}

func (x Outer_NestedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outer_NestedEnum.Descriptor instead.
func (Outer_NestedEnum) EnumDescriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{3, 0}
}

type ScalarTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldDouble   float64                `protobuf:"fixed64,1,opt,name=field_double,json=fieldDouble,proto3" json:"field_double,omitempty"`
	FieldFloat    float32                `protobuf:"fixed32,2,opt,name=field_float,json=fieldFloat,proto3" json:"field_float,omitempty"`
	FieldInt32    int32                  `protobuf:"varint,3,opt,name=field_int32,json=fieldInt32,proto3" json:"field_int32,omitempty"`
	FieldInt64    int64                  `protobuf:"varint,4,opt,name=field_int64,json=fieldInt64,proto3" json:"field_int64,omitempty"`
	FieldUint32   uint32                 `protobuf:"varint,5,opt,name=field_uint32,json=fieldUint32,proto3" json:"field_uint32,omitempty"`
	FieldUint64   uint64                 `protobuf:"varint,6,opt,name=field_uint64,json=fieldUint64,proto3" json:"field_uint64,omitempty"`
	FieldSint32   int32                  `protobuf:"zigzag32,7,opt,name=field_sint32,json=fieldSint32,proto3" json:"field_sint32,omitempty"`
	FieldSint64   int64                  `protobuf:"zigzag64,8,opt,name=field_sint64,json=fieldSint64,proto3" json:"field_sint64,omitempty"`
	FieldFixed32  uint32                 `protobuf:"fixed32,9,opt,name=field_fixed32,json=fieldFixed32,proto3" json:"field_fixed32,omitempty"`
	FieldFixed64  uint64                 `protobuf:"fixed64,10,opt,name=field_fixed64,json=fieldFixed64,proto3" json:"field_fixed64,omitempty"`
	FieldSfixed32 int32                  `protobuf:"fixed32,11,opt,name=field_sfixed32,json=fieldSfixed32,proto3" json:"field_sfixed32,omitempty"`
	FieldSfixed64 int64                  `protobuf:"fixed64,12,opt,name=field_sfixed64,json=fieldSfixed64,proto3" json:"field_sfixed64,omitempty"`
	FieldBool     bool                   `protobuf:"varint,13,opt,name=field_bool,json=fieldBool,proto3" json:"field_bool,omitempty"`
	FieldString   string                 `protobuf:"bytes,14,opt,name=field_string,json=fieldString,proto3" json:"field_string,omitempty"`
	FieldBytes    []byte                 `protobuf:"bytes,15,opt,name=field_bytes,json=fieldBytes,proto3" json:"field_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarTypes) Reset() {
	*x = ScalarTypes{}
	mi := &file_golden_golden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarTypes) ProtoMessage() {}

func (x *ScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarTypes.ProtoReflect.Descriptor instead.
func (*ScalarTypes) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{0}
}

func (x *ScalarTypes) GetFieldDouble() float64 {
	if x != nil {
		return x.FieldDouble
	}
	return 0
}

func (x *ScalarTypes) GetFieldFloat() float32 {
	if x != nil {
		return x.FieldFloat
	}
	return 0
}

func (x *ScalarTypes) GetFieldInt32() int32 {
	if x != nil {
		return x.FieldInt32
	}
	return 0
}

func (x *ScalarTypes) GetFieldInt64() int64 {
	if x != nil {
		return x.FieldInt64
	}
	return 0
}

func (x *ScalarTypes) GetFieldUint32() uint32 {
	if x != nil {
		return x.FieldUint32
	}
	return 0
}

func (x *ScalarTypes) GetFieldUint64() uint64 {
	if x != nil {
		return x.FieldUint64
	}
	return 0
}

func (x *ScalarTypes) GetFieldSint32() int32 {
	if x != nil {
		return x.FieldSint32
	}
	return 0
}

func (x *ScalarTypes) GetFieldSint64() int64 {
	if x != nil {
		return x.FieldSint64
	}
	return 0
}

func (x *ScalarTypes) GetFieldFixed32() uint32 {
	if x != nil {
		return x.FieldFixed32
	}
	return 0
}

func (x *ScalarTypes) GetFieldFixed64() uint64 {
	if x != nil {
		return x.FieldFixed64
	}
	return 0
}

func (x *ScalarTypes) GetFieldSfixed32() int32 {
	if x != nil {
		return x.FieldSfixed32
	}
	return 0
}

func (x *ScalarTypes) GetFieldSfixed64() int64 {
	if x != nil {
		return x.FieldSfixed64
	}
	return 0
}

func (x *ScalarTypes) GetFieldBool() bool {
	if x != nil {
		return x.FieldBool
	}
	return false
}

func (x *ScalarTypes) GetFieldString() string {
	if x != nil {
		return x.FieldString
	}
	return ""
}

func (x *ScalarTypes) GetFieldBytes() []byte {
	if x != nil {
		return x.FieldBytes
	}
	return nil
}

// Every scalar type with proto3 explicit presence (optional).
type OptionalScalarTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldDouble   *float64               `protobuf:"fixed64,1,opt,name=field_double,json=fieldDouble,proto3,oneof" json:"field_double,omitempty"`
	FieldFloat    *float32               `protobuf:"fixed32,2,opt,name=field_float,json=fieldFloat,proto3,oneof" json:"field_float,omitempty"`
	FieldInt32    *int32                 `protobuf:"varint,3,opt,name=field_int32,json=fieldInt32,proto3,oneof" json:"field_int32,omitempty"`
	FieldInt64    *int64                 `protobuf:"varint,4,opt,name=field_int64,json=fieldInt64,proto3,oneof" json:"field_int64,omitempty"`
	FieldUint32   *uint32                `protobuf:"varint,5,opt,name=field_uint32,json=fieldUint32,proto3,oneof" json:"field_uint32,omitempty"`
	FieldUint64   *uint64                `protobuf:"varint,6,opt,name=field_uint64,json=fieldUint64,proto3,oneof" json:"field_uint64,omitempty"`
	FieldSint32   *int32                 `protobuf:"zigzag32,7,opt,name=field_sint32,json=fieldSint32,proto3,oneof" json:"field_sint32,omitempty"`
	FieldSint64   *int64                 `protobuf:"zigzag64,8,opt,name=field_sint64,json=fieldSint64,proto3,oneof" json:"field_sint64,omitempty"`
	FieldFixed32  *uint32                `protobuf:"fixed32,9,opt,name=field_fixed32,json=fieldFixed32,proto3,oneof" json:"field_fixed32,omitempty"`
	FieldFixed64  *uint64                `protobuf:"fixed64,10,opt,name=field_fixed64,json=fieldFixed64,proto3,oneof" json:"field_fixed64,omitempty"`
	FieldSfixed32 *int32                 `protobuf:"fixed32,11,opt,name=field_sfixed32,json=fieldSfixed32,proto3,oneof" json:"field_sfixed32,omitempty"`
	FieldSfixed64 *int64                 `protobuf:"fixed64,12,opt,name=field_sfixed64,json=fieldSfixed64,proto3,oneof" json:"field_sfixed64,omitempty"`
	FieldBool     *bool                  `protobuf:"varint,13,opt,name=field_bool,json=fieldBool,proto3,oneof" json:"field_bool,omitempty"`
	FieldString   *string                `protobuf:"bytes,14,opt,name=field_string,json=fieldString,proto3,oneof" json:"field_string,omitempty"`
	FieldBytes    []byte                 `protobuf:"bytes,15,opt,name=field_bytes,json=fieldBytes,proto3,oneof" json:"field_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalScalarTypes) Reset() {
	*x = OptionalScalarTypes{}
	mi := &file_golden_golden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalScalarTypes) ProtoMessage() {}

func (x *OptionalScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalScalarTypes.ProtoReflect.Descriptor instead.
func (*OptionalScalarTypes) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{1}
}

func (x *OptionalScalarTypes) GetFieldDouble() float64 {
	if x != nil && x.FieldDouble != nil {
		return *x.FieldDouble
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldFloat() float32 {
	if x != nil && x.FieldFloat != nil {
		return *x.FieldFloat
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldInt32() int32 {
	if x != nil && x.FieldInt32 != nil {
		return *x.FieldInt32
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldInt64() int64 {
	if x != nil && x.FieldInt64 != nil {
		return *x.FieldInt64
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldUint32() uint32 {
	if x != nil && x.FieldUint32 != nil {
		return *x.FieldUint32
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldUint64() uint64 {
	if x != nil && x.FieldUint64 != nil {
		return *x.FieldUint64
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldSint32() int32 {
	if x != nil && x.FieldSint32 != nil {
		return *x.FieldSint32
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldSint64() int64 {
	if x != nil && x.FieldSint64 != nil {
		return *x.FieldSint64
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldFixed32() uint32 {
	if x != nil && x.FieldFixed32 != nil {
		return *x.FieldFixed32
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldFixed64() uint64 {
	if x != nil && x.FieldFixed64 != nil {
		return *x.FieldFixed64
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldSfixed32() int32 {
	if x != nil && x.FieldSfixed32 != nil {
		return *x.FieldSfixed32
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldSfixed64() int64 {
	if x != nil && x.FieldSfixed64 != nil {
		return *x.FieldSfixed64
	}
	return 0
}

func (x *OptionalScalarTypes) GetFieldBool() bool {
	if x != nil && x.FieldBool != nil {
		return *x.FieldBool
	}
	return false
}

func (x *OptionalScalarTypes) GetFieldString() string {
	if x != nil && x.FieldString != nil {
		return *x.FieldString
	}
	return ""
}

func (x *OptionalScalarTypes) GetFieldBytes() []byte {
	if x != nil {
		return x.FieldBytes
	}
	return nil
}

// Every scalar type repeated (packed where applicable).
type RepeatedScalarTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldDouble   []float64              `protobuf:"fixed64,1,rep,packed,name=field_double,json=fieldDouble,proto3" json:"field_double,omitempty"`
	FieldFloat    []float32              `protobuf:"fixed32,2,rep,packed,name=field_float,json=fieldFloat,proto3" json:"field_float,omitempty"`
	FieldInt32    []int32                `protobuf:"varint,3,rep,packed,name=field_int32,json=fieldInt32,proto3" json:"field_int32,omitempty"`
	FieldInt64    []int64                `protobuf:"varint,4,rep,packed,name=field_int64,json=fieldInt64,proto3" json:"field_int64,omitempty"`
	FieldUint32   []uint32               `protobuf:"varint,5,rep,packed,name=field_uint32,json=fieldUint32,proto3" json:"field_uint32,omitempty"`
	FieldUint64   []uint64               `protobuf:"varint,6,rep,packed,name=field_uint64,json=fieldUint64,proto3" json:"field_uint64,omitempty"`
	FieldSint32   []int32                `protobuf:"zigzag32,7,rep,packed,name=field_sint32,json=fieldSint32,proto3" json:"field_sint32,omitempty"`
	FieldSint64   []int64                `protobuf:"zigzag64,8,rep,packed,name=field_sint64,json=fieldSint64,proto3" json:"field_sint64,omitempty"`
	FieldFixed32  []uint32               `protobuf:"fixed32,9,rep,packed,name=field_fixed32,json=fieldFixed32,proto3" json:"field_fixed32,omitempty"`
	FieldFixed64  []uint64               `protobuf:"fixed64,10,rep,packed,name=field_fixed64,json=fieldFixed64,proto3" json:"field_fixed64,omitempty"`
	FieldSfixed32 []int32                `protobuf:"fixed32,11,rep,packed,name=field_sfixed32,json=fieldSfixed32,proto3" json:"field_sfixed32,omitempty"`
	FieldSfixed64 []int64                `protobuf:"fixed64,12,rep,packed,name=field_sfixed64,json=fieldSfixed64,proto3" json:"field_sfixed64,omitempty"`
	FieldBool     []bool                 `protobuf:"varint,13,rep,packed,name=field_bool,json=fieldBool,proto3" json:"field_bool,omitempty"`
	FieldString   []string               `protobuf:"bytes,14,rep,name=field_string,json=fieldString,proto3" json:"field_string,omitempty"`
	FieldBytes    [][]byte               `protobuf:"bytes,15,rep,name=field_bytes,json=fieldBytes,proto3" json:"field_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedScalarTypes) Reset() {
	*x = RepeatedScalarTypes{}
	mi := &file_golden_golden_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedScalarTypes) ProtoMessage() {}

func (x *RepeatedScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedScalarTypes.ProtoReflect.Descriptor instead.
func (*RepeatedScalarTypes) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedScalarTypes) GetFieldDouble() []float64 {
	if x != nil {
		return x.FieldDouble
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldFloat() []float32 {
	if x != nil {
		return x.FieldFloat
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldInt32() []int32 {
	if x != nil {
		return x.FieldInt32
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldInt64() []int64 {
	if x != nil {
		return x.FieldInt64
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldUint32() []uint32 {
	if x != nil {
		return x.FieldUint32
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldUint64() []uint64 {
	if x != nil {
		return x.FieldUint64
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldSint32() []int32 {
	if x != nil {
		return x.FieldSint32
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldSint64() []int64 {
	if x != nil {
		return x.FieldSint64
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldFixed32() []uint32 {
	if x != nil {
		return x.FieldFixed32
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldFixed64() []uint64 {
	if x != nil {
		return x.FieldFixed64
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldSfixed32() []int32 {
	if x != nil {
		return x.FieldSfixed32
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldSfixed64() []int64 {
	if x != nil {
		return x.FieldSfixed64
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldBool() []bool {
	if x != nil {
		return x.FieldBool
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldString() []string {
	if x != nil {
		return x.FieldString
	}
	return nil
}

func (x *RepeatedScalarTypes) GetFieldBytes() [][]byte {
	if x != nil {
		return x.FieldBytes
	}
	return nil
}

type Outer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *Outer_Inner           `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	EnumField     Outer_NestedEnum       `protobuf:"varint,2,opt,name=enum_field,json=enumField,proto3,enum=golden.Outer_NestedEnum" json:"enum_field,omitempty"`
	DeepInner     *Outer_Inner_DeepInner `protobuf:"bytes,3,opt,name=deep_inner,json=deepInner,proto3" json:"deep_inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_golden_golden_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{3}
}

func (x *Outer) GetInner() *Outer_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *Outer) GetEnumField() Outer_NestedEnum {
	if x != nil {
		return x.EnumField
	}
	return Outer_NESTED_ENUM_UNSPECIFIED
}

func (x *Outer) GetDeepInner() *Outer_Inner_DeepInner {
	if x != nil {
		return x.DeepInner
	}
	return nil
}

type EnumAndMessageFields struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SingularEnum    TopLevelEnum           `protobuf:"varint,1,opt,name=singular_enum,json=singularEnum,proto3,enum=golden.TopLevelEnum" json:"singular_enum,omitempty"`
	OptionalEnum    *TopLevelEnum          `protobuf:"varint,2,opt,name=optional_enum,json=optionalEnum,proto3,enum=golden.TopLevelEnum,oneof" json:"optional_enum,omitempty"`
	RepeatedEnum    []TopLevelEnum         `protobuf:"varint,3,rep,packed,name=repeated_enum,json=repeatedEnum,proto3,enum=golden.TopLevelEnum" json:"repeated_enum,omitempty"`
	SingularMessage *ScalarTypes           `protobuf:"bytes,4,opt,name=singular_message,json=singularMessage,proto3" json:"singular_message,omitempty"`
	OptionalMessage *ScalarTypes           `protobuf:"bytes,5,opt,name=optional_message,json=optionalMessage,proto3,oneof" json:"optional_message,omitempty"`
	RepeatedMessage []*ScalarTypes         `protobuf:"bytes,6,rep,name=repeated_message,json=repeatedMessage,proto3" json:"repeated_message,omitempty"`
	NestedEnum      Outer_NestedEnum       `protobuf:"varint,7,opt,name=nested_enum,json=nestedEnum,proto3,enum=golden.Outer_NestedEnum" json:"nested_enum,omitempty"`
	NestedMessage   *Outer_Inner           `protobuf:"bytes,8,opt,name=nested_message,json=nestedMessage,proto3" json:"nested_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnumAndMessageFields) Reset() {
	*x = EnumAndMessageFields{}
	mi := &file_golden_golden_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumAndMessageFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumAndMessageFields) ProtoMessage() {}

func (x *EnumAndMessageFields) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumAndMessageFields.ProtoReflect.Descriptor instead.
func (*EnumAndMessageFields) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{4}
}

func (x *EnumAndMessageFields) GetSingularEnum() TopLevelEnum {
	if x != nil {
		return x.SingularEnum
	}
	return TopLevelEnum_TOP_LEVEL_ENUM_UNSPECIFIED
}

func (x *EnumAndMessageFields) GetOptionalEnum() TopLevelEnum {
	if x != nil && x.OptionalEnum != nil {
		return *x.OptionalEnum
	}
	return TopLevelEnum_TOP_LEVEL_ENUM_UNSPECIFIED
}

func (x *EnumAndMessageFields) GetRepeatedEnum() []TopLevelEnum {
	if x != nil {
		return x.RepeatedEnum
	}
	return nil
}

func (x *EnumAndMessageFields) GetSingularMessage() *ScalarTypes {
	if x != nil {
		return x.SingularMessage
	}
	return nil
}

func (x *EnumAndMessageFields) GetOptionalMessage() *ScalarTypes {
	if x != nil {
		return x.OptionalMessage
	}
	return nil
}

func (x *EnumAndMessageFields) GetRepeatedMessage() []*ScalarTypes {
	if x != nil {
		return x.RepeatedMessage
	}
	return nil
}

func (x *EnumAndMessageFields) GetNestedEnum() Outer_NestedEnum {
	if x != nil {
		return x.NestedEnum
	}
	return Outer_NESTED_ENUM_UNSPECIFIED
}

func (x *EnumAndMessageFields) GetNestedMessage() *Outer_Inner {
	if x != nil {
		return x.NestedMessage
	}
	return nil
}

type MapKeyTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32Key      map[int32]string       `protobuf:"bytes,1,rep,name=int32_key,json=int32Key,proto3" json:"int32_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Int64Key      map[int64]string       `protobuf:"bytes,2,rep,name=int64_key,json=int64Key,proto3" json:"int64_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uint32Key     map[uint32]string      `protobuf:"bytes,3,rep,name=uint32_key,json=uint32Key,proto3" json:"uint32_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Uint64Key     map[uint64]string      `protobuf:"bytes,4,rep,name=uint64_key,json=uint64Key,proto3" json:"uint64_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sint32Key     map[int32]string       `protobuf:"bytes,5,rep,name=sint32_key,json=sint32Key,proto3" json:"sint32_key,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sint64Key     map[int64]string       `protobuf:"bytes,6,rep,name=sint64_key,json=sint64Key,proto3" json:"sint64_key,omitempty" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fixed32Key    map[uint32]string      `protobuf:"bytes,7,rep,name=fixed32_key,json=fixed32Key,proto3" json:"fixed32_key,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fixed64Key    map[uint64]string      `protobuf:"bytes,8,rep,name=fixed64_key,json=fixed64Key,proto3" json:"fixed64_key,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sfixed32Key   map[int32]string       `protobuf:"bytes,9,rep,name=sfixed32_key,json=sfixed32Key,proto3" json:"sfixed32_key,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sfixed64Key   map[int64]string       `protobuf:"bytes,10,rep,name=sfixed64_key,json=sfixed64Key,proto3" json:"sfixed64_key,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BoolKey       map[bool]string        `protobuf:"bytes,11,rep,name=bool_key,json=boolKey,proto3" json:"bool_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringKey     map[string]string      `protobuf:"bytes,12,rep,name=string_key,json=stringKey,proto3" json:"string_key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapKeyTypes) Reset() {
	*x = MapKeyTypes{}
	mi := &file_golden_golden_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapKeyTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapKeyTypes) ProtoMessage() {}

func (x *MapKeyTypes) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapKeyTypes.ProtoReflect.Descriptor instead.
func (*MapKeyTypes) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{5}
}

func (x *MapKeyTypes) GetInt32Key() map[int32]string {
	if x != nil {
		return x.Int32Key
	}
	return nil
}

func (x *MapKeyTypes) GetInt64Key() map[int64]string {
	if x != nil {
		return x.Int64Key
	}
	return nil
}

func (x *MapKeyTypes) GetUint32Key() map[uint32]string {
	if x != nil {
		return x.Uint32Key
	}
	return nil
}

func (x *MapKeyTypes) GetUint64Key() map[uint64]string {
	if x != nil {
		return x.Uint64Key
	}
	return nil
}

func (x *MapKeyTypes) GetSint32Key() map[int32]string {
	if x != nil {
		return x.Sint32Key
	}
	return nil
}

func (x *MapKeyTypes) GetSint64Key() map[int64]string {
	if x != nil {
		return x.Sint64Key
	}
	return nil
}

func (x *MapKeyTypes) GetFixed32Key() map[uint32]string {
	if x != nil {
		return x.Fixed32Key
	}
	return nil
}

func (x *MapKeyTypes) GetFixed64Key() map[uint64]string {
	if x != nil {
		return x.Fixed64Key
	}
	return nil
}

func (x *MapKeyTypes) GetSfixed32Key() map[int32]string {
	if x != nil {
		return x.Sfixed32Key
	}
	return nil
}

func (x *MapKeyTypes) GetSfixed64Key() map[int64]string {
	if x != nil {
		return x.Sfixed64Key
	}
	return nil
}

func (x *MapKeyTypes) GetBoolKey() map[bool]string {
	if x != nil {
		return x.BoolKey
	}
	return nil
}

func (x *MapKeyTypes) GetStringKey() map[string]string {
	if x != nil {
		return x.StringKey
	}
	return nil
}

type MapValueTypes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	DoubleValue   map[string]float64      `protobuf:"bytes,1,rep,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	FloatValue    map[string]float32      `protobuf:"bytes,2,rep,name=float_value,json=floatValue,proto3" json:"float_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Int32Value    map[string]int32        `protobuf:"bytes,3,rep,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Int64Value    map[string]int64        `protobuf:"bytes,4,rep,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Uint32Value   map[string]uint32       `protobuf:"bytes,5,rep,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Uint64Value   map[string]uint64       `protobuf:"bytes,6,rep,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BoolValue     map[string]bool         `protobuf:"bytes,7,rep,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringValue   map[string]string       `protobuf:"bytes,8,rep,name=string_value,json=stringValue,proto3" json:"string_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BytesValue    map[string][]byte       `protobuf:"bytes,9,rep,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnumValue     map[string]TopLevelEnum `protobuf:"bytes,10,rep,name=enum_value,json=enumValue,proto3" json:"enum_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=golden.TopLevelEnum"`
	MessageValue  map[string]*ScalarTypes `protobuf:"bytes,11,rep,name=message_value,json=messageValue,proto3" json:"message_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValueTypes) Reset() {
	*x = MapValueTypes{}
	mi := &file_golden_golden_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValueTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValueTypes) ProtoMessage() {}

func (x *MapValueTypes) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValueTypes.ProtoReflect.Descriptor instead.
func (*MapValueTypes) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{6}
}

func (x *MapValueTypes) GetDoubleValue() map[string]float64 {
	if x != nil {
		return x.DoubleValue
	}
	return nil
}

func (x *MapValueTypes) GetFloatValue() map[string]float32 {
	if x != nil {
		return x.FloatValue
	}
	return nil
}

func (x *MapValueTypes) GetInt32Value() map[string]int32 {
	if x != nil {
		return x.Int32Value
	}
	return nil
}

func (x *MapValueTypes) GetInt64Value() map[string]int64 {
	if x != nil {
		return x.Int64Value
	}
	return nil
}

func (x *MapValueTypes) GetUint32Value() map[string]uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return nil
}

func (x *MapValueTypes) GetUint64Value() map[string]uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return nil
}

func (x *MapValueTypes) GetBoolValue() map[string]bool {
	if x != nil {
		return x.BoolValue
	}
	return nil
}

func (x *MapValueTypes) GetStringValue() map[string]string {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *MapValueTypes) GetBytesValue() map[string][]byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *MapValueTypes) GetEnumValue() map[string]TopLevelEnum {
	if x != nil {
		return x.EnumValue
	}
	return nil
}

func (x *MapValueTypes) GetMessageValue() map[string]*ScalarTypes {
	if x != nil {
		return x.MessageValue
	}
	return nil
}

type OneofContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oneof mixing scalar, enum and message members.
	//
	// Types that are valid to be assigned to Choice:
	//
	//	*OneofContainer_ChoiceDouble
	//	*OneofContainer_ChoiceInt32
	//	*OneofContainer_ChoiceBool
	//	*OneofContainer_ChoiceString
	//	*OneofContainer_ChoiceBytes
	//	*OneofContainer_ChoiceEnum
	//	*OneofContainer_ChoiceMessage
	Choice isOneofContainer_Choice `protobuf_oneof:"choice"`
	// A second, independent oneof in the same message.
	//
	// Types that are valid to be assigned to Other:
	//
	//	*OneofContainer_OtherA
	//	*OneofContainer_OtherB
	Other isOneofContainer_Other `protobuf_oneof:"other"`
	// Regular field alongside oneofs.
	OutsideOneof  string `protobuf:"bytes,10,opt,name=outside_oneof,json=outsideOneof,proto3" json:"outside_oneof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofContainer) Reset() {
	*x = OneofContainer{}
	mi := &file_golden_golden_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofContainer) ProtoMessage() {}

func (x *OneofContainer) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofContainer.ProtoReflect.Descriptor instead.
func (*OneofContainer) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{7}
}

func (x *OneofContainer) GetChoice() isOneofContainer_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *OneofContainer) GetChoiceDouble() float64 {
	if x != nil {
		if x, ok := x.Choice.(*OneofContainer_ChoiceDouble); ok {
			return x.ChoiceDouble
		}
	}
	return 0
}

func (x *OneofContainer) GetChoiceInt32() int32 {
	if x != nil {
		if x, ok := x.Choice.(*OneofContainer_ChoiceInt32); ok {
			return x.ChoiceInt32
		}
	}
	return 0
}

func (x *OneofContainer) GetChoiceBool() bool {
	if x != nil {
		if x, ok := x.Choice.(*OneofContainer_ChoiceBool); ok {
			return x.ChoiceBool
		}
	}
	return false
}

func (x *OneofContainer) GetChoiceString() string {
	if x != nil {
		if x, ok := x.Choice.(*OneofContainer_ChoiceString); ok {
			return x.ChoiceString
		}
	}
	return ""
}

func (x *OneofContainer) GetChoiceBytes() []byte {
	if x != nil {
		if x, ok := x.Choice.(*OneofContainer_ChoiceBytes); ok {
			return x.ChoiceBytes
		}
	}
	return nil
}

func (x *OneofContainer) GetChoiceEnum() TopLevelEnum {
	if x != nil {
		if x, ok := x.Choice.(*OneofContainer_ChoiceEnum); ok {
			return x.ChoiceEnum
		}
	}
	return TopLevelEnum_TOP_LEVEL_ENUM_UNSPECIFIED
}

func (x *OneofContainer) GetChoiceMessage() *ScalarTypes {
	if x != nil {
		if x, ok := x.Choice.(*OneofContainer_ChoiceMessage); ok {
			return x.ChoiceMessage
		}
	}
	return nil
}

func (x *OneofContainer) GetOther() isOneofContainer_Other {
	if x != nil {
		return x.Other
	}
	return nil
}

func (x *OneofContainer) GetOtherA() string {
	if x != nil {
		if x, ok := x.Other.(*OneofContainer_OtherA); ok {
			return x.OtherA
		}
	}
	return ""
}

func (x *OneofContainer) GetOtherB() int64 {
	if x != nil {
		if x, ok := x.Other.(*OneofContainer_OtherB); ok {
			return x.OtherB
		}
	}
	return 0
}

func (x *OneofContainer) GetOutsideOneof() string {
	if x != nil {
		return x.OutsideOneof
	}
	return ""
}

type isOneofContainer_Choice interface {
	isOneofContainer_Choice()
}

type OneofContainer_ChoiceDouble struct {
	ChoiceDouble float64 `protobuf:"fixed64,1,opt,name=choice_double,json=choiceDouble,proto3,oneof"`
}

type OneofContainer_ChoiceInt32 struct {
	ChoiceInt32 int32 `protobuf:"varint,2,opt,name=choice_int32,json=choiceInt32,proto3,oneof"`
}

type OneofContainer_ChoiceBool struct {
	ChoiceBool bool `protobuf:"varint,3,opt,name=choice_bool,json=choiceBool,proto3,oneof"`
}

type OneofContainer_ChoiceString struct {
	ChoiceString string `protobuf:"bytes,4,opt,name=choice_string,json=choiceString,proto3,oneof"`
}

type OneofContainer_ChoiceBytes struct {
	ChoiceBytes []byte `protobuf:"bytes,5,opt,name=choice_bytes,json=choiceBytes,proto3,oneof"`
}

type OneofContainer_ChoiceEnum struct {
	ChoiceEnum TopLevelEnum `protobuf:"varint,6,opt,name=choice_enum,json=choiceEnum,proto3,enum=golden.TopLevelEnum,oneof"`
}

type OneofContainer_ChoiceMessage struct {
	ChoiceMessage *ScalarTypes `protobuf:"bytes,7,opt,name=choice_message,json=choiceMessage,proto3,oneof"`
}

func (*OneofContainer_ChoiceDouble) isOneofContainer_Choice() {}

func (*OneofContainer_ChoiceInt32) isOneofContainer_Choice() {}

func (*OneofContainer_ChoiceBool) isOneofContainer_Choice() {}

func (*OneofContainer_ChoiceString) isOneofContainer_Choice() {}

func (*OneofContainer_ChoiceBytes) isOneofContainer_Choice() {}

func (*OneofContainer_ChoiceEnum) isOneofContainer_Choice() {}

func (*OneofContainer_ChoiceMessage) isOneofContainer_Choice() {}

type isOneofContainer_Other interface {
	isOneofContainer_Other()
}

type OneofContainer_OtherA struct {
	OtherA string `protobuf:"bytes,8,opt,name=other_a,json=otherA,proto3,oneof"`
}

type OneofContainer_OtherB struct {
	OtherB int64 `protobuf:"varint,9,opt,name=other_b,json=otherB,proto3,oneof"`
}

func (*OneofContainer_OtherA) isOneofContainer_Other() {}

func (*OneofContainer_OtherB) isOneofContainer_Other() {}

type WellKnownTypes struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration  *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Any       *anypb.Any             `protobuf:"bytes,3,opt,name=any,proto3" json:"any,omitempty"`
	Empty     *emptypb.Empty         `protobuf:"bytes,4,opt,name=empty,proto3" json:"empty,omitempty"`
	FieldMask *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Struct    *structpb.Struct       `protobuf:"bytes,6,opt,name=struct,proto3" json:"struct,omitempty"`
	Value     *structpb.Value        `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	ListValue *structpb.ListValue    `protobuf:"bytes,8,opt,name=list_value,json=listValue,proto3" json:"list_value,omitempty"`
	// Wrapper types (nullable scalars).
	DoubleWrapper     *wrapperspb.DoubleValue         `protobuf:"bytes,9,opt,name=double_wrapper,json=doubleWrapper,proto3" json:"double_wrapper,omitempty"`
	FloatWrapper      *wrapperspb.FloatValue          `protobuf:"bytes,10,opt,name=float_wrapper,json=floatWrapper,proto3" json:"float_wrapper,omitempty"`
	Int32Wrapper      *wrapperspb.Int32Value          `protobuf:"bytes,11,opt,name=int32_wrapper,json=int32Wrapper,proto3" json:"int32_wrapper,omitempty"`
	Int64Wrapper      *wrapperspb.Int64Value          `protobuf:"bytes,12,opt,name=int64_wrapper,json=int64Wrapper,proto3" json:"int64_wrapper,omitempty"`
	Uint32Wrapper     *wrapperspb.UInt32Value         `protobuf:"bytes,13,opt,name=uint32_wrapper,json=uint32Wrapper,proto3" json:"uint32_wrapper,omitempty"`
	Uint64Wrapper     *wrapperspb.UInt64Value         `protobuf:"bytes,14,opt,name=uint64_wrapper,json=uint64Wrapper,proto3" json:"uint64_wrapper,omitempty"`
	BoolWrapper       *wrapperspb.BoolValue           `protobuf:"bytes,15,opt,name=bool_wrapper,json=boolWrapper,proto3" json:"bool_wrapper,omitempty"`
	StringWrapper     *wrapperspb.StringValue         `protobuf:"bytes,16,opt,name=string_wrapper,json=stringWrapper,proto3" json:"string_wrapper,omitempty"`
	BytesWrapper      *wrapperspb.BytesValue          `protobuf:"bytes,17,opt,name=bytes_wrapper,json=bytesWrapper,proto3" json:"bytes_wrapper,omitempty"`
	RepeatedTimestamp []*timestamppb.Timestamp        `protobuf:"bytes,18,rep,name=repeated_timestamp,json=repeatedTimestamp,proto3" json:"repeated_timestamp,omitempty"`
	MapDuration       map[string]*durationpb.Duration `protobuf:"bytes,19,rep,name=map_duration,json=mapDuration,proto3" json:"map_duration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WellKnownTypes) Reset() {
	*x = WellKnownTypes{}
	mi := &file_golden_golden_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WellKnownTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WellKnownTypes) ProtoMessage() {}

func (x *WellKnownTypes) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WellKnownTypes.ProtoReflect.Descriptor instead.
func (*WellKnownTypes) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{8}
}

func (x *WellKnownTypes) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WellKnownTypes) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *WellKnownTypes) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *WellKnownTypes) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

func (x *WellKnownTypes) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *WellKnownTypes) GetStruct() *structpb.Struct {
	if x != nil {
		return x.Struct
	}
	return nil
}

func (x *WellKnownTypes) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WellKnownTypes) GetListValue() *structpb.ListValue {
	if x != nil {
		return x.ListValue
	}
	return nil
}

func (x *WellKnownTypes) GetDoubleWrapper() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleWrapper
	}
	return nil
}

func (x *WellKnownTypes) GetFloatWrapper() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatWrapper
	}
	return nil
}

func (x *WellKnownTypes) GetInt32Wrapper() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Wrapper
	}
	return nil
}

func (x *WellKnownTypes) GetInt64Wrapper() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Wrapper
	}
	return nil
}

func (x *WellKnownTypes) GetUint32Wrapper() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Wrapper
	}
	return nil
}

func (x *WellKnownTypes) GetUint64Wrapper() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Wrapper
	}
	return nil
}

func (x *WellKnownTypes) GetBoolWrapper() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolWrapper
	}
	return nil
}

func (x *WellKnownTypes) GetStringWrapper() *wrapperspb.StringValue {
	if x != nil {
		return x.StringWrapper
	}
	return nil
}

func (x *WellKnownTypes) GetBytesWrapper() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesWrapper
	}
	return nil
}

func (x *WellKnownTypes) GetRepeatedTimestamp() []*timestamppb.Timestamp {
	if x != nil {
		return x.RepeatedTimestamp
	}
	return nil
}

func (x *WellKnownTypes) GetMapDuration() map[string]*durationpb.Duration {
	if x != nil {
		return x.MapDuration
	}
	return nil
}

// Self-referential tree node.
type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent        *TreeNode              `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`                                                                         // singular self-reference
	Children      []*TreeNode            `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`                                                                     // repeated self-reference
	Named         map[string]*TreeNode   `protobuf:"bytes,4,rep,name=named,proto3" json:"named,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // self-reference as map value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_golden_golden_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{9}
}

func (x *TreeNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TreeNode) GetParent() *TreeNode {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *TreeNode) GetChildren() []*TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *TreeNode) GetNamed() map[string]*TreeNode {
	if x != nil {
		return x.Named
	}
	return nil
}

// Mutually recursive pair.
type MutualA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *MutualB               `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutualA) Reset() {
	*x = MutualA{}
	mi := &file_golden_golden_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutualA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutualA) ProtoMessage() {}

func (x *MutualA) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutualA.ProtoReflect.Descriptor instead.
func (*MutualA) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{10}
}

func (x *MutualA) GetB() *MutualB {
	if x != nil {
		return x.B
	}
	return nil
}

type MutualB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *MutualA               `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutualB) Reset() {
	*x = MutualB{}
	mi := &file_golden_golden_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutualB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutualB) ProtoMessage() {}

func (x *MutualB) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutualB.ProtoReflect.Descriptor instead.
func (*MutualB) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{11}
}

func (x *MutualB) GetA() *MutualA {
	if x != nil {
		return x.A
	}
	return nil
}

type Reserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        string                 `protobuf:"bytes,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserved) Reset() {
	*x = Reserved{}
	mi := &file_golden_golden_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserved) ProtoMessage() {}

func (x *Reserved) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserved.ProtoReflect.Descriptor instead.
func (*Reserved) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{12}
}

func (x *Reserved) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

type Everything struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Scalars          *ScalarTypes           `protobuf:"bytes,1,opt,name=scalars,proto3" json:"scalars,omitempty"`
	Optionals        *OptionalScalarTypes   `protobuf:"bytes,2,opt,name=optionals,proto3" json:"optionals,omitempty"`
	Repeateds        *RepeatedScalarTypes   `protobuf:"bytes,3,opt,name=repeateds,proto3" json:"repeateds,omitempty"`
	EnumsAndMessages *EnumAndMessageFields  `protobuf:"bytes,4,opt,name=enums_and_messages,json=enumsAndMessages,proto3" json:"enums_and_messages,omitempty"`
	MapKeys          *MapKeyTypes           `protobuf:"bytes,5,opt,name=map_keys,json=mapKeys,proto3" json:"map_keys,omitempty"`
	MapValues        *MapValueTypes         `protobuf:"bytes,6,opt,name=map_values,json=mapValues,proto3" json:"map_values,omitempty"`
	Oneof            *OneofContainer        `protobuf:"bytes,7,opt,name=oneof,proto3" json:"oneof,omitempty"`
	WellKnown        *WellKnownTypes        `protobuf:"bytes,8,opt,name=well_known,json=wellKnown,proto3" json:"well_known,omitempty"`
	Tree             *TreeNode              `protobuf:"bytes,9,opt,name=tree,proto3" json:"tree,omitempty"`
	Reserved         *Reserved              `protobuf:"bytes,10,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Recursive        []*Everything          `protobuf:"bytes,11,rep,name=recursive,proto3" json:"recursive,omitempty"`
	// Types that are valid to be assigned to Terminal:
	//
	//	*Everything_Done
	//	*Everything_Error
	Terminal      isEverything_Terminal `protobuf_oneof:"terminal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Everything) Reset() {
	*x = Everything{}
	mi := &file_golden_golden_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Everything) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Everything) ProtoMessage() {}

func (x *Everything) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Everything.ProtoReflect.Descriptor instead.
func (*Everything) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{13}
}

func (x *Everything) GetScalars() *ScalarTypes {
	if x != nil {
		return x.Scalars
	}
	return nil
}

func (x *Everything) GetOptionals() *OptionalScalarTypes {
	if x != nil {
		return x.Optionals
	}
	return nil
}

func (x *Everything) GetRepeateds() *RepeatedScalarTypes {
	if x != nil {
		return x.Repeateds
	}
	return nil
}

func (x *Everything) GetEnumsAndMessages() *EnumAndMessageFields {
	if x != nil {
		return x.EnumsAndMessages
	}
	return nil
}

func (x *Everything) GetMapKeys() *MapKeyTypes {
	if x != nil {
		return x.MapKeys
	}
	return nil
}

func (x *Everything) GetMapValues() *MapValueTypes {
	if x != nil {
		return x.MapValues
	}
	return nil
}

func (x *Everything) GetOneof() *OneofContainer {
	if x != nil {
		return x.Oneof
	}
	return nil
}

func (x *Everything) GetWellKnown() *WellKnownTypes {
	if x != nil {
		return x.WellKnown
	}
	return nil
}

func (x *Everything) GetTree() *TreeNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *Everything) GetReserved() *Reserved {
	if x != nil {
		return x.Reserved
	}
	return nil
}

func (x *Everything) GetRecursive() []*Everything {
	if x != nil {
		return x.Recursive
	}
	return nil
}

func (x *Everything) GetTerminal() isEverything_Terminal {
	if x != nil {
		return x.Terminal
	}
	return nil
}

func (x *Everything) GetDone() bool {
	if x != nil {
		if x, ok := x.Terminal.(*Everything_Done); ok {
			return x.Done
		}
	}
	return false
}

func (x *Everything) GetError() string {
	if x != nil {
		if x, ok := x.Terminal.(*Everything_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isEverything_Terminal interface {
	isEverything_Terminal()
}

type Everything_Done struct {
	Done bool `protobuf:"varint,12,opt,name=done,proto3,oneof"`
}

type Everything_Error struct {
	Error string `protobuf:"bytes,13,opt,name=error,proto3,oneof"`
}

func (*Everything_Done) isEverything_Terminal() {}

func (*Everything_Error) isEverything_Terminal() {}

// Nested message type.
type Outer_Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestedEnum    Outer_NestedEnum       `protobuf:"varint,1,opt,name=nested_enum,json=nestedEnum,proto3,enum=golden.Outer_NestedEnum" json:"nested_enum,omitempty"`
	Deep          *Outer_Inner_DeepInner `protobuf:"bytes,2,opt,name=deep,proto3" json:"deep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer_Inner) Reset() {
	*x = Outer_Inner{}
	mi := &file_golden_golden_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Inner) ProtoMessage() {}

func (x *Outer_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Inner.ProtoReflect.Descriptor instead.
func (*Outer_Inner) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Outer_Inner) GetNestedEnum() Outer_NestedEnum {
	if x != nil {
		return x.NestedEnum
	}
	return Outer_NESTED_ENUM_UNSPECIFIED
}

func (x *Outer_Inner) GetDeep() *Outer_Inner_DeepInner {
	if x != nil {
		return x.Deep
	}
	return nil
}

type Outer_Inner_DeepInner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer_Inner_DeepInner) Reset() {
	*x = Outer_Inner_DeepInner{}
	mi := &file_golden_golden_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer_Inner_DeepInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_Inner_DeepInner) ProtoMessage() {}

func (x *Outer_Inner_DeepInner) ProtoReflect() protoreflect.Message {
	mi := &file_golden_golden_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_Inner_DeepInner.ProtoReflect.Descriptor instead.
func (*Outer_Inner_DeepInner) Descriptor() ([]byte, []int) {
	return file_golden_golden_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *Outer_Inner_DeepInner) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_golden_golden_proto protoreflect.FileDescriptor

const file_golden_golden_proto_rawDesc = "" +
	"\n" +
	"\x13golden/golden.proto\x12\x06golden\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9a\x04\n" +
	"\vScalarTypes\x12!\n" +
	"\ffield_double\x18\x01 \x01(\x01R\vfieldDouble\x12\x1f\n" +
	"\vfield_float\x18\x02 \x01(\x02R\n" +
	"fieldFloat\x12\x1f\n" +
	"\vfield_int32\x18\x03 \x01(\x05R\n" +
	"fieldInt32\x12\x1f\n" +
	"\vfield_int64\x18\x04 \x01(\x03R\n" +
	"fieldInt64\x12!\n" +
	"\ffield_uint32\x18\x05 \x01(\rR\vfieldUint32\x12!\n" +
	"\ffield_uint64\x18\x06 \x01(\x04R\vfieldUint64\x12!\n" +
	"\ffield_sint32\x18\a \x01(\x11R\vfieldSint32\x12!\n" +
	"\ffield_sint64\x18\b \x01(\x12R\vfieldSint64\x12#\n" +
	"\rfield_fixed32\x18\t \x01(\aR\ffieldFixed32\x12#\n" +
	"\rfield_fixed64\x18\n" +
	" \x01(\x06R\ffieldFixed64\x12%\n" +
	"\x0efield_sfixed32\x18\v \x01(\x0fR\rfieldSfixed32\x12%\n" +
	"\x0efield_sfixed64\x18\f \x01(\x10R\rfieldSfixed64\x12\x1d\n" +
	"\n" +
	"field_bool\x18\r \x01(\bR\tfieldBool\x12!\n" +
	"\ffield_string\x18\x0e \x01(\tR\vfieldString\x12\x1f\n" +
	"\vfield_bytes\x18\x0f \x01(\fR\n" +
	"fieldBytes\"\xec\x06\n" +
	"\x13OptionalScalarTypes\x12&\n" +
	"\ffield_double\x18\x01 \x01(\x01H\x00R\vfieldDouble\x88\x01\x01\x12$\n" +
	"\vfield_float\x18\x02 \x01(\x02H\x01R\n" +
	"fieldFloat\x88\x01\x01\x12$\n" +
	"\vfield_int32\x18\x03 \x01(\x05H\x02R\n" +
	"fieldInt32\x88\x01\x01\x12$\n" +
	"\vfield_int64\x18\x04 \x01(\x03H\x03R\n" +
	"fieldInt64\x88\x01\x01\x12&\n" +
	"\ffield_uint32\x18\x05 \x01(\rH\x04R\vfieldUint32\x88\x01\x01\x12&\n" +
	"\ffield_uint64\x18\x06 \x01(\x04H\x05R\vfieldUint64\x88\x01\x01\x12&\n" +
	"\ffield_sint32\x18\a \x01(\x11H\x06R\vfieldSint32\x88\x01\x01\x12&\n" +
	"\ffield_sint64\x18\b \x01(\x12H\aR\vfieldSint64\x88\x01\x01\x12(\n" +
	"\rfield_fixed32\x18\t \x01(\aH\bR\ffieldFixed32\x88\x01\x01\x12(\n" +
	"\rfield_fixed64\x18\n" +
	" \x01(\x06H\tR\ffieldFixed64\x88\x01\x01\x12*\n" +
	"\x0efield_sfixed32\x18\v \x01(\x0fH\n" +
	"R\rfieldSfixed32\x88\x01\x01\x12*\n" +
	"\x0efield_sfixed64\x18\f \x01(\x10H\vR\rfieldSfixed64\x88\x01\x01\x12\"\n" +
	"\n" +
	"field_bool\x18\r \x01(\bH\fR\tfieldBool\x88\x01\x01\x12&\n" +
	"\ffield_string\x18\x0e \x01(\tH\rR\vfieldString\x88\x01\x01\x12$\n" +
	"\vfield_bytes\x18\x0f \x01(\fH\x0eR\n" +
	"fieldBytes\x88\x01\x01B\x0f\n" +
	"\r_field_doubleB\x0e\n" +
	"\f_field_floatB\x0e\n" +
	"\f_field_int32B\x0e\n" +
	"\f_field_int64B\x0f\n" +
	"\r_field_uint32B\x0f\n" +
	"\r_field_uint64B\x0f\n" +
	"\r_field_sint32B\x0f\n" +
	"\r_field_sint64B\x10\n" +
	"\x0e_field_fixed32B\x10\n" +
	"\x0e_field_fixed64B\x11\n" +
	"\x0f_field_sfixed32B\x11\n" +
	"\x0f_field_sfixed64B\r\n" +
	"\v_field_boolB\x0f\n" +
	"\r_field_stringB\x0e\n" +
	"\f_field_bytes\"\xa2\x04\n" +
	"\x13RepeatedScalarTypes\x12!\n" +
	"\ffield_double\x18\x01 \x03(\x01R\vfieldDouble\x12\x1f\n" +
	"\vfield_float\x18\x02 \x03(\x02R\n" +
	"fieldFloat\x12\x1f\n" +
	"\vfield_int32\x18\x03 \x03(\x05R\n" +
	"fieldInt32\x12\x1f\n" +
	"\vfield_int64\x18\x04 \x03(\x03R\n" +
	"fieldInt64\x12!\n" +
	"\ffield_uint32\x18\x05 \x03(\rR\vfieldUint32\x12!\n" +
	"\ffield_uint64\x18\x06 \x03(\x04R\vfieldUint64\x12!\n" +
	"\ffield_sint32\x18\a \x03(\x11R\vfieldSint32\x12!\n" +
	"\ffield_sint64\x18\b \x03(\x12R\vfieldSint64\x12#\n" +
	"\rfield_fixed32\x18\t \x03(\aR\ffieldFixed32\x12#\n" +
	"\rfield_fixed64\x18\n" +
	" \x03(\x06R\ffieldFixed64\x12%\n" +
	"\x0efield_sfixed32\x18\v \x03(\x0fR\rfieldSfixed32\x12%\n" +
	"\x0efield_sfixed64\x18\f \x03(\x10R\rfieldSfixed64\x12\x1d\n" +
	"\n" +
	"field_bool\x18\r \x03(\bR\tfieldBool\x12!\n" +
	"\ffield_string\x18\x0e \x03(\tR\vfieldString\x12\x1f\n" +
	"\vfield_bytes\x18\x0f \x03(\fR\n" +
	"fieldBytes\"\x95\x03\n" +
	"\x05Outer\x12)\n" +
	"\x05inner\x18\x01 \x01(\v2\x13.golden.Outer.InnerR\x05inner\x127\n" +
	"\n" +
	"enum_field\x18\x02 \x01(\x0e2\x18.golden.Outer.NestedEnumR\tenumField\x12<\n" +
	"\n" +
	"deep_inner\x18\x03 \x01(\v2\x1d.golden.Outer.Inner.DeepInnerR\tdeepInner\x1a\x98\x01\n" +
	"\x05Inner\x129\n" +
	"\vnested_enum\x18\x01 \x01(\x0e2\x18.golden.Outer.NestedEnumR\n" +
	"nestedEnum\x121\n" +
	"\x04deep\x18\x02 \x01(\v2\x1d.golden.Outer.Inner.DeepInnerR\x04deep\x1a!\n" +
	"\tDeepInner\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"O\n" +
	"\n" +
	"NestedEnum\x12\x1b\n" +
	"\x17NESTED_ENUM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rNESTED_ENUM_A\x10\x01\x12\x11\n" +
	"\rNESTED_ENUM_B\x10\x02\"\xaf\x04\n" +
	"\x14EnumAndMessageFields\x129\n" +
	"\rsingular_enum\x18\x01 \x01(\x0e2\x14.golden.TopLevelEnumR\fsingularEnum\x12>\n" +
	"\roptional_enum\x18\x02 \x01(\x0e2\x14.golden.TopLevelEnumH\x00R\foptionalEnum\x88\x01\x01\x129\n" +
	"\rrepeated_enum\x18\x03 \x03(\x0e2\x14.golden.TopLevelEnumR\frepeatedEnum\x12>\n" +
	"\x10singular_message\x18\x04 \x01(\v2\x13.golden.ScalarTypesR\x0fsingularMessage\x12C\n" +
	"\x10optional_message\x18\x05 \x01(\v2\x13.golden.ScalarTypesH\x01R\x0foptionalMessage\x88\x01\x01\x12>\n" +
	"\x10repeated_message\x18\x06 \x03(\v2\x13.golden.ScalarTypesR\x0frepeatedMessage\x129\n" +
	"\vnested_enum\x18\a \x01(\x0e2\x18.golden.Outer.NestedEnumR\n" +
	"nestedEnum\x12:\n" +
	"\x0enested_message\x18\b \x01(\v2\x13.golden.Outer.InnerR\rnestedMessageB\x10\n" +
	"\x0e_optional_enumB\x13\n" +
	"\x11_optional_message\"\xa1\f\n" +
	"\vMapKeyTypes\x12>\n" +
	"\tint32_key\x18\x01 \x03(\v2!.golden.MapKeyTypes.Int32KeyEntryR\bint32Key\x12>\n" +
	"\tint64_key\x18\x02 \x03(\v2!.golden.MapKeyTypes.Int64KeyEntryR\bint64Key\x12A\n" +
	"\n" +
	"uint32_key\x18\x03 \x03(\v2\".golden.MapKeyTypes.Uint32KeyEntryR\tuint32Key\x12A\n" +
	"\n" +
	"uint64_key\x18\x04 \x03(\v2\".golden.MapKeyTypes.Uint64KeyEntryR\tuint64Key\x12A\n" +
	"\n" +
	"sint32_key\x18\x05 \x03(\v2\".golden.MapKeyTypes.Sint32KeyEntryR\tsint32Key\x12A\n" +
	"\n" +
	"sint64_key\x18\x06 \x03(\v2\".golden.MapKeyTypes.Sint64KeyEntryR\tsint64Key\x12D\n" +
	"\vfixed32_key\x18\a \x03(\v2#.golden.MapKeyTypes.Fixed32KeyEntryR\n" +
	"fixed32Key\x12D\n" +
	"\vfixed64_key\x18\b \x03(\v2#.golden.MapKeyTypes.Fixed64KeyEntryR\n" +
	"fixed64Key\x12G\n" +
	"\fsfixed32_key\x18\t \x03(\v2$.golden.MapKeyTypes.Sfixed32KeyEntryR\vsfixed32Key\x12G\n" +
	"\fsfixed64_key\x18\n" +
	" \x03(\v2$.golden.MapKeyTypes.Sfixed64KeyEntryR\vsfixed64Key\x12;\n" +
	"\bbool_key\x18\v \x03(\v2 .golden.MapKeyTypes.BoolKeyEntryR\aboolKey\x12A\n" +
	"\n" +
	"string_key\x18\f \x03(\v2\".golden.MapKeyTypes.StringKeyEntryR\tstringKey\x1a;\n" +
	"\rInt32KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rInt64KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eUint32KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eUint64KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eSint32KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eSint64KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fFixed32KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\aR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fFixed64KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x06R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10Sfixed32KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x0fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10Sfixed64KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x10R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fBoolKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eStringKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\f\n" +
	"\rMapValueTypes\x12I\n" +
	"\fdouble_value\x18\x01 \x03(\v2&.golden.MapValueTypes.DoubleValueEntryR\vdoubleValue\x12F\n" +
	"\vfloat_value\x18\x02 \x03(\v2%.golden.MapValueTypes.FloatValueEntryR\n" +
	"floatValue\x12F\n" +
	"\vint32_value\x18\x03 \x03(\v2%.golden.MapValueTypes.Int32ValueEntryR\n" +
	"int32Value\x12F\n" +
	"\vint64_value\x18\x04 \x03(\v2%.golden.MapValueTypes.Int64ValueEntryR\n" +
	"int64Value\x12I\n" +
	"\fuint32_value\x18\x05 \x03(\v2&.golden.MapValueTypes.Uint32ValueEntryR\vuint32Value\x12I\n" +
	"\fuint64_value\x18\x06 \x03(\v2&.golden.MapValueTypes.Uint64ValueEntryR\vuint64Value\x12C\n" +
	"\n" +
	"bool_value\x18\a \x03(\v2$.golden.MapValueTypes.BoolValueEntryR\tboolValue\x12I\n" +
	"\fstring_value\x18\b \x03(\v2&.golden.MapValueTypes.StringValueEntryR\vstringValue\x12F\n" +
	"\vbytes_value\x18\t \x03(\v2%.golden.MapValueTypes.BytesValueEntryR\n" +
	"bytesValue\x12C\n" +
	"\n" +
	"enum_value\x18\n" +
	" \x03(\v2$.golden.MapValueTypes.EnumValueEntryR\tenumValue\x12L\n" +
	"\rmessage_value\x18\v \x03(\v2'.golden.MapValueTypes.MessageValueEntryR\fmessageValue\x1a>\n" +
	"\x10DoubleValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fFloatValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a=\n" +
	"\x0fInt32ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fInt64ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10Uint32ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a>\n" +
	"\x10Uint64ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a<\n" +
	"\x0eBoolValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a>\n" +
	"\x10StringValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fBytesValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aR\n" +
	"\x0eEnumValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\x0e2\x14.golden.TopLevelEnumR\x05value:\x028\x01\x1aT\n" +
	"\x11MessageValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.golden.ScalarTypesR\x05value:\x028\x01\"\xb0\x03\n" +
	"\x0eOneofContainer\x12%\n" +
	"\rchoice_double\x18\x01 \x01(\x01H\x00R\fchoiceDouble\x12#\n" +
	"\fchoice_int32\x18\x02 \x01(\x05H\x00R\vchoiceInt32\x12!\n" +
	"\vchoice_bool\x18\x03 \x01(\bH\x00R\n" +
	"choiceBool\x12%\n" +
	"\rchoice_string\x18\x04 \x01(\tH\x00R\fchoiceString\x12#\n" +
	"\fchoice_bytes\x18\x05 \x01(\fH\x00R\vchoiceBytes\x127\n" +
	"\vchoice_enum\x18\x06 \x01(\x0e2\x14.golden.TopLevelEnumH\x00R\n" +
	"choiceEnum\x12<\n" +
	"\x0echoice_message\x18\a \x01(\v2\x13.golden.ScalarTypesH\x00R\rchoiceMessage\x12\x19\n" +
	"\aother_a\x18\b \x01(\tH\x01R\x06otherA\x12\x19\n" +
	"\aother_b\x18\t \x01(\x03H\x01R\x06otherB\x12#\n" +
	"\routside_oneof\x18\n" +
	" \x01(\tR\foutsideOneofB\b\n" +
	"\x06choiceB\a\n" +
	"\x05other\"\xf9\t\n" +
	"\x0eWellKnownTypes\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12&\n" +
	"\x03any\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03any\x12,\n" +
	"\x05empty\x18\x04 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\x129\n" +
	"\n" +
	"field_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12/\n" +
	"\x06struct\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06struct\x12,\n" +
	"\x05value\x18\a \x01(\v2\x16.google.protobuf.ValueR\x05value\x129\n" +
	"\n" +
	"list_value\x18\b \x01(\v2\x1a.google.protobuf.ListValueR\tlistValue\x12C\n" +
	"\x0edouble_wrapper\x18\t \x01(\v2\x1c.google.protobuf.DoubleValueR\rdoubleWrapper\x12@\n" +
	"\rfloat_wrapper\x18\n" +
	" \x01(\v2\x1b.google.protobuf.FloatValueR\ffloatWrapper\x12@\n" +
	"\rint32_wrapper\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\fint32Wrapper\x12@\n" +
	"\rint64_wrapper\x18\f \x01(\v2\x1b.google.protobuf.Int64ValueR\fint64Wrapper\x12C\n" +
	"\x0euint32_wrapper\x18\r \x01(\v2\x1c.google.protobuf.UInt32ValueR\ruint32Wrapper\x12C\n" +
	"\x0euint64_wrapper\x18\x0e \x01(\v2\x1c.google.protobuf.UInt64ValueR\ruint64Wrapper\x12=\n" +
	"\fbool_wrapper\x18\x0f \x01(\v2\x1a.google.protobuf.BoolValueR\vboolWrapper\x12C\n" +
	"\x0estring_wrapper\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\rstringWrapper\x12@\n" +
	"\rbytes_wrapper\x18\x11 \x01(\v2\x1b.google.protobuf.BytesValueR\fbytesWrapper\x12I\n" +
	"\x12repeated_timestamp\x18\x12 \x03(\v2\x1a.google.protobuf.TimestampR\x11repeatedTimestamp\x12J\n" +
	"\fmap_duration\x18\x13 \x03(\v2'.golden.WellKnownTypes.MapDurationEntryR\vmapDuration\x1aY\n" +
	"\x10MapDurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05value:\x028\x01\"\xf1\x01\n" +
	"\bTreeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06parent\x18\x02 \x01(\v2\x10.golden.TreeNodeR\x06parent\x12,\n" +
	"\bchildren\x18\x03 \x03(\v2\x10.golden.TreeNodeR\bchildren\x121\n" +
	"\x05named\x18\x04 \x03(\v2\x1b.golden.TreeNode.NamedEntryR\x05named\x1aJ\n" +
	"\n" +
	"NamedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.golden.TreeNodeR\x05value:\x028\x01\"(\n" +
	"\aMutualA\x12\x1d\n" +
	"\x01b\x18\x01 \x01(\v2\x0f.golden.MutualBR\x01b\"(\n" +
	"\aMutualB\x12\x1d\n" +
	"\x01a\x18\x01 \x01(\v2\x0f.golden.MutualAR\x01a\"Q\n" +
	"\bReserved\x12\x16\n" +
	"\x06active\x18\x01 \x01(\tR\x06activeJ\x04\b\x02\x10\x03J\x04\b\x04\x10\x05J\x04\b\x06\x10\n" +
	"R\told_fieldR\x10deprecated_field\"\x88\x05\n" +
	"\n" +
	"Everything\x12-\n" +
	"\ascalars\x18\x01 \x01(\v2\x13.golden.ScalarTypesR\ascalars\x129\n" +
	"\toptionals\x18\x02 \x01(\v2\x1b.golden.OptionalScalarTypesR\toptionals\x129\n" +
	"\trepeateds\x18\x03 \x01(\v2\x1b.golden.RepeatedScalarTypesR\trepeateds\x12J\n" +
	"\x12enums_and_messages\x18\x04 \x01(\v2\x1c.golden.EnumAndMessageFieldsR\x10enumsAndMessages\x12.\n" +
	"\bmap_keys\x18\x05 \x01(\v2\x13.golden.MapKeyTypesR\amapKeys\x124\n" +
	"\n" +
	"map_values\x18\x06 \x01(\v2\x15.golden.MapValueTypesR\tmapValues\x12,\n" +
	"\x05oneof\x18\a \x01(\v2\x16.golden.OneofContainerR\x05oneof\x125\n" +
	"\n" +
	"well_known\x18\b \x01(\v2\x16.golden.WellKnownTypesR\twellKnown\x12$\n" +
	"\x04tree\x18\t \x01(\v2\x10.golden.TreeNodeR\x04tree\x12,\n" +
	"\breserved\x18\n" +
	" \x01(\v2\x10.golden.ReservedR\breserved\x120\n" +
	"\trecursive\x18\v \x03(\v2\x12.golden.EverythingR\trecursive\x12\x14\n" +
	"\x04done\x18\f \x01(\bH\x00R\x04done\x12\x16\n" +
	"\x05error\x18\r \x01(\tH\x00R\x05errorB\n" +
	"\n" +
	"\bterminal*\x89\x01\n" +
	"\fTopLevelEnum\x12\x1e\n" +
	"\x1aTOP_LEVEL_ENUM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TOP_LEVEL_ENUM_FIRST\x10\x01\x12\x19\n" +
	"\x15TOP_LEVEL_ENUM_SECOND\x10\x02\x12$\n" +
	"\x17TOP_LEVEL_ENUM_NEGATIVE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*c\n" +
	"\vAliasedEnum\x12\x1c\n" +
	"\x18ALIASED_ENUM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ALIASED_ENUM_RUNNING\x10\x01\x12\x18\n" +
	"\x14ALIASED_ENUM_STARTED\x10\x01\x1a\x02\x10\x01B5Z3github.com/gopherex/protoc-gen-go-plainjson/example/goldenb\x06proto3"

var (
	file_golden_golden_proto_rawDescOnce sync.Once
	file_golden_golden_proto_rawDescData []byte
)

func file_golden_golden_proto_rawDescGZIP() []byte {
	file_golden_golden_proto_rawDescOnce.Do(func() {
		file_golden_golden_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_golden_golden_proto_rawDesc), len(file_golden_golden_proto_rawDesc)))
	})
	return file_golden_golden_proto_rawDescData
}

var file_golden_golden_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_golden_golden_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_golden_golden_proto_goTypes = []any{
	(TopLevelEnum)(0),              // 0: golden.TopLevelEnum
	(AliasedEnum)(0),               // 1: golden.AliasedEnum
	(Outer_NestedEnum)(0),          // 2: golden.Outer.NestedEnum
	(*ScalarTypes)(nil),            // 3: golden.ScalarTypes
	(*OptionalScalarTypes)(nil),    // 4: golden.OptionalScalarTypes
	(*RepeatedScalarTypes)(nil),    // 5: golden.RepeatedScalarTypes
	(*Outer)(nil),                  // 6: golden.Outer
	(*EnumAndMessageFields)(nil),   // 7: golden.EnumAndMessageFields
	(*MapKeyTypes)(nil),            // 8: golden.MapKeyTypes
	(*MapValueTypes)(nil),          // 9: golden.MapValueTypes
	(*OneofContainer)(nil),         // 10: golden.OneofContainer
	(*WellKnownTypes)(nil),         // 11: golden.WellKnownTypes
	(*TreeNode)(nil),               // 12: golden.TreeNode
	(*MutualA)(nil),                // 13: golden.MutualA
	(*MutualB)(nil),                // 14: golden.MutualB
	(*Reserved)(nil),               // 15: golden.Reserved
	(*Everything)(nil),             // 16: golden.Everything
	(*Outer_Inner)(nil),            // 17: golden.Outer.Inner
	(*Outer_Inner_DeepInner)(nil),  // 18: golden.Outer.Inner.DeepInner
	nil,                            // 19: golden.MapKeyTypes.Int32KeyEntry
	nil,                            // 20: golden.MapKeyTypes.Int64KeyEntry
	nil,                            // 21: golden.MapKeyTypes.Uint32KeyEntry
	nil,                            // 22: golden.MapKeyTypes.Uint64KeyEntry
	nil,                            // 23: golden.MapKeyTypes.Sint32KeyEntry
	nil,                            // 24: golden.MapKeyTypes.Sint64KeyEntry
	nil,                            // 25: golden.MapKeyTypes.Fixed32KeyEntry
	nil,                            // 26: golden.MapKeyTypes.Fixed64KeyEntry
	nil,                            // 27: golden.MapKeyTypes.Sfixed32KeyEntry
	nil,                            // 28: golden.MapKeyTypes.Sfixed64KeyEntry
	nil,                            // 29: golden.MapKeyTypes.BoolKeyEntry
	nil,                            // 30: golden.MapKeyTypes.StringKeyEntry
	nil,                            // 31: golden.MapValueTypes.DoubleValueEntry
	nil,                            // 32: golden.MapValueTypes.FloatValueEntry
	nil,                            // 33: golden.MapValueTypes.Int32ValueEntry
	nil,                            // 34: golden.MapValueTypes.Int64ValueEntry
	nil,                            // 35: golden.MapValueTypes.Uint32ValueEntry
	nil,                            // 36: golden.MapValueTypes.Uint64ValueEntry
	nil,                            // 37: golden.MapValueTypes.BoolValueEntry
	nil,                            // 38: golden.MapValueTypes.StringValueEntry
	nil,                            // 39: golden.MapValueTypes.BytesValueEntry
	nil,                            // 40: golden.MapValueTypes.EnumValueEntry
	nil,                            // 41: golden.MapValueTypes.MessageValueEntry
	nil,                            // 42: golden.WellKnownTypes.MapDurationEntry
	nil,                            // 43: golden.TreeNode.NamedEntry
	(*timestamppb.Timestamp)(nil),  // 44: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 45: google.protobuf.Duration
	(*anypb.Any)(nil),              // 46: google.protobuf.Any
	(*emptypb.Empty)(nil),          // 47: google.protobuf.Empty
	(*fieldmaskpb.FieldMask)(nil),  // 48: google.protobuf.FieldMask
	(*structpb.Struct)(nil),        // 49: google.protobuf.Struct
	(*structpb.Value)(nil),         // 50: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 51: google.protobuf.ListValue
	(*wrapperspb.DoubleValue)(nil), // 52: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 53: google.protobuf.FloatValue
	(*wrapperspb.Int32Value)(nil),  // 54: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 55: google.protobuf.Int64Value
	(*wrapperspb.UInt32Value)(nil), // 56: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 57: google.protobuf.UInt64Value
	(*wrapperspb.BoolValue)(nil),   // 58: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 59: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 60: google.protobuf.BytesValue
}
var file_golden_golden_proto_depIdxs = []int32{
	17, // 0: golden.Outer.inner:type_name -> golden.Outer.Inner
	2,  // 1: golden.Outer.enum_field:type_name -> golden.Outer.NestedEnum
	18, // 2: golden.Outer.deep_inner:type_name -> golden.Outer.Inner.DeepInner
	0,  // 3: golden.EnumAndMessageFields.singular_enum:type_name -> golden.TopLevelEnum
	0,  // 4: golden.EnumAndMessageFields.optional_enum:type_name -> golden.TopLevelEnum
	0,  // 5: golden.EnumAndMessageFields.repeated_enum:type_name -> golden.TopLevelEnum
	3,  // 6: golden.EnumAndMessageFields.singular_message:type_name -> golden.ScalarTypes
	3,  // 7: golden.EnumAndMessageFields.optional_message:type_name -> golden.ScalarTypes
	3,  // 8: golden.EnumAndMessageFields.repeated_message:type_name -> golden.ScalarTypes
	2,  // 9: golden.EnumAndMessageFields.nested_enum:type_name -> golden.Outer.NestedEnum
	17, // 10: golden.EnumAndMessageFields.nested_message:type_name -> golden.Outer.Inner
	19, // 11: golden.MapKeyTypes.int32_key:type_name -> golden.MapKeyTypes.Int32KeyEntry
	20, // 12: golden.MapKeyTypes.int64_key:type_name -> golden.MapKeyTypes.Int64KeyEntry
	21, // 13: golden.MapKeyTypes.uint32_key:type_name -> golden.MapKeyTypes.Uint32KeyEntry
	22, // 14: golden.MapKeyTypes.uint64_key:type_name -> golden.MapKeyTypes.Uint64KeyEntry
	23, // 15: golden.MapKeyTypes.sint32_key:type_name -> golden.MapKeyTypes.Sint32KeyEntry
	24, // 16: golden.MapKeyTypes.sint64_key:type_name -> golden.MapKeyTypes.Sint64KeyEntry
	25, // 17: golden.MapKeyTypes.fixed32_key:type_name -> golden.MapKeyTypes.Fixed32KeyEntry
	26, // 18: golden.MapKeyTypes.fixed64_key:type_name -> golden.MapKeyTypes.Fixed64KeyEntry
	27, // 19: golden.MapKeyTypes.sfixed32_key:type_name -> golden.MapKeyTypes.Sfixed32KeyEntry
	28, // 20: golden.MapKeyTypes.sfixed64_key:type_name -> golden.MapKeyTypes.Sfixed64KeyEntry
	29, // 21: golden.MapKeyTypes.bool_key:type_name -> golden.MapKeyTypes.BoolKeyEntry
	30, // 22: golden.MapKeyTypes.string_key:type_name -> golden.MapKeyTypes.StringKeyEntry
	31, // 23: golden.MapValueTypes.double_value:type_name -> golden.MapValueTypes.DoubleValueEntry
	32, // 24: golden.MapValueTypes.float_value:type_name -> golden.MapValueTypes.FloatValueEntry
	33, // 25: golden.MapValueTypes.int32_value:type_name -> golden.MapValueTypes.Int32ValueEntry
	34, // 26: golden.MapValueTypes.int64_value:type_name -> golden.MapValueTypes.Int64ValueEntry
	35, // 27: golden.MapValueTypes.uint32_value:type_name -> golden.MapValueTypes.Uint32ValueEntry
	36, // 28: golden.MapValueTypes.uint64_value:type_name -> golden.MapValueTypes.Uint64ValueEntry
	37, // 29: golden.MapValueTypes.bool_value:type_name -> golden.MapValueTypes.BoolValueEntry
	38, // 30: golden.MapValueTypes.string_value:type_name -> golden.MapValueTypes.StringValueEntry
	39, // 31: golden.MapValueTypes.bytes_value:type_name -> golden.MapValueTypes.BytesValueEntry
	40, // 32: golden.MapValueTypes.enum_value:type_name -> golden.MapValueTypes.EnumValueEntry
	41, // 33: golden.MapValueTypes.message_value:type_name -> golden.MapValueTypes.MessageValueEntry
	0,  // 34: golden.OneofContainer.choice_enum:type_name -> golden.TopLevelEnum
	3,  // 35: golden.OneofContainer.choice_message:type_name -> golden.ScalarTypes
	44, // 36: golden.WellKnownTypes.timestamp:type_name -> google.protobuf.Timestamp
	45, // 37: golden.WellKnownTypes.duration:type_name -> google.protobuf.Duration
	46, // 38: golden.WellKnownTypes.any:type_name -> google.protobuf.Any
	47, // 39: golden.WellKnownTypes.empty:type_name -> google.protobuf.Empty
	48, // 40: golden.WellKnownTypes.field_mask:type_name -> google.protobuf.FieldMask
	49, // 41: golden.WellKnownTypes.struct:type_name -> google.protobuf.Struct
	50, // 42: golden.WellKnownTypes.value:type_name -> google.protobuf.Value
	51, // 43: golden.WellKnownTypes.list_value:type_name -> google.protobuf.ListValue
	52, // 44: golden.WellKnownTypes.double_wrapper:type_name -> google.protobuf.DoubleValue
	53, // 45: golden.WellKnownTypes.float_wrapper:type_name -> google.protobuf.FloatValue
	54, // 46: golden.WellKnownTypes.int32_wrapper:type_name -> google.protobuf.Int32Value
	55, // 47: golden.WellKnownTypes.int64_wrapper:type_name -> google.protobuf.Int64Value
	56, // 48: golden.WellKnownTypes.uint32_wrapper:type_name -> google.protobuf.UInt32Value
	57, // 49: golden.WellKnownTypes.uint64_wrapper:type_name -> google.protobuf.UInt64Value
	58, // 50: golden.WellKnownTypes.bool_wrapper:type_name -> google.protobuf.BoolValue
	59, // 51: golden.WellKnownTypes.string_wrapper:type_name -> google.protobuf.StringValue
	60, // 52: golden.WellKnownTypes.bytes_wrapper:type_name -> google.protobuf.BytesValue
	44, // 53: golden.WellKnownTypes.repeated_timestamp:type_name -> google.protobuf.Timestamp
	42, // 54: golden.WellKnownTypes.map_duration:type_name -> golden.WellKnownTypes.MapDurationEntry
	12, // 55: golden.TreeNode.parent:type_name -> golden.TreeNode
	12, // 56: golden.TreeNode.children:type_name -> golden.TreeNode
	43, // 57: golden.TreeNode.named:type_name -> golden.TreeNode.NamedEntry
	14, // 58: golden.MutualA.b:type_name -> golden.MutualB
	13, // 59: golden.MutualB.a:type_name -> golden.MutualA
	3,  // 60: golden.Everything.scalars:type_name -> golden.ScalarTypes
	4,  // 61: golden.Everything.optionals:type_name -> golden.OptionalScalarTypes
	5,  // 62: golden.Everything.repeateds:type_name -> golden.RepeatedScalarTypes
	7,  // 63: golden.Everything.enums_and_messages:type_name -> golden.EnumAndMessageFields
	8,  // 64: golden.Everything.map_keys:type_name -> golden.MapKeyTypes
	9,  // 65: golden.Everything.map_values:type_name -> golden.MapValueTypes
	10, // 66: golden.Everything.oneof:type_name -> golden.OneofContainer
	11, // 67: golden.Everything.well_known:type_name -> golden.WellKnownTypes
	12, // 68: golden.Everything.tree:type_name -> golden.TreeNode
	15, // 69: golden.Everything.reserved:type_name -> golden.Reserved
	16, // 70: golden.Everything.recursive:type_name -> golden.Everything
	2,  // 71: golden.Outer.Inner.nested_enum:type_name -> golden.Outer.NestedEnum
	18, // 72: golden.Outer.Inner.deep:type_name -> golden.Outer.Inner.DeepInner
	0,  // 73: golden.MapValueTypes.EnumValueEntry.value:type_name -> golden.TopLevelEnum
	3,  // 74: golden.MapValueTypes.MessageValueEntry.value:type_name -> golden.ScalarTypes
	45, // 75: golden.WellKnownTypes.MapDurationEntry.value:type_name -> google.protobuf.Duration
	12, // 76: golden.TreeNode.NamedEntry.value:type_name -> golden.TreeNode
	77, // [77:77] is the sub-list for method output_type
	77, // [77:77] is the sub-list for method input_type
	77, // [77:77] is the sub-list for extension type_name
	77, // [77:77] is the sub-list for extension extendee
	0,  // [0:77] is the sub-list for field type_name
}

func init() { file_golden_golden_proto_init() }
func file_golden_golden_proto_init() {
	if File_golden_golden_proto != nil {
		return
	}
	file_golden_golden_proto_msgTypes[1].OneofWrappers = []any{}
	file_golden_golden_proto_msgTypes[4].OneofWrappers = []any{}
	file_golden_golden_proto_msgTypes[7].OneofWrappers = []any{
		(*OneofContainer_ChoiceDouble)(nil),
		(*OneofContainer_ChoiceInt32)(nil),
		(*OneofContainer_ChoiceBool)(nil),
		(*OneofContainer_ChoiceString)(nil),
		(*OneofContainer_ChoiceBytes)(nil),
		(*OneofContainer_ChoiceEnum)(nil),
		(*OneofContainer_ChoiceMessage)(nil),
		(*OneofContainer_OtherA)(nil),
		(*OneofContainer_OtherB)(nil),
	}
	file_golden_golden_proto_msgTypes[13].OneofWrappers = []any{
		(*Everything_Done)(nil),
		(*Everything_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_golden_golden_proto_rawDesc), len(file_golden_golden_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_golden_golden_proto_goTypes,
		DependencyIndexes: file_golden_golden_proto_depIdxs,
		EnumInfos:         file_golden_golden_proto_enumTypes,
		MessageInfos:      file_golden_golden_proto_msgTypes,
	}.Build()
	File_golden_golden_proto = out.File
	file_golden_golden_proto_goTypes = nil
	file_golden_golden_proto_depIdxs = nil
}
