// Code generated by protoc-gen-go-plainjson. DO NOT EDIT.
//
// The marshalers below are one-way: they flatten a message into JSON and
// cannot read it back.
//
// source: example/spec/selection/selection.proto

package selection

import (
	jx "github.com/go-faster/jx"
	plainjsonpb "github.com/gopherex/protoc-gen-go-plainjson/plainjsonpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// plainjsonEnumName_NullValue renders google.protobuf.NullValue the way its options ask for.
func plainjsonEnumName_NullValue(v structpb.NullValue) string {
	switch v {
	case structpb.NullValue_NULL_VALUE:
		return "NULL_VALUE"
	}
	return v.String()
}

// EncodePlainJSON writes the flattened form of Omit into e.
func (m *Omit) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_Omit(m, e)
}

// MarshalPlainJSON returns the flattened form of Omit.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *Omit) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_Omit(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of Pick into e.
func (m *Pick) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_Pick(m, e)
}

// MarshalPlainJSON returns the flattened form of Pick.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *Pick) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_Pick(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of PickKeepsFieldName into e.
func (m *PickKeepsFieldName) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_PickKeepsFieldName(m, e)
}

// MarshalPlainJSON returns the flattened form of PickKeepsFieldName.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *PickKeepsFieldName) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_PickKeepsFieldName(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of Lift into e.
func (m *Lift) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_Lift(m, e)
}

// MarshalPlainJSON returns the flattened form of Lift.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *Lift) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_Lift(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of LiftAlongsideFlatten into e.
func (m *LiftAlongsideFlatten) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_LiftAlongsideFlatten(m, e)
}

// MarshalPlainJSON returns the flattened form of LiftAlongsideFlatten.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *LiftAlongsideFlatten) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_LiftAlongsideFlatten(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// EncodePlainJSON writes the flattened form of PickFromStruct into e.
func (m *PickFromStruct) EncodePlainJSON(e *jx.Encoder) error {
	return encodePlainJSON_PickFromStruct(m, e)
}

// MarshalPlainJSON returns the flattened form of PickFromStruct.
//
// The transformation is one-way: nesting, branch identity and dropped
// fields cannot be recovered from the result.
func (m *PickFromStruct) MarshalPlainJSON() ([]byte, error) {
	var e jx.Encoder
	if err := encodePlainJSON_PickFromStruct(m, &e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

// encodePlainJSON_Omit writes spec.selection.Omit as a flat JSON object.
func encodePlainJSON_Omit(m *Omit, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- id
	if v := m.GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_Pick writes spec.selection.Pick as a flat JSON object.
func encodePlainJSON_Pick(m *Pick, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// total <- total.amount
	if v := m.GetTotal().GetAmount(); v != 0 {
		e.FieldStart("total")
		plainjsonpb.Int64(e, v, false)
	}
	// email <- buyer.profile.contact.email
	if v := m.GetBuyer().GetProfile().GetContact().GetEmail(); v != "" {
		e.FieldStart("email")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_PickKeepsFieldName writes spec.selection.PickKeepsFieldName as a flat JSON object.
func encodePlainJSON_PickKeepsFieldName(m *PickKeepsFieldName, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// buyer <- buyer.profile.contact.email
	if v := m.GetBuyer().GetProfile().GetContact().GetEmail(); v != "" {
		e.FieldStart("buyer")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_Lift writes spec.selection.Lift as a flat JSON object.
func encodePlainJSON_Lift(m *Lift, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// id <- deep.a.b.id
	if v := m.GetDeep().GetA().GetB().GetId(); v != "" {
		e.FieldStart("id")
		e.Str(v)
	}
	// title <- deep.a.b.title
	if v := m.GetDeep().GetA().GetB().GetTitle(); v != "" {
		e.FieldStart("title")
		e.Str(v)
	}
	// total <- deep.a.stats.total
	if v := m.GetDeep().GetA().GetStats().GetTotal(); v != 0 {
		e.FieldStart("total")
		e.Int32(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_LiftAlongsideFlatten writes spec.selection.LiftAlongsideFlatten as a flat JSON object.
func encodePlainJSON_LiftAlongsideFlatten(m *LiftAlongsideFlatten, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// keep <- keep
	if v := m.GetKeep(); v != "" {
		e.FieldStart("keep")
		e.Str(v)
	}
	// email <- buyer.profile.contact.email
	if v := m.GetBuyer().GetProfile().GetContact().GetEmail(); v != "" {
		e.FieldStart("email")
		e.Str(v)
	}
	e.ObjEnd()
	return nil
}

// encodePlainJSON_PickFromStruct writes spec.selection.PickFromStruct as a flat JSON object.
func encodePlainJSON_PickFromStruct(m *PickFromStruct, e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	// userId <- attrs.user.id
	if picked, ok := plainjsonpb.PickStruct(m.GetAttrs(), "user.id"); ok {
		e.FieldStart("userId")
		plainjsonpb.Value(e, picked)
	}
	e.ObjEnd()
	return nil
}
